-- PETATOE P5.13.7 — Add Appointment Localization + Dashboard Calendar Locale
insert into public.app_translations
(translation_key,screen_key,module_name,text_type,ar_text,en_text,default_ar,default_en,is_active)
values
('dashboard.calendar.previousMonth','dashboard','dashboard','aria','الشهر السابق','Previous month','الشهر السابق','Previous month',true),
('dashboard.calendar.nextMonth','dashboard','dashboard','aria','الشهر التالي','Next month','الشهر التالي','Next month',true),
('dashboard.calendar.today','dashboard','dashboard','button','اليوم','Today','اليوم','Today',true),
('dashboard.calendar.clear','dashboard','dashboard','button','مسح','Clear','مسح','Clear',true),
('appointmentNew.page.title','installationRequestNew','appointments','title','إضافة موعد جديد','Add New Appointment','إضافة موعد جديد','Add New Appointment',true),
('appointmentNew.page.subtitle','installationRequestNew','appointments','subtitle','إنشاء موعد بعقد أو بدونه','Create an appointment with or without a contract','إنشاء موعد بعقد أو بدونه','Create an appointment with or without a contract',true),
('appointmentNew.intro.note','installationRequestNew','appointments','help','سجّل بيانات العميل والخدمات والحيوان والتحصيل. ينتقل الموعد بعد الحفظ إلى المواعيد بحالة بانتظار المراجعة.','Enter customer, service, pet, and collection details. After saving, the appointment moves to appointments pending review.','سجّل بيانات العميل والخدمات والحيوان والتحصيل. ينتقل الموعد بعد الحفظ إلى المواعيد بحالة بانتظار المراجعة.','Enter customer, service, pet, and collection details. After saving, the appointment moves to appointments pending review.',true),
('appointmentNew.common.optional','installationRequestNew','appointments','label','اختياري','Optional','اختياري','Optional',true),
('appointmentNew.common.required','installationRequestNew','appointments','label','مطلوب','Required','مطلوب','Required',true),
('appointmentNew.customer.title','installationRequestNew','appointments','title','بيانات العميل','Customer Details','بيانات العميل','Customer Details',true),
('appointmentNew.customer.note','installationRequestNew','appointments','help','اختر العميل والحي، واربط الموعد بعقد العميل إن وجد.','Select the customer and district, and link the appointment to a customer contract if available.','اختر العميل والحي، واربط الموعد بعقد العميل إن وجد.','Select the customer and district, and link the appointment to a customer contract if available.',true),
('appointmentNew.customer.name','installationRequestNew','appointments','label','اسم العميل','Customer Name','اسم العميل','Customer Name',true),
('appointmentNew.customer.search','installationRequestNew','appointments','placeholder','ابحث بالاسم أو رقم الجوال أو رقم العميل','Search by name, mobile number, or customer number','ابحث بالاسم أو رقم الجوال أو رقم العميل','Search by name, mobile number, or customer number',true),
('appointmentNew.customer.searchHint','installationRequestNew','appointments','help','يمكن البحث باسم العميل أو رقم الجوال أو رقم العميل.','You can search by customer name, mobile number, or customer number.','يمكن البحث باسم العميل أو رقم الجوال أو رقم العميل.','You can search by customer name, mobile number, or customer number.',true),
('appointmentNew.customer.district','installationRequestNew','appointments','label','الحي','District','الحي','District',true),
('appointmentNew.customer.districtHint','installationRequestNew','appointments','help','القائمة الحالية مخصصة لأحياء جدة فقط.','The current list is limited to Jeddah districts.','القائمة الحالية مخصصة لأحياء جدة فقط.','The current list is limited to Jeddah districts.',true),
('appointmentNew.customer.contract','installationRequestNew','appointments','label','رقم العقد (اختياري)','Contract Number (Optional)','رقم العقد (اختياري)','Contract Number (Optional)',true),
('appointmentNew.customer.noContract','installationRequestNew','appointments','option','بدون عقد','No contract','بدون عقد','No contract',true),
('appointmentNew.customer.contractHint','installationRequestNew','appointments','help','تظهر عقود العميل المقبولة والمتاحة فقط.','Only the customer''s accepted and available contracts are shown.','تظهر عقود العميل المقبولة والمتاحة فقط.','Only the customer''s accepted and available contracts are shown.',true),
('appointmentNew.customer.location','installationRequestNew','appointments','label','موقع العميل (رابط Google Maps)','Customer Location (Google Maps link)','موقع العميل (رابط Google Maps)','Customer Location (Google Maps link)',true),
('appointmentNew.customer.locationHint','installationRequestNew','appointments','help','الصق رابط مشاركة الموقع من Google Maps ليظهر للفريق زر فتح الموقع.','Paste the Google Maps sharing link so the team can open the customer location.','الصق رابط مشاركة الموقع من Google Maps ليظهر للفريق زر فتح الموقع.','Paste the Google Maps sharing link so the team can open the customer location.',true),
('appointmentNew.services.title','installationRequestNew','appointments','title','تفاصيل الخدمة','Service Details','تفاصيل الخدمة','Service Details',true),
('appointmentNew.services.note','installationRequestNew','appointments','help','أضف خدمة واحدة أو أكثر، ثم اختر نوع الخصم. ضريبة القيمة المضافة ثابتة 15%، ثم يطبق الخصم على الإجمالي شامل الضريبة.','Add one or more services, then select the discount type. VAT is fixed at 15%, and the discount is applied to the VAT-inclusive total.','أضف خدمة واحدة أو أكثر، ثم اختر نوع الخصم. ضريبة القيمة المضافة ثابتة 15%، ثم يطبق الخصم على الإجمالي شامل الضريبة.','Add one or more services, then select the discount type. VAT is fixed at 15%, and the discount is applied to the VAT-inclusive total.',true),
('appointmentNew.services.type','installationRequestNew','appointments','label','نوع الخدمة','Service Type','نوع الخدمة','Service Type',true),
('appointmentNew.services.quantity','installationRequestNew','appointments','label','عدد الخدمات','Quantity','عدد الخدمات','Quantity',true),
('appointmentNew.services.price','installationRequestNew','appointments','label','سعر الخدمة','Service Price','سعر الخدمة','Service Price',true),
('appointmentNew.services.total','installationRequestNew','appointments','label','الإجمالي','Total','الإجمالي','Total',true),
('appointmentNew.services.action','installationRequestNew','appointments','label','إجراء','Action','إجراء','Action',true),
('appointmentNew.services.add','installationRequestNew','appointments','button','إضافة خدمة أخرى','Add Another Service','إضافة خدمة أخرى','Add Another Service',true),
('appointmentNew.services.select','installationRequestNew','appointments','option','اختر نوع الخدمة','Select service type','اختر نوع الخدمة','Select service type',true),
('appointmentNew.services.search','installationRequestNew','appointments','placeholder','ابحث عن خدمة...','Search for a service...','ابحث عن خدمة...','Search for a service...',true),
('appointmentNew.services.searchAria','installationRequestNew','appointments','aria','البحث في الخدمات','Search services','البحث في الخدمات','Search services',true),
('appointmentNew.services.noMatch','installationRequestNew','appointments','empty','لا توجد خدمة مطابقة للبحث.','No matching service found.','لا توجد خدمة مطابقة للبحث.','No matching service found.',true),
('appointmentNew.services.remove','installationRequestNew','appointments','button','حذف','Remove','حذف','Remove',true),
('appointmentNew.discount.type','installationRequestNew','appointments','label','نوع الخصم','Discount Type','نوع الخصم','Discount Type',true),
('appointmentNew.discount.amount','installationRequestNew','appointments','option','قيمة (SAR)','Amount (SAR)','قيمة (SAR)','Amount (SAR)',true),
('appointmentNew.discount.percentage','installationRequestNew','appointments','option','نسبة (%)','Percentage (%)','نسبة (%)','Percentage (%)',true),
('appointmentNew.discount.amountLabel','installationRequestNew','appointments','label','قيمة الخصم (SAR)','Discount Amount (SAR)','قيمة الخصم (SAR)','Discount Amount (SAR)',true),
('appointmentNew.discount.percentageLabel','installationRequestNew','appointments','label','نسبة الخصم (%)','Discount Percentage (%)','نسبة الخصم (%)','Discount Percentage (%)',true),
('appointmentNew.summary.quantity','installationRequestNew','appointments','label','إجمالي عدد الخدمات','Total Service Quantity','إجمالي عدد الخدمات','Total Service Quantity',true),
('appointmentNew.summary.subtotal','installationRequestNew','appointments','label','إجمالي الخدمات قبل الضريبة','Services Subtotal Before VAT','إجمالي الخدمات قبل الضريبة','Services Subtotal Before VAT',true),
('appointmentNew.summary.tax','installationRequestNew','appointments','label','ضريبة القيمة المضافة (15%)','VAT (15%)','ضريبة القيمة المضافة (15%)','VAT (15%)',true),
('appointmentNew.summary.discount','installationRequestNew','appointments','label','الخصم بعد الضريبة','Discount After VAT','الخصم بعد الضريبة','Discount After VAT',true),
('appointmentNew.summary.final','installationRequestNew','appointments','label','الإجمالي النهائي','Final Total','الإجمالي النهائي','Final Total',true),
('appointmentNew.animals.title','installationRequestNew','appointments','title','بيانات الحيوان','Pet Details','بيانات الحيوان','Pet Details',true),
('appointmentNew.animals.note','installationRequestNew','appointments','help','أضف بيانات الحيوان أو أكثر المرتبطين بالموعد.','Add details for one or more pets linked to the appointment.','أضف بيانات الحيوان أو أكثر المرتبطين بالموعد.','Add details for one or more pets linked to the appointment.',true),
('appointmentNew.animals.name','installationRequestNew','appointments','label','اسم الحيوان','Pet Name','اسم الحيوان','Pet Name',true),
('appointmentNew.animals.type','installationRequestNew','appointments','label','نوع الحيوان','Pet Type','نوع الحيوان','Pet Type',true),
('appointmentNew.animals.breed','installationRequestNew','appointments','label','السلالة','Breed','السلالة','Breed',true),
('appointmentNew.animals.size','installationRequestNew','appointments','label','الحجم','Size','الحجم','Size',true),
('appointmentNew.animals.quantity','installationRequestNew','appointments','label','العدد','Quantity','العدد','Quantity',true),
('appointmentNew.animals.actions','installationRequestNew','appointments','label','الإجراءات','Actions','الإجراءات','Actions',true),
('appointmentNew.animals.add','installationRequestNew','appointments','button','إضافة حيوان آخر','Add Another Pet','إضافة حيوان آخر','Add Another Pet',true),
('appointmentNew.animals.selectType','installationRequestNew','appointments','option','اختر النوع','Select type','اختر النوع','Select type',true),
('appointmentNew.animals.dog','installationRequestNew','appointments','option','كلب','Dog','كلب','Dog',true),
('appointmentNew.animals.cat','installationRequestNew','appointments','option','قط','Cat','قط','Cat',true),
('appointmentNew.animals.other','installationRequestNew','appointments','option','أخرى','Other','أخرى','Other',true),
('appointmentNew.animals.selectBreed','installationRequestNew','appointments','option','اختر السلالة','Select breed','اختر السلالة','Select breed',true),
('appointmentNew.animals.selectSize','installationRequestNew','appointments','option','اختر الحجم','Select size','اختر الحجم','Select size',true),
('appointmentNew.animals.small','installationRequestNew','appointments','option','صغير','Small','صغير','Small',true),
('appointmentNew.animals.medium','installationRequestNew','appointments','option','متوسط','Medium','متوسط','Medium',true),
('appointmentNew.animals.large','installationRequestNew','appointments','option','كبير','Large','كبير','Large',true),
('appointmentNew.animals.saved','installationRequestNew','appointments','label','محفوظ سابقًا','Previously saved','محفوظ سابقًا','Previously saved',true),
('appointmentNew.collection.title','installationRequestNew','appointments','title','التحصيل','Collection','التحصيل','Collection',true),
('appointmentNew.collection.note','installationRequestNew','appointments','help','قيمة الموعد والخصم تتحدثان تلقائيًا من تفاصيل الخدمة.','Appointment value and discount update automatically from service details.','قيمة الموعد والخصم تتحدثان تلقائيًا من تفاصيل الخدمة.','Appointment value and discount update automatically from service details.',true),
('appointmentNew.collection.sessionValue','installationRequestNew','appointments','label','قيمة الجلسة','Session Value','قيمة الجلسة','Session Value',true),
('appointmentNew.collection.discount','installationRequestNew','appointments','label','إجمالي الخصم','Total Discount','إجمالي الخصم','Total Discount',true),
('appointmentNew.collection.collected','installationRequestNew','appointments','label','المبلغ المحصل','Amount Collected','المبلغ المحصل','Amount Collected',true),
('appointmentNew.collection.status','installationRequestNew','appointments','label','حالة التحصيل','Collection Status','حالة التحصيل','Collection Status',true),
('appointmentNew.collection.uncollected','installationRequestNew','appointments','option','غير محصل','Not Collected','غير محصل','Not Collected',true),
('appointmentNew.collection.partial','installationRequestNew','appointments','option','محصل جزئيًا','Partially Collected','محصل جزئيًا','Partially Collected',true),
('appointmentNew.collection.full','installationRequestNew','appointments','option','محصل بالكامل','Fully Collected','محصل بالكامل','Fully Collected',true),
('appointmentNew.collection.payment','installationRequestNew','appointments','label','طريقة الدفع','Payment Method','طريقة الدفع','Payment Method',true),
('appointmentNew.collection.paymentChoose','installationRequestNew','appointments','option','اختر طريقة الدفع','Select payment method','اختر طريقة الدفع','Select payment method',true),
('appointmentNew.collection.cash','installationRequestNew','appointments','option','نقدي','Cash','نقدي','Cash',true),
('appointmentNew.collection.card','installationRequestNew','appointments','option','بطاقة / شبكة','Card / POS','بطاقة / شبكة','Card / POS',true),
('appointmentNew.collection.bank','installationRequestNew','appointments','option','تحويل بنكي','Bank Transfer','تحويل بنكي','Bank Transfer',true),
('appointmentNew.collection.website','installationRequestNew','appointments','option','الدفع عن طريق الموقع','Website Payment','الدفع عن طريق الموقع','Website Payment',true),
('appointmentNew.collection.appointmentStatus','installationRequestNew','appointments','label','الحالة','Status','الحالة','Status',true),
('appointmentNew.collection.pendingReview','installationRequestNew','appointments','label','بانتظار المراجعة','Pending Review','بانتظار المراجعة','Pending Review',true),
('appointmentNew.schedule.title','installationRequestNew','appointments','title','جدولة الموعد','Schedule Appointment','جدولة الموعد','Schedule Appointment',true),
('appointmentNew.schedule.note','installationRequestNew','appointments','help','يمكن جدولة الموعد الآن، أو تركه لينتقل إلى قائمة انتظار الجدولة. أضف الملاحظات التشغيلية مع الجدولة.','You can schedule the appointment now or leave it in the scheduling queue. Add operational notes with the schedule.','يمكن جدولة الموعد الآن، أو تركه لينتقل إلى قائمة انتظار الجدولة. أضف الملاحظات التشغيلية مع الجدولة.','You can schedule the appointment now or leave it in the scheduling queue. Add operational notes with the schedule.',true),
('appointmentNew.schedule.date','installationRequestNew','appointments','label','تاريخ الموعد','Appointment Date','تاريخ الموعد','Appointment Date',true),
('appointmentNew.schedule.time','installationRequestNew','appointments','label','وقت الموعد','Appointment Time','وقت الموعد','Appointment Time',true),
('appointmentNew.schedule.later','installationRequestNew','appointments','option','يحدد لاحقًا','Set later','يحدد لاحقًا','Set later',true),
('appointmentNew.schedule.time12','installationRequestNew','appointments','option','12:00 ظهرًا','12:00 PM','12:00 ظهرًا','12:00 PM',true),
('appointmentNew.schedule.time14','installationRequestNew','appointments','option','2:00 مساءً','2:00 PM','2:00 مساءً','2:00 PM',true),
('appointmentNew.schedule.time16','installationRequestNew','appointments','option','4:00 مساءً','4:00 PM','4:00 مساءً','4:00 PM',true),
('appointmentNew.schedule.time18','installationRequestNew','appointments','option','6:00 مساءً','6:00 PM','6:00 مساءً','6:00 PM',true),
('appointmentNew.schedule.time20','installationRequestNew','appointments','option','8:00 مساءً','8:00 PM','8:00 مساءً','8:00 PM',true),
('appointmentNew.schedule.time22','installationRequestNew','appointments','option','10:00 مساءً','10:00 PM','10:00 مساءً','10:00 PM',true),
('appointmentNew.schedule.team','installationRequestNew','appointments','label','الفرقة / السيارة','Team / Vehicle','الفرقة / السيارة','Team / Vehicle',true),
('appointmentNew.schedule.teamLater','installationRequestNew','appointments','option','تحدد لاحقًا','Set later','تحدد لاحقًا','Set later',true),
('appointmentNew.schedule.groomer','installationRequestNew','appointments','label','الجرومر','Groomer','الجرومر','Groomer',true),
('appointmentNew.schedule.groomerPlaceholder','installationRequestNew','appointments','placeholder','اسم الجرومر','Groomer name','اسم الجرومر','Groomer name',true),
('appointmentNew.schedule.notes','installationRequestNew','appointments','label','ملاحظات الموعد','Appointment Notes','ملاحظات الموعد','Appointment Notes',true),
('appointmentNew.schedule.notesPlaceholder','installationRequestNew','appointments','placeholder','اكتب تعليمات العميل أو تفاصيل الموقع أو أي متطلبات خاصة','Enter customer instructions, location details, or any special requirements','اكتب تعليمات العميل أو تفاصيل الموقع أو أي متطلبات خاصة','Enter customer instructions, location details, or any special requirements',true),
('appointmentNew.schedule.hint','installationRequestNew','appointments','help','إذا اكتملت بيانات الجدولة سيظهر الموعد مباشرة في الجدول. إذا تُركت فارغة سيبقى في انتظار الجدولة.','If scheduling details are complete, the appointment appears directly on the schedule. If left blank, it remains pending scheduling.','إذا اكتملت بيانات الجدولة سيظهر الموعد مباشرة في الجدول. إذا تُركت فارغة سيبقى في انتظار الجدولة.','If scheduling details are complete, the appointment appears directly on the schedule. If left blank, it remains pending scheduling.',true),
('appointmentNew.action.reset','installationRequestNew','appointments','button','إعادة تعيين','Reset','إعادة تعيين','Reset',true),
('appointmentNew.action.save','installationRequestNew','appointments','button','حفظ الموعد','Save Appointment','حفظ الموعد','Save Appointment',true),
('appointmentNew.action.saving','installationRequestNew','appointments','button','جاري الحفظ...','Saving...','جاري الحفظ...','Saving...',true),
('appointmentNew.action.saved','installationRequestNew','appointments','button','تم الحفظ','Saved','تم الحفظ','Saved',true),
('appointmentNew.action.saveError','installationRequestNew','appointments','button','تعذر الحفظ','Save Failed','تعذر الحفظ','Save Failed',true)
on conflict (translation_key) do update set
screen_key=excluded.screen_key,module_name=excluded.module_name,text_type=excluded.text_type,
default_ar=excluded.default_ar,default_en=excluded.default_en,
ar_text=case when coalesce(public.app_translations.ar_text,'')='' then excluded.ar_text else public.app_translations.ar_text end,
en_text=case when coalesce(public.app_translations.en_text,'')='' then excluded.en_text else public.app_translations.en_text end,
is_active=true;

select translation_key,ar_text,en_text from public.app_translations
where (translation_key like 'appointmentNew.%' or translation_key like 'dashboard.calendar.%')
and (coalesce(trim(ar_text),'')='' or coalesce(trim(en_text),'')='');
