-- P5.13.4 Customer Management Localization + User Default Language

alter table public.user_profiles add column if not exists default_language text not null default 'ar';
alter table public.user_profiles drop constraint if exists user_profiles_default_language_check;
alter table public.user_profiles add constraint user_profiles_default_language_check check (default_language in ('ar','en'));
update public.user_profiles set default_language='ar' where default_language is null or default_language not in ('ar','en');

insert into public.app_translations
  (translation_key,screen_key,module_name,text_type,ar_text,en_text)
values
  ('customers.page.title','customers','customers','title','العملاء','Customers'),
  ('customers.page.subtitle','customers','customers','subtitle','إدارة بيانات العملاء والبحث والتصفية','Manage customer data, search, and filtering'),
  ('followups.page.title','followups','customers','title','المتابعات','Follow-ups'),
  ('followups.page.subtitle','followups','customers','subtitle','سجل التواصل والمتابعات القادمة لكل عميل','Communication history and upcoming follow-ups for each customer'),
  ('contracts.page.title','quotations','customers','title','عقود العملاء','Customer Contracts'),
  ('contracts.page.subtitle','quotations','customers','subtitle','إدارة عقود العملاء وحالتها وقيمتها','Manage customer contracts, statuses, and values'),
  ('invoices.page.title','salesInvoices','customers','title','فواتير المبيعات','Sales Invoices'),
  ('invoices.page.subtitle','salesInvoices','customers','subtitle','سجل الفواتير المرتبطة بالعقود والمواعيد','Invoices linked to contracts and appointments'),
  ('customers.search.placeholder','customers','customers','placeholder','بحث بالكود أو الاسم أو العنوان أو الجوال...','Search by code, name, address, or mobile...'),
  ('customers.import','customers','customers','button','رفع عملاء Excel','Import Customers Excel'),
  ('customers.template','customers','customers','button','تنزيل نموذج Excel','Download Excel Template'),
  ('customers.add','customers','customers','button','إضافة عميل','Add Customer'),
  ('customers.col.code','customers','customers','label','code','Code'),
  ('customers.col.name','customers','customers','label','name','Name'),
  ('customers.col.address','customers','customers','label','address','Address'),
  ('customers.col.mobile','customers','customers','label','mobile','Mobile'),
  ('customers.col.maps','customers','customers','label','موقع Google Maps','Google Maps Location'),
  ('customers.col.actions','customers','customers','label','الإجراءات','Actions'),
  ('customers.action.view','customers','customers','button','عرض','View'),
  ('customers.action.followup','customers','customers','button','متابعة','Follow-up'),
  ('customers.action.edit','customers','customers','button','تعديل','Edit'),
  ('customers.action.delete','customers','customers','button','حذف','Delete'),
  ('customers.action.openMap','customers','customers','button','فتح الموقع','Open location'),
  ('customers.empty','customers','customers','empty','لا توجد نتائج مطابقة.','No matching results.'),
  ('customers.loading','customers','customers','status','جاري تحميل بيانات العملاء...','Loading customer data...'),
  ('customers.count','customers','customers','format','{count} عميل','{count} customers'),
  ('customers.prev','customers','customers','button','السابق','Previous'),
  ('customers.next','customers','customers','button','التالي','Next'),
  ('customers.dialog.add','customers','customers','title','إضافة عميل جديد','Add New Customer'),
  ('customers.dialog.edit','customers','customers','title','تعديل بيانات العميل','Edit Customer'),
  ('customers.dialog.note','customers','customers','help','بيانات العميل الأساسية فقط.','Basic customer information only.'),
  ('customers.dialog.neighborhoodPlaceholder','customers','customers','placeholder','ابحث واختر الحي','Search and select a district'),
  ('customers.dialog.neighborhoodAria','customers','customers','label','فتح قائمة الأحياء','Open district list'),
  ('customers.dialog.mapsPlaceholder','customers','customers','placeholder','https://maps.app.goo.gl/...','https://maps.app.goo.gl/...'),
  ('customers.dialog.cancel','customers','customers','button','إلغاء','Cancel'),
  ('customers.dialog.save','customers','customers','button','حفظ العميل','Save Customer'),
  ('customers.dialog.loading','customers','customers','status','جاري تحميل البيانات...','Loading data...'),
  ('customers.dialog.saving','customers','customers','status','جاري الحفظ...','Saving...'),
  ('customers.unknown','customers','customers','status','عميل غير معروف','Unknown customer'),
  ('followups.title','followups','customers','title','سجل متابعات العملاء','Customer Follow-up Log'),
  ('followups.note','followups','customers','help','كل تواصل مع العميل يُحفظ كسجل مستقل دون حذف التاريخ السابق.','Every customer interaction is saved as a separate record without deleting previous history.'),
  ('followups.exportPdf','followups','customers','button','تصدير PDF','Export PDF'),
  ('followups.whatsappPdf','followups','customers','button','إرسال التقرير واتساب PDF','Send Report via WhatsApp PDF'),
  ('followups.add','followups','customers','button','إضافة متابعة','Add Follow-up'),
  ('followups.search.placeholder','followups','customers','placeholder','بحث باسم العميل أو رقم الجوال أو المندوب...','Search by customer name, mobile number, or representative...'),
  ('followups.filter.all','followups','customers','option','كل المتابعات','All follow-ups'),
  ('followups.filter.today','followups','customers','option','متابعات اليوم','Today''s follow-ups'),
  ('followups.filter.overdue','followups','customers','option','متابعات متأخرة','Overdue follow-ups'),
  ('followups.filter.upcoming','followups','customers','option','متابعات قادمة','Upcoming follow-ups'),
  ('followups.filter.completed','followups','customers','option','متابعات مكتملة','Completed follow-ups'),
  ('followups.filter.allReps','followups','customers','option','كل المندوبين','All representatives'),
  ('followups.col.customer','followups','customers','label','العميل','Customer'),
  ('followups.col.phone','followups','customers','label','رقم العميل','Customer Number'),
  ('followups.col.contactDate','followups','customers','label','تاريخ التواصل','Contact Date'),
  ('followups.col.method','followups','customers','label','طريقة التواصل','Contact Method'),
  ('followups.col.rep','followups','customers','label','المندوب','Representative'),
  ('followups.col.result','followups','customers','label','نتيجة التواصل','Contact Result'),
  ('followups.col.contract','followups','customers','label','العقد','Contract'),
  ('followups.col.next','followups','customers','label','المتابعة القادمة','Next Follow-up'),
  ('followups.col.status','followups','customers','label','الحالة','Status'),
  ('followups.col.actions','followups','customers','label','الإجراءات','Actions'),
  ('followups.stats.total','followups','customers','label','إجمالي المتابعات','Total Follow-ups'),
  ('followups.stats.today','followups','customers','label','متابعات اليوم','Today''s Follow-ups'),
  ('followups.stats.overdue','followups','customers','label','المتابعات المتأخرة','Overdue Follow-ups'),
  ('followups.stats.upcoming','followups','customers','label','المتابعات القادمة','Upcoming Follow-ups'),
  ('followups.empty','followups','customers','empty','لا توجد متابعات مطابقة.','No matching follow-ups.'),
  ('followups.loading','followups','customers','status','جاري تحميل المتابعات...','Loading follow-ups...'),
  ('followups.count','followups','customers','format','{count} متابعة','{count} follow-ups'),
  ('followups.dialog.add','followups','customers','title','إضافة متابعة جديدة','Add New Follow-up'),
  ('followups.dialog.edit','followups','customers','title','تعديل المتابعة','Edit Follow-up'),
  ('followups.dialog.note','followups','customers','help','سيتم الاحتفاظ بكل متابعة داخل سجل العميل.','Each follow-up will be kept in the customer record.'),
  ('followups.dialog.customer','followups','customers','label','العميل','Customer'),
  ('followups.dialog.contactDate','followups','customers','label','تاريخ التواصل','Contact Date'),
  ('followups.dialog.method','followups','customers','label','طريقة التواصل','Contact Method'),
  ('followups.dialog.rep','followups','customers','label','المندوب المسؤول','Responsible Representative'),
  ('followups.dialog.result','followups','customers','label','نتيجة التواصل','Contact Result'),
  ('followups.dialog.contractNumber','followups','customers','label','رقم العقد','Contract Number'),
  ('followups.dialog.noSaleReason','followups','customers','label','سبب عدم البيع','Reason for No Sale'),
  ('followups.dialog.nextDate','followups','customers','label','تاريخ المتابعة القادمة','Next Follow-up Date'),
  ('followups.dialog.status','followups','customers','label','حالة المتابعة','Follow-up Status'),
  ('followups.dialog.notes','followups','customers','label','ملاحظات المتابعة','Follow-up Notes'),
  ('followups.dialog.cancel','followups','customers','button','إلغاء','Cancel'),
  ('followups.dialog.save','followups','customers','button','حفظ المتابعة','Save Follow-up'),
  ('followups.method.call','followups','customers','option','اتصال','Call'),
  ('followups.method.whatsapp','followups','customers','option','واتساب','WhatsApp'),
  ('followups.method.visit','followups','customers','option','زيارة','Visit'),
  ('followups.method.email','followups','customers','option','بريد إلكتروني','Email'),
  ('followups.method.meeting','followups','customers','option','اجتماع','Meeting'),
  ('followups.result.contacted','followups','customers','option','تم التواصل','Contacted'),
  ('followups.result.noAnswer','followups','customers','option','لم يتم الرد','No Answer'),
  ('followups.result.requestContract','followups','customers','option','طلب عقد','Requested Contract'),
  ('followups.result.sentContract','followups','customers','option','تم إرسال عقد','Contract Sent'),
  ('followups.result.negotiation','followups','customers','option','تفاوض','Negotiation'),
  ('followups.result.sold','followups','customers','option','تم البيع','Sold'),
  ('followups.result.notSold','followups','customers','option','لم يتم البيع','Not Sold'),
  ('followups.result.deferred','followups','customers','option','مؤجل','Deferred'),
  ('followups.status.open','followups','customers','option','مفتوحة','Open'),
  ('followups.status.completed','followups','customers','option','مكتملة','Completed'),
  ('followups.status.today','followups','customers','status','اليوم','Today'),
  ('followups.status.overdue','followups','customers','status','متأخرة','Overdue'),
  ('followups.status.upcoming','followups','customers','status','قادمة','Upcoming'),
  ('contracts.action.createAppointment','quotations','customers','button','إنشاء موعد','Create Appointment'),
  ('contracts.action.toInvoice','quotations','customers','button','تحويل إلى فاتورة','Convert to Invoice'),
  ('contracts.action.openInvoice','quotations','customers','button','فتح الفاتورة','Open Invoice'),
  ('contracts.action.openAppointment','quotations','customers','button','فتح الموعد','Open Appointment'),
  ('contracts.title','quotations','customers','title','إدارة عقود العملاء','Customer Contracts'),
  ('contracts.note','quotations','customers','help','تسجيل عقود العملاء وربطها بالعملاء ومتابعة حالتها وقيمتها.','Register customer contracts, link them to customers, and track their status and value.'),
  ('contracts.exportPdf','quotations','customers','button','تصدير PDF','Export PDF'),
  ('contracts.whatsappPdf','quotations','customers','button','إرسال التقرير واتساب PDF','Send Report via WhatsApp PDF'),
  ('contracts.add','quotations','customers','button','إضافة عقد','Add Contract'),
  ('contracts.search.placeholder','quotations','customers','placeholder','بحث برقم العقد أو رقم طلب العميل أو العميل أو المندوب...','Search by contract number, customer order number, customer, or representative...'),
  ('contracts.filter.allStatuses','quotations','customers','option','كل الحالات','All statuses'),
  ('contracts.status.inProgress','quotations','customers','status','قيد التنفيذ','In Progress'),
  ('contracts.status.accepted','quotations','customers','status','مقبول','Accepted'),
  ('contracts.status.rejected','quotations','customers','status','مرفوض','Rejected'),
  ('contracts.filter.unconverted','quotations','customers','option','غير محول إلى موعد','Not Converted to Appointment'),
  ('contracts.filter.converted','quotations','customers','option','تم تحويله إلى موعد','Converted to Appointment'),
  ('contracts.filter.all','quotations','customers','option','الكل','All'),
  ('contracts.filter.allReps','quotations','customers','option','كل المندوبين','All representatives'),
  ('contracts.col.number','quotations','customers','label','رقم العقد','Contract Number'),
  ('contracts.col.customer','quotations','customers','label','العميل','Customer'),
  ('contracts.col.phone','quotations','customers','label','رقم العميل','Customer Number'),
  ('contracts.col.rep','quotations','customers','label','المندوب','Representative'),
  ('contracts.col.date','quotations','customers','label','تاريخ العقد','Contract Date'),
  ('contracts.col.value','quotations','customers','label','القيمة','Value'),
  ('contracts.col.status','quotations','customers','label','الحالة','Status'),
  ('contracts.col.expiry','quotations','customers','label','تاريخ الانتهاء','Expiry Date'),
  ('contracts.col.rejectReason','quotations','customers','label','سبب الرفض','Rejection Reason'),
  ('contracts.col.actions','quotations','customers','label','الإجراءات','Actions'),
  ('contracts.stats.total','quotations','customers','label','إجمالي العقود','Total Contracts'),
  ('contracts.stats.totalValue','quotations','customers','label','إجمالي القيمة','Total Value'),
  ('contracts.stats.accepted','quotations','customers','label','العقود المقبولة','Accepted Contracts'),
  ('contracts.stats.acceptedValue','quotations','customers','label','قيمة العقود المقبولة','Accepted Contracts Value'),
  ('contracts.stats.rejected','quotations','customers','label','العقود المرفوضة','Rejected Contracts'),
  ('contracts.stats.conversion','quotations','customers','label','نسبة التحويل','Conversion Rate'),
  ('contracts.empty','quotations','customers','empty','لا توجد عقود مطابقة.','No matching contracts.'),
  ('contracts.loading','quotations','customers','status','جاري تحميل عقود العملاء...','Loading customer contracts...'),
  ('contracts.count','quotations','customers','format','{count} عقد','{count} contracts'),
  ('contracts.dialog.add','quotations','customers','title','إضافة عقد','Add Contract'),
  ('contracts.dialog.edit','quotations','customers','title','تعديل العقد','Edit Contract'),
  ('contracts.dialog.note','quotations','customers','help','أدخل بيانات العقد واربطه بالعميل والمندوب.','Enter contract details and link it to the customer and representative.'),
  ('contracts.dialog.customerOrder','quotations','customers','label','رقم طلب العميل (اختياري)','Customer Order Number (optional)'),
  ('contracts.dialog.customerOrderPlaceholder','quotations','customers','placeholder','رقم أمر الشراء أو طلب العميل','Purchase order or customer request number'),
  ('contracts.dialog.customerSearchPlaceholder','quotations','customers','placeholder','ابحث باسم العميل أو رقم الجوال...','Search by customer name or mobile number...'),
  ('contracts.dialog.openCustomers','quotations','customers','label','فتح قائمة العملاء','Open customer list'),
  ('contracts.dialog.customerResults','quotations','customers','label','نتائج بحث العملاء','Customer search results'),
  ('contracts.dialog.customerHint','quotations','customers','help','يمكن البحث بالاسم أو رقم الجوال أو كود العميل.','You can search by name, mobile number, or customer code.'),
  ('contracts.dialog.amount','quotations','customers','label','قيمة العقد','Contract Value'),
  ('contracts.dialog.expiry','quotations','customers','label','تاريخ انتهاء العقد','Contract Expiry Date'),
  ('contracts.dialog.description','quotations','customers','label','تفاصيل العقد','Contract Details'),
  ('contracts.dialog.descriptionPlaceholder','quotations','customers','placeholder','وصف مختصر للخدمات أو البنود المشمولة في العقد','Brief description of services or terms included in the contract'),
  ('contracts.dialog.notes','quotations','customers','label','ملاحظات','Notes'),
  ('contracts.dialog.cancel','quotations','customers','button','إلغاء','Cancel'),
  ('contracts.dialog.save','quotations','customers','button','حفظ العقد','Save Contract'),
  ('invoices.title','salesInvoices','customers','title','فواتير المبيعات','Sales Invoices'),
  ('invoices.note','salesInvoices','customers','help','سجل موحد للفواتير الناتجة من عقود العملاء وتأكيد انتهاء المواعيد.','Unified record of invoices generated from customer contracts and appointment completion confirmations.'),
  ('invoices.refresh','salesInvoices','customers','button','تحديث','Refresh'),
  ('invoices.summary.count','salesInvoices','customers','label','عدد الفواتير','Invoice Count'),
  ('invoices.summary.amount','salesInvoices','customers','label','إجمالي قيمة الفواتير','Total Invoice Value'),
  ('invoices.summary.cost','salesInvoices','customers','label','إجمالي مصاريف الموعد','Total Appointment Expenses'),
  ('invoices.search.placeholder','salesInvoices','customers','placeholder','بحث برقم الطلب أو العميل أو رقم الفاتورة أو المندوب...','Search by request number, customer, invoice number, or representative...'),
  ('invoices.filter.allSources','salesInvoices','customers','option','كل المصادر','All Sources'),
  ('invoices.source.contract','salesInvoices','customers','status','عقد','Contract'),
  ('invoices.source.appointment','salesInvoices','customers','status','موعد','Appointment'),
  ('invoices.filter.allStatuses','salesInvoices','customers','option','كل الحالات','All Statuses'),
  ('invoices.status.issued','salesInvoices','customers','status','صادرة','Issued'),
  ('invoices.status.cancelled','salesInvoices','customers','status','ملغاة','Cancelled'),
  ('invoices.date.from','salesInvoices','customers','label','من تاريخ','From Date'),
  ('invoices.date.to','salesInvoices','customers','label','إلى تاريخ','To Date'),
  ('invoices.reset','salesInvoices','customers','button','إعادة تعيين','Reset'),
  ('invoices.col.request','salesInvoices','customers','label','رقم الطلب','Request Number'),
  ('invoices.col.customer','salesInvoices','customers','label','اسم العميل','Customer Name'),
  ('invoices.col.invoice','salesInvoices','customers','label','رقم الفاتورة','Invoice Number'),
  ('invoices.col.amount','salesInvoices','customers','label','قيمة الفاتورة','Invoice Amount'),
  ('invoices.col.cost','salesInvoices','customers','label','مصاريف الموعد','Appointment Expenses'),
  ('invoices.col.rep','salesInvoices','customers','label','اسم المندوب','Representative Name'),
  ('invoices.col.date','salesInvoices','customers','label','تاريخ الفاتورة','Invoice Date'),
  ('invoices.col.source','salesInvoices','customers','label','المصدر','Source'),
  ('invoices.col.status','salesInvoices','customers','label','الحالة','Status'),
  ('invoices.loading','salesInvoices','customers','status','جاري تحميل الفواتير...','Loading invoices...'),
  ('invoices.empty','salesInvoices','customers','empty','لا توجد فواتير مطابقة.','No matching invoices.'),
  ('users.defaultLanguage','users','users','label','اللغة الافتراضية','Default Language'),
  ('users.language.ar','users','users','option','العربية','Arabic'),
  ('users.language.en','users','users','option','English','English')
on conflict (translation_key) do update set
  screen_key=excluded.screen_key,module_name=excluded.module_name,text_type=excluded.text_type,default_ar=excluded.ar_text,default_en=excluded.en_text,
  ar_text=case when coalesce(public.app_translations.ar_text,'')='' then excluded.ar_text else public.app_translations.ar_text end,
  en_text=case when coalesce(public.app_translations.en_text,'')='' then excluded.en_text else public.app_translations.en_text end,is_active=true;

select translation_key, ar_text, en_text from public.app_translations
where screen_key in ('customers','followups','quotations','salesInvoices','users')
  and (coalesce(trim(ar_text),'')='' or coalesce(trim(en_text),'')='');
