-- PETATOE P5.13.8.69R5 — SEA VIBE canonical movement-date consistency
begin;

-- Historical repair: sailing-permit wallet movements belong to the trip's business date.
update public.sea_vibe_zawel_transactions z
set transaction_date = t.trip_date
from public.sea_vibe_trips t
where z.trip_id = t.id
  and z.transaction_type in ('permit','permit_adjustment')
  and z.transaction_date is distinct from t.trip_date;

-- Canonical owner for the sailing-permit expense + Zawel wallet date.
create or replace function public.sea_vibe_sync_permit_expense() returns trigger
language plpgsql security definer set search_path=public as $$
declare
  v_catalog uuid;
  v_fee numeric(12,2);
  v_points integer;
  v_old_points integer:=0;
  v_has_wallet boolean:=false;
  v_delta integer:=0;
  v_balance bigint:=0;
begin
  select id into v_catalog
  from public.sea_vibe_expense_catalog
  where system_key='sailing_permit'
  limit 1;

  select fee_amount,coalesce(points,0) into v_fee,v_points
  from public.sea_vibe_sailing_permit_fees
  where people_count=new.people_count
    and duration_hours=new.duration_hours;

  if v_catalog is null or v_fee is null then
    raise exception 'SEA_VIBE_PERMIT_REFERENCE_MISSING';
  end if;

  insert into public.sea_vibe_expenses(
    expense_scope,trip_id,expense_catalog_id,expense_date,amount,payment_method_id,notes,
    is_system_generated,system_key,created_by,updated_by
  ) values(
    'trip',new.id,v_catalog,new.trip_date,v_fee,null,
    'Auto-calculated from sailing permit reference matrix',true,'sailing_permit',
    coalesce(new.created_by,auth.uid()),auth.uid()
  )
  on conflict(trip_id,system_key) where trip_id is not null and system_key is not null
  do update set
    expense_catalog_id=excluded.expense_catalog_id,
    expense_date=excluded.expense_date,
    amount=excluded.amount,
    updated_by=auth.uid(),
    updated_at=now();

  if tg_op='INSERT' then
    if v_points>0 then
      select coalesce(sum(points_delta),0) into v_balance
      from public.sea_vibe_zawel_transactions;

      if v_balance < v_points then
        raise exception 'SEA_VIBE_ZAWEL_INSUFFICIENT_POINTS';
      end if;

      insert into public.sea_vibe_zawel_transactions(
        transaction_type,points_delta,cash_amount,trip_id,reference,notes,transaction_date,created_by
      ) values(
        'permit',-v_points,v_fee,new.id,new.trip_serial,'رسوم تصريح الإبحار',new.trip_date,auth.uid()
      );
    end if;
  else
    -- A trip date edit moves every wallet movement generated by that trip to the same business date.
    if old.trip_date is distinct from new.trip_date then
      update public.sea_vibe_zawel_transactions
      set transaction_date=new.trip_date
      where trip_id=new.id
        and transaction_type in ('permit','permit_adjustment');
    end if;

    select exists(
      select 1
      from public.sea_vibe_zawel_transactions
      where trip_id=new.id
        and transaction_type in ('permit','permit_adjustment')
    ) into v_has_wallet;

    if v_has_wallet
       and (old.people_count is distinct from new.people_count
            or old.duration_hours is distinct from new.duration_hours) then
      select coalesce(points,0) into v_old_points
      from public.sea_vibe_sailing_permit_fees
      where people_count=old.people_count
        and duration_hours=old.duration_hours;

      v_delta:=v_old_points-v_points;

      if v_delta<>0 then
        select coalesce(sum(points_delta),0) into v_balance
        from public.sea_vibe_zawel_transactions;

        if v_delta<0 and v_balance < abs(v_delta) then
          raise exception 'SEA_VIBE_ZAWEL_INSUFFICIENT_POINTS';
        end if;

        insert into public.sea_vibe_zawel_transactions(
          transaction_type,points_delta,cash_amount,trip_id,reference,notes,transaction_date,created_by
        ) values(
          'permit_adjustment',v_delta,
          abs(round(((v_old_points-v_points)::numeric*575/2500),2)),
          new.id,new.trip_serial,'تسوية رسوم تصريح الإبحار بعد تعديل الرحلة',new.trip_date,auth.uid()
        );
      end if;
    end if;
  end if;

  return new;
end; $$;

-- Keep the existing trigger scope, but bind it to the corrected canonical function.
drop trigger if exists trg_sea_vibe_trip_permit_expense on public.sea_vibe_trips;
create trigger trg_sea_vibe_trip_permit_expense
after insert or update of trip_date,duration_hours,people_count
on public.sea_vibe_trips
for each row execute function public.sea_vibe_sync_permit_expense();

-- Preserve the existing view column order/types for dependency safety.
-- movement_at is now audit/creation timestamp only; movement_date is the business date used by UI/filtering/sorting.
create or replace view public.sea_vibe_treasury_movements with (security_invoker=true) as
select 'trip_revenue:'||t.id::text as movement_id,
       t.created_at as movement_at,
       'trip_revenue'::text as movement_type,
       t.total_value::numeric(14,2) as amount,
       t.trip_serial as reference,
       coalesce(t.notes,'') as description,
       t.id as trip_id,
       null::uuid as asset_id,
       t.treasury_movement_serial as movement_serial,
       'trip'::text as source_kind,
       t.id as source_id,
       null::uuid as expense_group_id,
       t.trip_date as movement_date
from public.sea_vibe_trips t
union all
select 'expense:'||e.id::text,
       e.created_at,
       case when e.expense_scope='asset' then 'asset_expense' else 'expense' end,
       (-e.amount)::numeric(14,2),
       coalesce(t.trip_serial,a.asset_code,''),
       coalesce(c.name_ar,'')||case when e.notes is null then '' else ' — '||e.notes end,
       e.trip_id,
       e.asset_id,
       e.movement_serial,
       'expense'::text,
       e.movement_group_id,
       e.movement_group_id,
       e.expense_date
from public.sea_vibe_expenses e
left join public.sea_vibe_trips t on t.id=e.trip_id
left join public.sea_vibe_assets a on a.id=e.asset_id
left join public.sea_vibe_expense_catalog c on c.id=e.expense_catalog_id
where coalesce(e.system_key,'')<>'sailing_permit'
union all
select 'zawel_topup:'||z.id::text,
       z.created_at,
       'zawel_topup'::text,
       (-z.cash_amount)::numeric(14,2),
       coalesce(z.reference,''),
       'شحن رصيد زاول',
       null::uuid,
       null::uuid,
       z.treasury_movement_serial,
       'zawel_topup'::text,
       z.id,
       null::uuid,
       z.transaction_date
from public.sea_vibe_zawel_transactions z
where z.transaction_type='topup';

grant select on public.sea_vibe_treasury_movements to authenticated;

commit;
