-- P5.13.8 Appointment Management Localization Rollout
insert into public.app_translations
(translation_key,screen_key,module_name,text_type,ar_text,en_text,default_ar,default_en,is_active)
values
  ('appointments.common.refreshData','appointments','appointments','button','تحديث البيانات','Refresh Data','تحديث البيانات','Refresh Data',true),
  ('appointments.common.refresh','appointments','appointments','button','تحديث','Refresh','تحديث','Refresh',true),
  ('appointments.common.search','appointments','appointments','label','بحث','Search','بحث','Search',true),
  ('appointments.common.allStatuses','appointments','appointments','option','كل الحالات','All statuses','كل الحالات','All statuses',true),
  ('appointments.common.team','appointments','appointments','label','الفرقة','Team','الفرقة','Team',true),
  ('appointments.common.allTeams','appointments','appointments','option','كل الفرق','All teams','كل الفرق','All teams',true),
  ('appointments.common.groomer','appointments','appointments','label','الجرومر','Groomer','الجرومر','Groomer',true),
  ('appointments.common.allGroomers','appointments','appointments','option','كل الجرومر','All groomers','كل الجرومر','All groomers',true),
  ('appointments.common.representative','appointments','appointments','label','المندوب','Representative','المندوب','Representative',true),
  ('appointments.common.technician','appointments','appointments','label','الفني','Technician','الفني','Technician',true),
  ('appointments.common.fromDate','appointments','appointments','label','من تاريخ','From date','من تاريخ','From date',true),
  ('appointments.common.toDate','appointments','appointments','label','إلى تاريخ','To date','إلى تاريخ','To date',true),
  ('appointments.common.reset','appointments','appointments','button','إعادة ضبط','Reset','إعادة ضبط','Reset',true),
  ('appointments.common.today','appointments','appointments','button','اليوم','Today','اليوم','Today',true),
  ('appointments.common.loading','appointments','appointments','status','جاري التحميل...','Loading...','جاري التحميل...','Loading...',true),
  ('appointments.common.previousMonth','appointments','appointments','aria','الشهر السابق','Previous month','الشهر السابق','Previous month',true),
  ('appointments.common.nextMonth','appointments','appointments','aria','الشهر التالي','Next month','الشهر التالي','Next month',true),
  ('appointments.overview.title','appointments','appointments','title','لوحة المواعيد','Appointments Dashboard','لوحة المواعيد','Appointments Dashboard',true),
  ('appointments.overview.note','appointments','appointments','help','ملخص تشغيلي مباشر للطلبات والجدولة والتنفيذ والاستثناءات.','Live operational summary of appointments, scheduling, execution, and exceptions.','ملخص تشغيلي مباشر للطلبات والجدولة والتنفيذ والاستثناءات.','Live operational summary of appointments, scheduling, execution, and exceptions.',true),
  ('appointments.overview.today','appointments','appointments','label','مواعيد اليوم','Today''s appointments','مواعيد اليوم','Today''s appointments',true),
  ('appointments.overview.todayNote','appointments','appointments','help','المواعيد المحددة لليوم','Appointments scheduled for today','المواعيد المحددة لليوم','Appointments scheduled for today',true),
  ('appointments.overview.inProgress','appointments','appointments','label','قيد التنفيذ','In progress','قيد التنفيذ','In progress',true),
  ('appointments.overview.inProgressNote','appointments','appointments','help','في الطريق أو قيد التنفيذ','On route or in progress','في الطريق أو قيد التنفيذ','On route or in progress',true),
  ('appointments.overview.overdue','appointments','appointments','label','متأخرة','Overdue','متأخرة','Overdue',true),
  ('appointments.overview.overdueNote','appointments','appointments','help','تجاوزت الموعد ولم تُغلق','Past due and not closed','تجاوزت الموعد ولم تُغلق','Past due and not closed',true),
  ('appointments.overview.completed','appointments','appointments','label','مكتملة','Completed','مكتملة','Completed',true),
  ('appointments.overview.completedNote','appointments','appointments','help','إجمالي المواعيد المكتملة','Total completed appointments','إجمالي المواعيد المكتملة','Total completed appointments',true),
  ('appointments.overview.unassigned','appointments','appointments','label','غير مسندة','Unassigned','غير مسندة','Unassigned',true),
  ('appointments.overview.unassignedNote','appointments','appointments','help','طلبات بلا فني مسؤول','Appointments without an assigned technician','طلبات بلا فني مسؤول','Appointments without an assigned technician',true),
  ('appointments.overview.exceptions','appointments','appointments','label','استثناءات مفتوحة','Open exceptions','استثناءات مفتوحة','Open exceptions',true),
  ('appointments.overview.exceptionsNote','appointments','appointments','help','مؤجلة أو متعذرة','Deferred or blocked','مؤجلة أو متعذرة','Deferred or blocked',true),
  ('appointments.overview.statusDistribution','appointments','appointments','title','توزيع الحالات','Status distribution','توزيع الحالات','Status distribution',true),
  ('appointments.overview.statusDistributionNote','appointments','appointments','help','عدد الطلبات في كل حالة تشغيلية.','Number of appointments in each operational status.','عدد الطلبات في كل حالة تشغيلية.','Number of appointments in each operational status.',true),
  ('appointments.overview.upcoming','appointments','appointments','title','أقرب المواعيد','Upcoming appointments','أقرب المواعيد','Upcoming appointments',true),
  ('appointments.overview.upcomingNote','appointments','appointments','help','الطلبات المجدولة القادمة.','Next scheduled appointments.','الطلبات المجدولة القادمة.','Next scheduled appointments.',true),
  ('appointments.requests.title','appointments','appointments','title','المواعيد','Appointments','المواعيد','Appointments',true),
  ('appointments.requests.note','appointments','appointments','help','إدارة ومراجعة جميع المواعيد وحالاتها وخدماتها.','Manage and review all appointments, statuses, and services.','إدارة ومراجعة جميع المواعيد وحالاتها وخدماتها.','Manage and review all appointments, statuses, and services.',true),
  ('appointments.requests.searchPlaceholder','appointments','appointments','placeholder','رقم الموعد، العميل أو رقم العميل','Appointment number, customer, or customer number','رقم الموعد، العميل أو رقم العميل','Appointment number, customer, or customer number',true),
  ('appointments.requests.kpiTotal','appointments','appointments','label','إجمالي الطلبات','Total appointments','إجمالي الطلبات','Total appointments',true),
  ('appointments.requests.kpiScheduled','appointments','appointments','label','مجدولة','Scheduled','مجدولة','Scheduled',true),
  ('appointments.requests.kpiInProgress','appointments','appointments','label','قيد التنفيذ','In progress','قيد التنفيذ','In progress',true),
  ('appointments.requests.kpiOverdue','appointments','appointments','label','متأخرة','Overdue','متأخرة','Overdue',true),
  ('appointments.requests.loading','appointments','appointments','status','جاري تحميل المواعيد...','Loading appointments...','جاري تحميل المواعيد...','Loading appointments...',true),
  ('appointments.schedule.title','appointments','appointments','title','جدولة وتوزيع المواعيد','Appointment Scheduling & Dispatch','جدولة وتوزيع المواعيد','Appointment Scheduling & Dispatch',true),
  ('appointments.schedule.note','appointments','appointments','help','تقويم تشغيلي لتوزيع المواعيد على فرق التشغيل ومراجعة الأحمال اليومية.','Operational calendar for dispatching appointments to teams and reviewing daily workload.','تقويم تشغيلي لتوزيع المواعيد على فرق التشغيل ومراجعة الأحمال اليومية.','Operational calendar for dispatching appointments to teams and reviewing daily workload.',true),
  ('appointments.schedule.refresh','appointments','appointments','button','تحديث الجدول','Refresh schedule','تحديث الجدول','Refresh schedule',true),
  ('appointments.schedule.displayedMonth','appointments','appointments','label','الشهر المعروض','Displayed month','الشهر المعروض','Displayed month',true),
  ('appointments.schedule.kpiMonth','appointments','appointments','label','طلبات الشهر','Monthly appointments','طلبات الشهر','Monthly appointments',true),
  ('appointments.schedule.kpiUnassigned','appointments','appointments','label','غير مسندة','Unassigned','غير مسندة','Unassigned',true),
  ('appointments.schedule.kpiAvailable','appointments','appointments','label','الجرومر المتاحون','Available groomers','الجرومر المتاحون','Available groomers',true),
  ('appointments.schedule.kpiPeak','appointments','appointments','label','أعلى حمل يومي','Peak daily load','أعلى حمل يومي','Peak daily load',true),
  ('appointments.schedule.unscheduledTitle','appointments','appointments','title','طلبات تحتاج جدولة أو إسناد','Appointments requiring scheduling or assignment','طلبات تحتاج جدولة أو إسناد','Appointments requiring scheduling or assignment',true),
  ('appointments.schedule.unscheduledNote','appointments','appointments','help','الطلبات الجديدة أو غير المرتبطة بفرقة تشغيل.','New appointments or appointments not assigned to an operating team.','الطلبات الجديدة أو غير المرتبطة بفرقة تشغيل.','New appointments or appointments not assigned to an operating team.',true),
  ('appointments.schedule.calendarAria','appointments','appointments','aria','تقويم جدولة المواعيد','Appointment scheduling calendar','تقويم جدولة المواعيد','Appointment scheduling calendar',true),
  ('appointments.completion.title','appointments','appointments','title','تأكيد انتهاء المواعيد','Appointment Completion Confirmation','تأكيد انتهاء المواعيد','Appointment Completion Confirmation',true),
  ('appointments.completion.note','appointments','appointments','help','مراجعة واعتماد انتهاء الموعد وتحويل الطلب إلى فاتورة.','Review and confirm appointment completion, then convert it to an invoice.','مراجعة واعتماد انتهاء الموعد وتحويل الطلب إلى فاتورة.','Review and confirm appointment completion, then convert it to an invoice.',true),
  ('appointments.completion.searchPlaceholder','appointments','appointments','placeholder','رقم الطلب، اسم العميل، رقم العميل أو اسم الفني','Request number, customer name, customer number, or technician','رقم الطلب، اسم العميل، رقم العميل أو اسم الفني','Request number, customer name, customer number, or technician',true),
  ('appointments.completion.transferStatus','appointments','appointments','label','حالة التحويل','Conversion status','حالة التحويل','Conversion status',true),
  ('appointments.completion.pendingInvoice','appointments','appointments','option','بانتظار التحويل إلى فاتورة','Pending invoice conversion','بانتظار التحويل إلى فاتورة','Pending invoice conversion',true),
  ('appointments.completion.allAllowedReps','appointments','appointments','option','كل المندوبين المسموحين','All allowed representatives','كل المندوبين المسموحين','All allowed representatives',true),
  ('appointments.completion.kpiCompleted','appointments','appointments','label','مواعيد مكتملة','Completed appointments','مواعيد مكتملة','Completed appointments',true),
  ('appointments.completion.kpiDocumented','appointments','appointments','label','بيانات موثقة','Documented records','بيانات موثقة','Documented records',true),
  ('appointments.completion.kpiPending','appointments','appointments','label','بانتظار التحويل','Pending conversion','بانتظار التحويل','Pending conversion',true),
  ('appointments.completion.kpiPhotos','appointments','appointments','label','صور مرفوعة','Uploaded photos','صور مرفوعة','Uploaded photos',true),
  ('appointments.completion.completedAt','appointments','appointments','label','تاريخ الإكمال','Completion date','تاريخ الإكمال','Completion date',true),
  ('appointments.weekday.sun','appointments','appointments','label','الأحد','Sunday','الأحد','Sunday',true),
  ('appointments.weekday.mon','appointments','appointments','label','الاثنين','Monday','الاثنين','Monday',true),
  ('appointments.weekday.tue','appointments','appointments','label','الثلاثاء','Tuesday','الثلاثاء','Tuesday',true),
  ('appointments.weekday.wed','appointments','appointments','label','الأربعاء','Wednesday','الأربعاء','Wednesday',true),
  ('appointments.weekday.thu','appointments','appointments','label','الخميس','Thursday','الخميس','Thursday',true),
  ('appointments.weekday.fri','appointments','appointments','label','الجمعة','Friday','الجمعة','Friday',true),
  ('appointments.weekday.sat','appointments','appointments','label','السبت','Saturday','السبت','Saturday',true),
  ('appointments.col.number','appointments','appointments','label','رقم الطلب','Request number','رقم الطلب','Request number',true),
  ('appointments.col.customer','appointments','appointments','label','العميل','Customer','العميل','Customer',true),
  ('appointments.col.customerNumber','appointments','appointments','label','رقم العميل','Customer number','رقم العميل','Customer number',true),
  ('appointments.col.contract','appointments','appointments','label','العقد','Contract','العقد','Contract',true),
  ('appointments.col.services','appointments','appointments','label','الخدمات','Services','الخدمات','Services',true),
  ('appointments.col.servicesTotal','appointments','appointments','label','إجمالي الخدمات','Services total','إجمالي الخدمات','Services total',true),
  ('appointments.col.district','appointments','appointments','label','الحي','District','الحي','District',true),
  ('appointments.col.date','appointments','appointments','label','التاريخ','Date','التاريخ','Date',true),
  ('appointments.col.period','appointments','appointments','label','الفترة','Period','الفترة','Period',true),
  ('appointments.col.status','appointments','appointments','label','الحالة','Status','الحالة','Status',true),
  ('appointments.col.team','appointments','appointments','label','الفرقة','Team','الفرقة','Team',true),
  ('appointments.col.location','appointments','appointments','label','الموقع','Location','الموقع','Location',true),
  ('appointments.col.finalTotal','appointments','appointments','label','الإجمالي النهائي','Final total','الإجمالي النهائي','Final total',true),
  ('appointments.col.action','appointments','appointments','label','الإجراء','Action','الإجراء','Action',true),
  ('appointments.col.actions','appointments','appointments','label','الإجراءات','Actions','الإجراءات','Actions',true)
on conflict (translation_key) do update set
 screen_key=excluded.screen_key,module_name=excluded.module_name,text_type=excluded.text_type,
 default_ar=excluded.default_ar,default_en=excluded.default_en,
 ar_text=case when coalesce(trim(public.app_translations.ar_text),'')='' then excluded.ar_text else public.app_translations.ar_text end,
 en_text=case when coalesce(trim(public.app_translations.en_text),'')='' then excluded.en_text else public.app_translations.en_text end,
 is_active=true;
