-- R44R37 — Generated content, exports, and notifications localization (L6)
-- Non-destructive seed for canonical public.app_translations.
-- Existing customized translations are preserved; only blank values are filled.

begin;

with translation_seed(translation_key,screen_key,module_name,text_type,ar_text,en_text,default_ar,default_en,is_active,updated_at) as (
values
  ('appointments.reports.export.appointmentExpenses','installationReports','appointments','label','مصاريف الموعد','Appointment expenses','مصاريف الموعد','Appointment expenses',true,now()),
  ('appointments.reports.export.appointments','installationReports','appointments','label','المواعيد','Appointments','المواعيد','Appointments',true,now()),
  ('appointments.reports.export.averageServiceValueVat','installationReports','appointments','label','متوسط قيمة الخدمة (شاملة الضريبة)','Average service value (VAT included)','متوسط قيمة الخدمة (شاملة الضريبة)','Average service value (VAT included)',true,now()),
  ('appointments.reports.export.collected','installationReports','appointments','label','المحصل','Collected','المحصل','Collected',true,now()),
  ('appointments.reports.export.collectedPercent','installationReports','appointments','label','النسبة من المحصل','% of collected','النسبة من المحصل','% of collected',true,now()),
  ('appointments.reports.export.count','installationReports','appointments','label','العدد','Count','العدد','Count',true,now()),
  ('appointments.reports.export.customer','installationReports','appointments','label','العميل','Customer','العميل','Customer',true,now()),
  ('appointments.reports.export.dailyOperational','installationReports','appointments','label','التقرير التشغيلي اليومي','Daily operational report','التقرير التشغيلي اليومي','Daily operational report',true,now()),
  ('appointments.reports.export.date','installationReports','appointments','label','التاريخ','Date','التاريخ','Date',true,now()),
  ('appointments.reports.export.downloadedWhatsapp','installationReports','appointments','label','تم تنزيل التقرير وفتح واتساب','Report downloaded and WhatsApp opened','تم تنزيل التقرير وفتح واتساب','Report downloaded and WhatsApp opened',true,now()),
  ('appointments.reports.export.executedQty','installationReports','appointments','label','الكمية المنفذة','Executed quantity','الكمية المنفذة','Executed quantity',true,now()),
  ('appointments.reports.export.executedServices','installationReports','appointments','label','عدد الخدمات المنفذة','Executed services','عدد الخدمات المنفذة','Executed services',true,now()),
  ('appointments.reports.export.executedValue','installationReports','appointments','label','قيمة المنفذ','Executed value','قيمة المنفذ','Executed value',true,now()),
  ('appointments.reports.export.executionDate','installationReports','appointments','label','تاريخ التنفيذ','Execution date','تاريخ التنفيذ','Execution date',true,now()),
  ('appointments.reports.export.executionRate','installationReports','appointments','label','نسبة الإنجاز','Execution rate','نسبة الإنجاز','Execution rate',true,now()),
  ('appointments.reports.export.executionStages','installationReports','appointments','label','مراحل تنفيذ الطلب','Execution stages','مراحل تنفيذ الطلب','Execution stages',true,now()),
  ('appointments.reports.export.executionStagesFor','installationReports','appointments','label','مراحل تنفيذ {team}','Execution stages — {team}','مراحل تنفيذ {team}','Execution stages — {team}',true,now()),
  ('appointments.reports.export.executionStagesNote','installationReports','appointments','note','المواعيد مرتبة حسب وقت التنفيذ الفعلي، مع قيمة الطلب ومدة التنفيذ لكل مسار.','Appointments are ordered by actual execution time, with order value and execution duration.','المواعيد مرتبة حسب وقت التنفيذ الفعلي، مع قيمة الطلب ومدة التنفيذ لكل مسار.','Appointments are ordered by actual execution time, with order value and execution duration.',true,now()),
  ('appointments.reports.export.exported','installationReports','appointments','label','تم تصدير التقرير','Report exported','تم تصدير التقرير','Report exported',true,now()),
  ('appointments.reports.export.firstTeam','installationReports','appointments','label','الفريق الأول','First team','الفريق الأول','First team',true,now()),
  ('appointments.reports.export.firstTeamStages','installationReports','appointments','label','مراحل تنفيذ الفريق الأول','First team execution stages','مراحل تنفيذ الفريق الأول','First team execution stages',true,now()),
  ('appointments.reports.export.footer','installationReports','appointments','note','تقرير ملخص المواعيد — PETATOE Enterprise CRM','Appointment Summary Report — PETATOE Enterprise CRM','تقرير ملخص المواعيد — PETATOE Enterprise CRM','Appointment Summary Report — PETATOE Enterprise CRM',true,now()),
  ('appointments.reports.export.generalSummarySubtitle','installationReports','appointments','title','الكروت الرئيسية وتفاصيل الخدمات اليومية للفرق المختارة','Main KPIs and daily service details for selected teams','الكروت الرئيسية وتفاصيل الخدمات اليومية للفرق المختارة','Main KPIs and daily service details for selected teams',true,now()),
  ('appointments.reports.export.generalSummaryTitle','installationReports','appointments','title','الملخص العام والخدمات حسب الفرق','General summary and services by team','الملخص العام والخدمات حسب الفرق','General summary and services by team',true,now()),
  ('appointments.reports.export.invoiceDate','installationReports','appointments','label','تاريخ الفاتورة','Invoice date','تاريخ الفاتورة','Invoice date',true,now()),
  ('appointments.reports.export.invoiceNumber','installationReports','appointments','label','رقم الفاتورة','Invoice number','رقم الفاتورة','Invoice number',true,now()),
  ('appointments.reports.export.invoiceSubtitle','installationReports','appointments','title','الفواتير الصادرة بتاريخ {date} للفرق والفلاتر المختارة','Invoices issued on {date} for selected teams and filters','الفواتير الصادرة بتاريخ {date} للفرق والفلاتر المختارة','Invoices issued on {date} for selected teams and filters',true,now()),
  ('appointments.reports.export.invoiceValue','installationReports','appointments','label','قيمة الفاتورة','Invoice value','قيمة الفاتورة','Invoice value',true,now()),
  ('appointments.reports.export.loadSummaryFirst','installationReports','appointments','label','حمّل ملخص المواعيد أولًا قبل التصدير.','Load the appointment summary before exporting.','حمّل ملخص المواعيد أولًا قبل التصدير.','Load the appointment summary before exporting.',true,now()),
  ('appointments.reports.export.netProfit','installationReports','appointments','label','صافي الربح','Net profit','صافي الربح','Net profit',true,now()),
  ('appointments.reports.export.noCollections','installationReports','appointments','label','لا توجد عمليات تحصيل مسجلة','No collection operations recorded','لا توجد عمليات تحصيل مسجلة','No collection operations recorded',true,now()),
  ('appointments.reports.export.noData','installationReports','appointments','label','لا توجد بيانات','No data','لا توجد بيانات','No data',true,now()),
  ('appointments.reports.export.noExecutedServices','installationReports','appointments','label','لا توجد خدمات منفذة','No executed services','لا توجد خدمات منفذة','No executed services',true,now()),
  ('appointments.reports.export.noInvoice','installationReports','appointments','label','بدون فاتورة','No invoice','بدون فاتورة','No invoice',true,now()),
  ('appointments.reports.export.noOrdersForDate','installationReports','appointments','label','لا توجد طلبات ضمن التاريخ المحدد','No orders for the selected date','لا توجد طلبات ضمن التاريخ المحدد','No orders for the selected date',true,now()),
  ('appointments.reports.export.noReschedules','installationReports','appointments','label','لا توجد حالات إعادة جدولة في التاريخ المحدد','No reschedules for the selected date','لا توجد حالات إعادة جدولة في التاريخ المحدد','No reschedules for the selected date',true,now()),
  ('appointments.reports.export.noServices','installationReports','appointments','label','لا توجد خدمات','No services','لا توجد خدمات','No services',true,now()),
  ('appointments.reports.export.noServicesForDate','installationReports','appointments','label','لا توجد خدمات ضمن التاريخ المحدد','No services for the selected date','لا توجد خدمات ضمن التاريخ المحدد','No services for the selected date',true,now()),
  ('appointments.reports.export.note','installationReports','appointments','note','ملاحظة','Note','ملاحظة','Note',true,now()),
  ('appointments.reports.export.openingShare','installationReports','appointments','label','جاري فتح المشاركة...','Opening share...','جاري فتح المشاركة...','Opening share...',true,now()),
  ('appointments.reports.export.operationCount','installationReports','appointments','label','عدد العمليات','Operations','عدد العمليات','Operations',true,now()),
  ('appointments.reports.export.orderData','installationReports','appointments','label','بيانات الطلب','Order data','بيانات الطلب','Order data',true,now()),
  ('appointments.reports.export.orderValue','installationReports','appointments','label','قيمة الطلب','Order value','قيمة الطلب','Order value',true,now()),
  ('appointments.reports.export.pageOf','installationReports','appointments','format','صفحة {page} من {total}','Page {page} of {total}','صفحة {page} من {total}','Page {page} of {total}',true,now()),
  ('appointments.reports.export.pageRenderError','installationReports','appointments','error','تعذر تجهيز إحدى صفحات التقرير.','Unable to render one of the report pages.','تعذر تجهيز إحدى صفحات التقرير.','Unable to render one of the report pages.',true,now()),
  ('appointments.reports.export.paymentMethod','installationReports','appointments','label','طريقة الدفع','Payment method','طريقة الدفع','Payment method',true,now()),
  ('appointments.reports.export.paymentNote','installationReports','appointments','note','طرق الدفع المعتمدة: تحويل، بطاقة / شبكة، نقدي، دفع عن طريق الموقع. جميع قيم المبيعات شاملة الضريبة.','Approved payment methods are bank transfer, card/network, cash, and website payment. All sales values include VAT.','طرق الدفع المعتمدة: تحويل، بطاقة / شبكة، نقدي، دفع عن طريق الموقع. جميع قيم المبيعات شاملة الضريبة.','Approved payment methods are bank transfer, card/network, cash, and website payment. All sales values include VAT.',true,now()),
  ('appointments.reports.export.paymentSummarySubtitle','installationReports','appointments','title','اليوم ومن بداية الشهر حتى {date}','Today and month-to-date through {date}','اليوم ومن بداية الشهر حتى {date}','Today and month-to-date through {date}',true,now()),
  ('appointments.reports.export.paymentSummaryTitle','installationReports','appointments','title','ملخص طرق الدفع حسب الفريق','Payment method summary by team','ملخص طرق الدفع حسب الفريق','Payment method summary by team',true,now()),
  ('appointments.reports.export.pdfDownloadedAttach','installationReports','appointments','label','تم تنزيل ملف PDF على الجهاز. أرفق الملف الذي تم تنزيله داخل محادثة واتساب.','The PDF was downloaded to the device. Attach it in the WhatsApp conversation.','تم تنزيل ملف PDF على الجهاز. أرفق الملف الذي تم تنزيله داخل محادثة واتساب.','The PDF was downloaded to the device. Attach it in the WhatsApp conversation.',true,now()),
  ('appointments.reports.export.pdfError','installationReports','appointments','error','تعذر تجهيز ملف PDF.','Unable to prepare the PDF.','تعذر تجهيز ملف PDF.','Unable to prepare the PDF.',true,now()),
  ('appointments.reports.export.pdfToolsMissing','installationReports','appointments','error','تعذر تحميل أدوات إنشاء ملف PDF.','Unable to load PDF generation tools.','تعذر تحميل أدوات إنشاء ملف PDF.','Unable to load PDF generation tools.',true,now()),
  ('appointments.reports.export.performedBy','installationReports','appointments','label','تم بواسطة','Performed by','تم بواسطة','Performed by',true,now()),
  ('appointments.reports.export.preparingPdf','installationReports','appointments','label','جاري تجهيز PDF...','Preparing PDF...','جاري تجهيز PDF...','Preparing PDF...',true,now()),
  ('appointments.reports.export.preparingWhatsapp','installationReports','appointments','label','جاري تجهيز تقرير ملخص المواعيد لواتساب...','Preparing appointment summary report for WhatsApp...','جاري تجهيز تقرير ملخص المواعيد لواتساب...','Preparing appointment summary report for WhatsApp...',true,now()),
  ('appointments.reports.export.previousTeam','installationReports','appointments','label','الفريق السابق','Previous team','الفريق السابق','Previous team',true,now()),
  ('appointments.reports.export.previousTime','installationReports','appointments','label','الوقت السابق','Previous time','الوقت السابق','Previous time',true,now()),
  ('appointments.reports.export.reason','installationReports','appointments','label','السبب','Reason','السبب','Reason',true,now()),
  ('appointments.reports.export.remaining','installationReports','appointments','label','المتبقي','Remaining','المتبقي','Remaining',true,now()),
  ('appointments.reports.export.remainingQty','installationReports','appointments','label','الكمية المتبقية','Remaining quantity','الكمية المتبقية','Remaining quantity',true,now()),
  ('appointments.reports.export.remainingValue','installationReports','appointments','label','قيمة المتبقي','Remaining value','قيمة المتبقي','Remaining value',true,now()),
  ('appointments.reports.export.reportReady','installationReports','appointments','label','تم تجهيز التقرير','Report ready','تم تجهيز التقرير','Report ready',true,now()),
  ('appointments.reports.export.representative','installationReports','appointments','label','المندوب','Representative','المندوب','Representative',true,now()),
  ('appointments.reports.export.requestNumber','installationReports','appointments','label','رقم الطلب','Request number','رقم الطلب','Request number',true,now()),
  ('appointments.reports.export.requestedQty','installationReports','appointments','label','الكمية المطلوبة','Requested quantity','الكمية المطلوبة','Requested quantity',true,now()),
  ('appointments.reports.export.revisit','installationReports','appointments','label','إعادة الزيارة','Revisit','إعادة الزيارة','Revisit',true,now()),
  ('appointments.reports.export.secondTeam','installationReports','appointments','label','الفريق الثاني','Second team','الفريق الثاني','Second team',true,now()),
  ('appointments.reports.export.secondTeamStages','installationReports','appointments','label','مراحل تنفيذ الفريق الثاني','Second team execution stages','مراحل تنفيذ الفريق الثاني','Second team execution stages',true,now()),
  ('appointments.reports.export.selectedTeams','installationReports','appointments','label','الفرق المختارة','Selected teams','الفرق المختارة','Selected teams',true,now()),
  ('appointments.reports.export.sentToShare','installationReports','appointments','label','تم إرسال التقرير للمشاركة','Report sent to share','تم إرسال التقرير للمشاركة','Report sent to share',true,now()),
  ('appointments.reports.export.service','installationReports','appointments','label','الخدمة','Service','الخدمة','Service',true,now()),
  ('appointments.reports.export.serviceAverageVat','installationReports','appointments','label','متوسط قيمة الخدمة (شاملة الضريبة)','Average service value (VAT included)','متوسط قيمة الخدمة (شاملة الضريبة)','Average service value (VAT included)',true,now()),
  ('appointments.reports.export.serviceRevenueVat','installationReports','appointments','label','إيراد الخدمة شامل الضريبة','Service revenue incl. VAT','إيراد الخدمة شامل الضريبة','Service revenue incl. VAT',true,now()),
  ('appointments.reports.export.serviceTotalVat','installationReports','appointments','label','إجمالي قيمة الخدمة (شاملة الضريبة)','Total service value (VAT included)','إجمالي قيمة الخدمة (شاملة الضريبة)','Total service value (VAT included)',true,now()),
  ('appointments.reports.export.services','installationReports','appointments','label','الخدمات','Services','الخدمات','Services',true,now()),
  ('appointments.reports.export.servicesValueDuration','installationReports','appointments','label','الخدمات وقيمة الطلب ومدة التنفيذ','Services, order value, and duration','الخدمات وقيمة الطلب ومدة التنفيذ','Services, order value, and duration',true,now()),
  ('appointments.reports.export.shareOpenError','installationReports','appointments','error','تعذر فتح مشاركة التقرير.','Unable to open report sharing.','تعذر فتح مشاركة التقرير.','Unable to open report sharing.',true,now()),
  ('appointments.reports.export.shareReadyAgain','installationReports','appointments','label','تم تجهيز ملف PDF. اضغط «إرسال التقرير واتساب PDF» مرة أخرى لفتح مشاركة الملفات واختيار واتساب.','PDF is ready. Press “Share report via WhatsApp PDF” again to open file sharing and choose WhatsApp.','تم تجهيز ملف PDF. اضغط «إرسال التقرير واتساب PDF» مرة أخرى لفتح مشاركة الملفات واختيار واتساب.','PDF is ready. Press “Share report via WhatsApp PDF” again to open file sharing and choose WhatsApp.',true,now()),
  ('appointments.reports.export.stage','installationReports','appointments','label','المرحلة','Stage','المرحلة','Stage',true,now()),
  ('appointments.reports.export.status','installationReports','appointments','label','الحالة','Status','الحالة','Status',true,now()),
  ('appointments.reports.export.summaryTitle','installationReports','appointments','title','ملخص المواعيد','Appointment Summary','ملخص المواعيد','Appointment Summary',true,now()),
  ('appointments.reports.export.team','installationReports','appointments','label','الفريق','Team','الفريق','Team',true,now()),
  ('appointments.reports.export.teamNumber','installationReports','appointments','label','الفريق {number}','Team {number}','الفريق {number}','Team {number}',true,now()),
  ('appointments.reports.export.technician','installationReports','appointments','label','الفني','Technician','الفني','Technician',true,now()),
  ('appointments.reports.export.todaySalesInvoices','installationReports','appointments','label','فواتير مبيعات اليوم','Today sales invoices','فواتير مبيعات اليوم','Today sales invoices',true,now()),
  ('appointments.reports.export.totalAmount','installationReports','appointments','label','إجمالي المبلغ','Total amount','إجمالي المبلغ','Total amount',true,now()),
  ('appointments.reports.export.totalServices','installationReports','appointments','label','إجمالي الخدمات','Total services','إجمالي الخدمات','Total services',true,now()),
  ('appointments.reports.export.totalServicesValueVat','installationReports','appointments','label','إجمالي قيمة الخدمات (شاملة الضريبة)','Total service value (VAT included)','إجمالي قيمة الخدمات (شاملة الضريبة)','Total service value (VAT included)',true,now()),
  ('appointments.reports.export.totalVisits','installationReports','appointments','label','إجمالي الزيارات','Total visits','إجمالي الزيارات','Total visits',true,now()),
  ('appointments.reports.export.unspecifiedTeam','installationReports','appointments','label','فريق غير محدد','Unspecified team','فريق غير محدد','Unspecified team',true,now()),
  ('appointments.reports.export.valueVat','installationReports','appointments','label','القيمة شامل الضريبة','Value incl. VAT','القيمة شامل الضريبة','Value incl. VAT',true,now()),
  ('appointments.reports.export.vatNote','installationReports','appointments','note','جميع القيم المالية المعروضة شاملة ضريبة القيمة المضافة، وتُعرض داخل التقرير وفق القيم المعتمدة في ملخص المواعيد.','All displayed financial values include VAT and follow the approved appointment summary values.','جميع القيم المالية المعروضة شاملة ضريبة القيمة المضافة، وتُعرض داخل التقرير وفق القيم المعتمدة في ملخص المواعيد.','All displayed financial values include VAT and follow the approved appointment summary values.',true,now()),
  ('appointments.reports.export.whatsappBlocked','installationReports','appointments','error','تم تنزيل ملف PDF، لكن المتصفح منع فتح واتساب. اسمح بالنوافذ المنبثقة لهذا الموقع ثم أعد المحاولة.','The PDF was downloaded, but the browser blocked WhatsApp. Allow pop-ups for this site and try again.','تم تنزيل ملف PDF، لكن المتصفح منع فتح واتساب. اسمح بالنوافذ المنبثقة لهذا الموقع ثم أعد المحاولة.','The PDF was downloaded, but the browser blocked WhatsApp. Allow pop-ups for this site and try again.',true,now()),
  ('appointments.reports.export.whatsappMessage','installationReports','appointments','format','ملخص المواعيد بتاريخ {date}','Appointment summary dated {date}','ملخص المواعيد بتاريخ {date}','Appointment summary dated {date}',true,now()),
  ('appointments.reports.summary.stage.mapOpened','installationReports','appointments','label','فتح موقع العميل','Customer location opened','فتح موقع العميل','Customer location opened',true,now()),
  ('appointments.reports.summary.stage.onRoute','installationReports','appointments','label','بدء التحرك','On route','بدء التحرك','On route',true,now()),
  ('appointments.reports.summary.stage.started','installationReports','appointments','label','بدء الموعد','Appointment started','بدء الموعد','Appointment started',true,now()),
  ('contracts.export.call','quotations','crm','button','اتصال','Call','اتصال','Call',true,now()),
  ('contracts.export.copied','quotations','crm','label','تم نسخ بيانات العقد.','Contract details copied.','تم نسخ بيانات العقد.','Contract details copied.',true,now()),
  ('contracts.export.copyPrompt','quotations','crm','label','انسخ بيانات العقد:','Copy contract details:','انسخ بيانات العقد:','Copy contract details:',true,now()),
  ('contracts.export.customerOrderNumber','quotations','crm','label','رقم طلب العميل','Customer Order Number','رقم طلب العميل','Customer Order Number',true,now()),
  ('contracts.export.date','quotations','crm','label','تاريخ العقد','Contract Date','تاريخ العقد','Contract Date',true,now()),
  ('contracts.export.expiryDate','quotations','crm','label','تاريخ الانتهاء','Expiry Date','تاريخ الانتهاء','Expiry Date',true,now()),
  ('contracts.export.filterNote','quotations','crm','note','البحث والحالة والمندوب','Search, status, and representative','البحث والحالة والمندوب','Search, status, and representative',true,now()),
  ('contracts.export.filterTitle','quotations','crm','title','فلترة عقود العملاء','Filter Customer Contracts','فلترة عقود العملاء','Filter Customer Contracts',true,now()),
  ('contracts.export.mobileNote','quotations','crm','note','ابحث وراجع وشارك العقود بسهولة','Search, review, and share contracts easily','ابحث وراجع وشارك العقود بسهولة','Search, review, and share contracts easily',true,now()),
  ('contracts.export.mobileTitle','quotations','crm','title','عقود العملاء','Customer Contracts','عقود العملاء','Customer Contracts',true,now()),
  ('contracts.export.number','quotations','crm','label','رقم العقد','Contract Number','رقم العقد','Contract Number',true,now()),
  ('contracts.export.print','quotations','crm','button','PDF / طباعة','PDF / Print','PDF / طباعة','PDF / Print',true,now()),
  ('contracts.export.printTitle','quotations','crm','title','عقد {code}','Contract {code}','عقد {code}','Contract {code}',true,now()),
  ('contracts.export.rejectionReason','quotations','crm','label','سبب الرفض','Rejection Reason','سبب الرفض','Rejection Reason',true,now()),
  ('contracts.export.share','quotations','crm','button','مشاركة','Share','مشاركة','Share',true,now()),
  ('contracts.export.shareText','quotations','crm','format','عقد {code}
العميل: {customer}
المندوب: {representative}
التاريخ: {date}
القيمة: {amount}
الحالة: {status}
تاريخ الانتهاء: {expiry}','Contract {code}
Customer: {customer}
Representative: {representative}
Date: {date}
Value: {amount}
Status: {status}
Expiry Date: {expiry}','عقد {code}
العميل: {customer}
المندوب: {representative}
التاريخ: {date}
القيمة: {amount}
الحالة: {status}
تاريخ الانتهاء: {expiry}','Contract {code}
Customer: {customer}
Representative: {representative}
Date: {date}
Value: {amount}
Status: {status}
Expiry Date: {expiry}',true,now()),
  ('contracts.export.shareTitle','quotations','crm','title','عقد {code}','Contract {code}','عقد {code}','Contract {code}',true,now()),
  ('contracts.export.subtitle','quotations','crm','title','التقرير يعكس الفلاتر المحددة في شاشة عقود العملاء','The report reflects the selected filters on the Customer Contracts screen','التقرير يعكس الفلاتر المحددة في شاشة عقود العملاء','The report reflects the selected filters on the Customer Contracts screen',true,now()),
  ('contracts.export.title','quotations','crm','title','تقرير عقود العملاء','Customer Contracts Report','تقرير عقود العملاء','Customer Contracts Report',true,now()),
  ('contracts.export.whatsapp','quotations','crm','button','WhatsApp','WhatsApp','WhatsApp','WhatsApp',true,now()),
  ('contracts.export.workflowStatus','quotations','crm','label','حالة التحويل','Workflow Status','حالة التحويل','Workflow Status',true,now()),
  ('customer360.export.acceptedContracts','customers','crm','label','العروض المقبولة','Accepted Contracts','العروض المقبولة','Accepted Contracts',true,now()),
  ('customer360.export.acceptedValue','customers','crm','label','القيمة المقبولة','Accepted Value','القيمة المقبولة','Accepted Value',true,now()),
  ('customer360.export.action','customers','crm','label','الإجراء','Action','الإجراء','Action',true,now()),
  ('customer360.export.address','customers','crm','label','العنوان','Address','العنوان','Address',true,now()),
  ('customer360.export.amount','customers','crm','label','القيمة','Amount','القيمة','Amount',true,now()),
  ('customer360.export.basicData','customers','crm','label','البيانات الأساسية','Basic Information','البيانات الأساسية','Basic Information',true,now()),
  ('customer360.export.code','customers','crm','label','الكود','Code','الكود','Code',true,now()),
  ('customer360.export.completed','customers','crm','label','مكتمل','Completed','مكتمل','Completed',true,now()),
  ('customer360.export.contracts','customers','crm','label','العروض','Contracts','العروض','Contracts',true,now()),
  ('customer360.export.conversionRate','customers','crm','label','نسبة التحويل','Conversion Rate','نسبة التحويل','Conversion Rate',true,now()),
  ('customer360.export.creatingPng','customers','crm','label','جاري إنشاء الصورة...','Creating image...','جاري إنشاء الصورة...','Creating image...',true,now()),
  ('customer360.export.date','customers','crm','label','التاريخ','Date','التاريخ','Date',true,now()),
  ('customer360.export.details','customers','crm','label','التفاصيل','Details','التفاصيل','Details',true,now()),
  ('customer360.export.engagementScore','customers','crm','label','درجة التفاعل','Engagement Score','درجة التفاعل','Engagement Score',true,now()),
  ('customer360.export.error','customers','crm','error','تعذر تصدير بيانات العميل.','Unable to export customer data.','تعذر تصدير بيانات العميل.','Unable to export customer data.',true,now()),
  ('customer360.export.excelMissing','customers','crm','error','مكتبة Excel غير محملة.','Excel library is not loaded.','مكتبة Excel غير محملة.','Excel library is not loaded.',true,now()),
  ('customer360.export.exportPng','customers','crm','button','تصدير PNG','Export PNG','تصدير PNG','Export PNG',true,now()),
  ('customer360.export.followups','customers','crm','label','المتابعات','Follow-ups','المتابعات','Follow-ups',true,now()),
  ('customer360.export.footer','customers','crm','note','تم الإنشاء بواسطة PETATOE — مركز تصدير العميل 360','Generated by PETATOE — Customer 360 Export Center','تم الإنشاء بواسطة PETATOE — مركز تصدير العميل 360','Generated by PETATOE — Customer 360 Export Center',true,now()),
  ('customer360.export.generatedAt','customers','crm','label','تاريخ الإنشاء','Generated At','تاريخ الإنشاء','Generated At',true,now()),
  ('customer360.export.healthScore','customers','crm','label','صحة العميل','Health Score','صحة العميل','Health Score',true,now()),
  ('customer360.export.inactivityDays','customers','crm','label','أيام عدم النشاط','Inactivity Days','أيام عدم النشاط','Inactivity Days',true,now()),
  ('customer360.export.lastContact','customers','crm','label','آخر تواصل','Last Contact','آخر تواصل','Last Contact',true,now()),
  ('customer360.export.meta','customers','crm','label','بيانات إضافية','Meta','بيانات إضافية','Meta',true,now()),
  ('customer360.export.method','customers','crm','label','الطريقة','Method','الطريقة','Method',true,now()),
  ('customer360.export.mobile','customers','crm','label','الجوال','Mobile','الجوال','Mobile',true,now()),
  ('customer360.export.name','customers','crm','label','الاسم','Name','الاسم','Name',true,now()),
  ('customer360.export.nextFollowup','customers','crm','label','المتابعة القادمة','Next Follow-up','المتابعة القادمة','Next Follow-up',true,now()),
  ('customer360.export.no','customers','crm','label','لا','No','لا','No',true,now()),
  ('customer360.export.noFollowups','customers','crm','label','لا توجد متابعات.','No follow-ups.','لا توجد متابعات.','No follow-ups.',true,now()),
  ('customer360.export.noMobile','customers','crm','label','بدون جوال','No mobile number','بدون جوال','No mobile number',true,now()),
  ('customer360.export.noQuotations','customers','crm','label','لا توجد عروض أسعار.','No quotations.','لا توجد عروض أسعار.','No quotations.',true,now()),
  ('customer360.export.notes','customers','crm','note','الملاحظات','Notes','الملاحظات','Notes',true,now()),
  ('customer360.export.number','customers','crm','label','الرقم','Number','الرقم','Number',true,now()),
  ('customer360.export.overdueFollowups','customers','crm','label','المتابعات المتأخرة','Overdue Follow-ups','المتابعات المتأخرة','Overdue Follow-ups',true,now()),
  ('customer360.export.pngMissing','customers','crm','error','مكتبة PNG غير محملة.','PNG library is not loaded.','مكتبة PNG غير محملة.','PNG library is not loaded.',true,now()),
  ('customer360.export.popupRequired','customers','crm','label','اسمح بالنوافذ المنبثقة لإنشاء التقرير.','Allow pop-ups to create the report.','اسمح بالنوافذ المنبثقة لإنشاء التقرير.','Allow pop-ups to create the report.',true,now()),
  ('customer360.export.potentialValue','customers','crm','label','القيمة المحتملة','Potential Value','القيمة المحتملة','Potential Value',true,now()),
  ('customer360.export.priority','customers','crm','label','الأولوية','Priority','الأولوية','Priority',true,now()),
  ('customer360.export.quotation','customers','crm','label','العرض','Quotation','العرض','Quotation',true,now()),
  ('customer360.export.quotations','customers','crm','label','عروض الأسعار','Quotations','عروض الأسعار','Quotations',true,now()),
  ('customer360.export.rejectionReason','customers','crm','label','سبب الرفض / عدم البيع','Rejection / No Sale Reason','سبب الرفض / عدم البيع','Rejection / No Sale Reason',true,now()),
  ('customer360.export.reportTitle','customers','crm','title','تقرير العميل 360°','Customer 360° Report','تقرير العميل 360°','Customer 360° Report',true,now()),
  ('customer360.export.representative','customers','crm','label','المندوب','Representative','المندوب','Representative',true,now()),
  ('customer360.export.responseRate','customers','crm','label','معدل الاستجابة','Response Rate','معدل الاستجابة','Response Rate',true,now()),
  ('customer360.export.result','customers','crm','label','النتيجة','Result','النتيجة','Result',true,now()),
  ('customer360.export.riskNextAction','customers','crm','label','المخاطر والإجراء التالي','Risk & Next Action','المخاطر والإجراء التالي','Risk & Next Action',true,now()),
  ('customer360.export.riskScore','customers','crm','label','درجة الخطر','Risk Score','درجة الخطر','Risk Score',true,now()),
  ('customer360.export.sheetFollowups','customers','crm','label','المتابعات','Follow-ups','المتابعات','Follow-ups',true,now()),
  ('customer360.export.sheetQuotations','customers','crm','label','عروض الأسعار','Quotations','عروض الأسعار','Quotations',true,now()),
  ('customer360.export.sheetSummary','customers','crm','label','ملخص العميل','Customer Summary','ملخص العميل','Customer Summary',true,now()),
  ('customer360.export.sheetTimeline','customers','crm','label','سجل النشاط','Activity Timeline','سجل النشاط','Activity Timeline',true,now()),
  ('customer360.export.status','customers','crm','label','الحالة','Status','الحالة','Status',true,now()),
  ('customer360.export.title','customers','crm','title','العنوان','Title','العنوان','Title',true,now()),
  ('customer360.export.totalContractValue','customers','crm','label','إجمالي قيمة العروض','Total Contract Value','إجمالي قيمة العروض','Total Contract Value',true,now()),
  ('customer360.export.type','customers','crm','label','النوع','Type','النوع','Type',true,now()),
  ('customer360.export.upcomingFollowups','customers','crm','label','المتابعات القادمة','Upcoming Follow-ups','المتابعات القادمة','Upcoming Follow-ups',true,now()),
  ('customer360.export.yes','customers','crm','label','نعم','Yes','نعم','Yes',true,now()),
  ('customerImport.template.allowedColumns','customers','crm','label','الأعمدة المعتمدة فقط: code | name | address | mobile','Approved columns only: code | name | address | mobile','الأعمدة المعتمدة فقط: code | name | address | mobile','Approved columns only: code | name | address | mobile',true,now()),
  ('customerImport.template.instructionsTitle','customers','crm','title','تعليمات نموذج العملاء','Customer Template Instructions','تعليمات نموذج العملاء','Customer Template Instructions',true,now()),
  ('customerImport.template.keepHeaders','customers','crm','label','لا تغيّر أسماء الأعمدة.','Do not change column names.','لا تغيّر أسماء الأعمدة.','Do not change column names.',true,now()),
  ('customerImport.template.requiredColumns','customers','crm','label','code و name و mobile مطلوبة، و address اختياري.','code, name, and mobile are required; address is optional.','code و name و mobile مطلوبة، و address اختياري.','code, name, and mobile are required; address is optional.',true,now()),
  ('customerImport.template.sampleAddress','customers','crm','label','جدة - حي ...','Jeddah - District ...','جدة - حي ...','Jeddah - District ...',true,now()),
  ('customerImport.template.sampleName','customers','crm','label','اسم العميل','Customer Name','اسم العميل','Customer Name',true,now()),
  ('customerImport.template.sheetCustomers','customers','crm','label','Customers','Customers','Customers','Customers',true,now()),
  ('customerImport.template.sheetFailed','customers','crm','label','Failed Rows','Failed Rows','Failed Rows','Failed Rows',true,now()),
  ('customerImport.template.sheetInstructions','customers','crm','label','Instructions','Instructions','Instructions','Instructions',true,now()),
  ('dailyPerformance.export.activity.allTypes','dailyPerformanceReport','crm','label','كل الأنشطة','All Activities','كل الأنشطة','All Activities',true,now()),
  ('dailyPerformance.export.activity.count','dailyPerformanceReport','crm','label','عدد الحركات','Activity Count','عدد الحركات','Activity Count',true,now()),
  ('dailyPerformance.export.activity.empty','dailyPerformanceReport','crm','label','لا توجد حركات مطابقة للفلاتر.','No activity matches the selected filters.','لا توجد حركات مطابقة للفلاتر.','No activity matches the selected filters.',true,now()),
  ('dailyPerformance.export.activity.exportError','dailyPerformanceReport','crm','error','تعذر تصدير خط السير.','Unable to export the activity route.','تعذر تصدير خط السير.','Unable to export the activity route.',true,now()),
  ('dailyPerformance.export.activity.exportPdf','dailyPerformanceReport','crm','button','تصدير خط السير PDF','Export Activity Route PDF','تصدير خط السير PDF','Export Activity Route PDF',true,now()),
  ('dailyPerformance.export.activity.fallback','dailyPerformanceReport','crm','label','نشاط','Activity','نشاط','Activity',true,now()),
  ('dailyPerformance.export.activity.loadFirst','dailyPerformanceReport','crm','label','حمّل تقرير الأداء اليومي أولًا.','Load the daily performance report first.','حمّل تقرير الأداء اليومي أولًا.','Load the daily performance report first.',true,now()),
  ('dailyPerformance.export.activity.performedBy','dailyPerformanceReport','crm','label','نفذ بواسطة','Performed by','نفذ بواسطة','Performed by',true,now()),
  ('dailyPerformance.export.activity.selectEmployeeFirst','dailyPerformanceReport','crm','label','اختر الموظف واعرض بيانات خط السير أولًا.','Select an employee and display the activity route first.','اختر الموظف واعرض بيانات خط السير أولًا.','Select an employee and display the activity route first.',true,now()),
  ('dailyPerformance.export.activity.shareError','dailyPerformanceReport','crm','error','تعذر مشاركة خط السير.','Unable to share the activity route.','تعذر مشاركة خط السير.','Unable to share the activity route.',true,now()),
  ('dailyPerformance.export.activity.shareTitle','dailyPerformanceReport','crm','title','خط سير {name} - {date}','Activity Route {name} - {date}','خط سير {name} - {date}','Activity Route {name} - {date}',true,now()),
  ('dailyPerformance.export.activity.shareWhatsapp','dailyPerformanceReport','crm','button','إرسال خط السير واتساب PDF','Share Activity Route via WhatsApp PDF','إرسال خط السير واتساب PDF','Share Activity Route via WhatsApp PDF',true,now()),
  ('dailyPerformance.export.activity.subtitle','dailyPerformanceReport','crm','title','سجل تفصيلي للحركات والمهام داخل البرنامج بالدقيقة','Detailed minute-by-minute log of movements and tasks in the app','سجل تفصيلي للحركات والمهام داخل البرنامج بالدقيقة','Detailed minute-by-minute log of movements and tasks in the app',true,now()),
  ('dailyPerformance.export.activity.title','dailyPerformanceReport','crm','title','خط سير يوم الموظف','Employee Daily Activity Route','خط سير يوم الموظف','Employee Daily Activity Route',true,now()),
  ('dailyPerformance.export.activity.type','dailyPerformanceReport','crm','label','نوع النشاط','Activity Type','نوع النشاط','Activity Type',true,now()),
  ('dailyPerformance.export.activity.whatsappMessage','dailyPerformanceReport','crm','format','خط سير يوم الموظف
الموظف: {name}
التاريخ: {date}
مرفق التقرير بصيغة PDF وفق الفلاتر المحددة.','Employee daily activity route
Employee: {name}
Date: {date}
The PDF report is attached using the selected filters.','خط سير يوم الموظف
الموظف: {name}
التاريخ: {date}
مرفق التقرير بصيغة PDF وفق الفلاتر المحددة.','Employee daily activity route
Employee: {name}
Date: {date}
The PDF report is attached using the selected filters.',true,now()),
  ('dailyPerformance.export.checklist','dailyPerformanceReport','crm','label','إنجاز المهام %','Checklist %','إنجاز المهام %','Checklist %',true,now()),
  ('dailyPerformance.export.code','dailyPerformanceReport','crm','label','الكود','Code','الكود','Code',true,now()),
  ('dailyPerformance.export.completed','dailyPerformanceReport','crm','label','مكتمل','Completed','مكتمل','Completed',true,now()),
  ('dailyPerformance.export.completion','dailyPerformanceReport','crm','label','الإنجاز %','Completion %','الإنجاز %','Completion %',true,now()),
  ('dailyPerformance.export.contentUnavailable','dailyPerformanceReport','crm','error','تعذر الوصول إلى محتوى تقرير الأداء اليومي.','Unable to access daily performance report content.','تعذر الوصول إلى محتوى تقرير الأداء اليومي.','Unable to access daily performance report content.',true,now()),
  ('dailyPerformance.export.csv.title','dailyPerformanceReport','crm','title','تقرير الأداء اليومي الموسع','Expanded Daily Performance Report','تقرير الأداء اليومي الموسع','Expanded Daily Performance Report',true,now()),
  ('dailyPerformance.export.customerTarget','dailyPerformanceReport','crm','label','هدف العملاء %','Customer Target %','هدف العملاء %','Customer Target %',true,now()),
  ('dailyPerformance.export.employee','dailyPerformanceReport','crm','label','الموظف','Employee','الموظف','Employee',true,now()),
  ('dailyPerformance.export.employeeRepresentative','dailyPerformanceReport','crm','label','الموظف / المندوب','Employee / Representative','الموظف / المندوب','Employee / Representative',true,now()),
  ('dailyPerformance.export.exportedAt','dailyPerformanceReport','crm','label','وقت التصدير','Exported At','وقت التصدير','Exported At',true,now()),
  ('dailyPerformance.export.followupTarget','dailyPerformanceReport','crm','label','هدف المتابعة %','Follow-up Target %','هدف المتابعة %','Follow-up Target %',true,now()),
  ('dailyPerformance.export.followups','dailyPerformanceReport','crm','label','المتابعات','Follow-ups','المتابعات','Follow-ups',true,now()),
  ('dailyPerformance.export.footer','dailyPerformanceReport','crm','note','PETATOE — تقرير الأداء اليومي المؤسسي','PETATOE — Enterprise Daily Performance Report','PETATOE — تقرير الأداء اليومي المؤسسي','PETATOE — Enterprise Daily Performance Report',true,now()),
  ('dailyPerformance.export.generatedAt','dailyPerformanceReport','crm','label','تاريخ الإنشاء','Generated At','تاريخ الإنشاء','Generated At',true,now()),
  ('dailyPerformance.export.loadFirst','dailyPerformanceReport','crm','label','حمّل تقرير الأداء اليومي أولًا قبل تصدير PDF.','Load the daily performance report before exporting PDF.','حمّل تقرير الأداء اليومي أولًا قبل تصدير PDF.','Load the daily performance report before exporting PDF.',true,now()),
  ('dailyPerformance.export.loadFirstPrepare','dailyPerformanceReport','crm','label','حمّل تقرير الأداء اليومي أولًا قبل تجهيز PDF.','Load the daily performance report before preparing PDF.','حمّل تقرير الأداء اليومي أولًا قبل تجهيز PDF.','Load the daily performance report before preparing PDF.',true,now()),
  ('dailyPerformance.export.managerNote','dailyPerformanceReport','crm','note','ملاحظة المدير','Manager Note','ملاحظة المدير','Manager Note',true,now()),
  ('dailyPerformance.export.newCustomers','dailyPerformanceReport','crm','label','عملاء جدد','New Customers','عملاء جدد','New Customers',true,now()),
  ('dailyPerformance.export.notCompleted','dailyPerformanceReport','crm','label','غير مكتمل','Not Completed','غير مكتمل','Not Completed',true,now()),
  ('dailyPerformance.export.overdue','dailyPerformanceReport','crm','label','المتأخر','Overdue','المتأخر','Overdue',true,now()),
  ('dailyPerformance.export.pdfSubtitle','dailyPerformanceReport','crm','title','متابعة تنفيذ المهام والنشاط اليومي للموظفين','Track employee task execution and daily activity','متابعة تنفيذ المهام والنشاط اليومي للموظفين','Track employee task execution and daily activity',true,now()),
  ('dailyPerformance.export.pdfTitle','dailyPerformanceReport','crm','title','تقرير الأداء اليومي','Daily Performance Report','تقرير الأداء اليومي','Daily Performance Report',true,now()),
  ('dailyPerformance.export.points','dailyPerformanceReport','crm','label','النقاط','Points','النقاط','Points',true,now()),
  ('dailyPerformance.export.popupRequired','dailyPerformanceReport','crm','label','اسمح بالنوافذ المنبثقة لتصدير تقرير PDF.','Allow pop-ups to export the PDF report.','اسمح بالنوافذ المنبثقة لتصدير تقرير PDF.','Allow pop-ups to export the PDF report.',true,now()),
  ('dailyPerformance.export.printCopy','dailyPerformanceReport','crm','label','نسخة مخصصة للطباعة والحفظ بصيغة PDF','Print-ready copy for saving as PDF','نسخة مخصصة للطباعة والحفظ بصيغة PDF','Print-ready copy for saving as PDF',true,now()),
  ('dailyPerformance.export.quotationTarget','dailyPerformanceReport','crm','label','هدف العروض %','Quotation Target %','هدف العروض %','Quotation Target %',true,now()),
  ('dailyPerformance.export.quotations','dailyPerformanceReport','crm','label','العروض','Quotations','العروض','Quotations',true,now()),
  ('dailyPerformance.export.rank','dailyPerformanceReport','crm','label','الترتيب','Rank','الترتيب','Rank',true,now()),
  ('dailyPerformance.export.reportDate','dailyPerformanceReport','crm','label','تاريخ التقرير','Report Date','تاريخ التقرير','Report Date',true,now()),
  ('dailyPerformance.export.shareError','dailyPerformanceReport','crm','error','تعذر تجهيز تقرير PDF للمشاركة.','Unable to prepare the PDF report for sharing.','تعذر تجهيز تقرير PDF للمشاركة.','Unable to prepare the PDF report for sharing.',true,now()),
  ('dailyPerformance.export.shareTitle','dailyPerformanceReport','crm','title','تقرير الأداء اليومي - {date}','Daily Performance Report - {date}','تقرير الأداء اليومي - {date}','Daily Performance Report - {date}',true,now()),
  ('dailyPerformance.export.shareWhatsapp','dailyPerformanceReport','crm','button','إرسال التقرير واتساب PDF','Share report via WhatsApp PDF','إرسال التقرير واتساب PDF','Share report via WhatsApp PDF',true,now()),
  ('dailyPerformance.export.whatsappDownloaded','dailyPerformanceReport','crm','label','تم تنزيل ملف PDF وفتح واتساب. أرفق الملف الذي تم تنزيله بالمحادثة.','PDF downloaded and WhatsApp opened. Attach the downloaded file to the conversation.','تم تنزيل ملف PDF وفتح واتساب. أرفق الملف الذي تم تنزيله بالمحادثة.','PDF downloaded and WhatsApp opened. Attach the downloaded file to the conversation.',true,now()),
  ('dailyPerformance.export.whatsappMessage','dailyPerformanceReport','crm','format','تقرير الأداء اليومي
التاريخ: {date}
مرفق تقرير الأداء بصيغة PDF.','Daily performance report
Date: {date}
The performance report is attached as PDF.','تقرير الأداء اليومي
التاريخ: {date}
مرفق تقرير الأداء بصيغة PDF.','Daily performance report
Date: {date}
The performance report is attached as PDF.',true,now()),
  ('followups.export.contactDate','followups','crm','label','تاريخ التواصل','Contact Date','تاريخ التواصل','Contact Date',true,now()),
  ('followups.export.contract','followups','crm','label','العقد','Contract','العقد','Contract',true,now()),
  ('followups.export.method','followups','crm','label','طريقة التواصل','Contact Method','طريقة التواصل','Contact Method',true,now()),
  ('followups.export.nextFollowup','followups','crm','label','المتابعة القادمة','Next Follow-up','المتابعة القادمة','Next Follow-up',true,now()),
  ('followups.export.result','followups','crm','label','نتيجة التواصل','Contact Result','نتيجة التواصل','Contact Result',true,now()),
  ('followups.export.subtitle','followups','crm','title','التقرير يعكس الفلاتر المحددة في شاشة المتابعات','The report reflects the selected filters on the Follow-ups screen','التقرير يعكس الفلاتر المحددة في شاشة المتابعات','The report reflects the selected filters on the Follow-ups screen',true,now()),
  ('followups.export.title','followups','crm','title','تقرير المتابعات','Follow-ups Report','تقرير المتابعات','Follow-ups Report',true,now()),
  ('reportsOverview.export.acceptedValue','reportsOverview','crm','label','قيمة العروض المقبولة','Accepted contract value','قيمة العروض المقبولة','Accepted contract value',true,now()),
  ('reportsOverview.export.activityScore','reportsOverview','crm','label','درجة النشاط','Activity Score','درجة النشاط','Activity Score',true,now()),
  ('reportsOverview.export.change','reportsOverview','crm','label','التغير','Change','التغير','Change',true,now()),
  ('reportsOverview.export.changePercent','reportsOverview','crm','label','التغير %','Change %','التغير %','Change %',true,now()),
  ('reportsOverview.export.count','reportsOverview','crm','label','العدد','Count','العدد','Count',true,now()),
  ('reportsOverview.export.creatingPng','reportsOverview','crm','label','جاري إنشاء الصورة...','Creating image...','جاري إنشاء الصورة...','Creating image...',true,now()),
  ('reportsOverview.export.csvTitle','reportsOverview','crm','title','PETATOE — التقرير التنفيذي','PETATOE — Executive Report','PETATOE — التقرير التنفيذي','PETATOE — Executive Report',true,now()),
  ('reportsOverview.export.excelError','reportsOverview','crm','error','تعذر إنشاء ملف Excel.','Unable to create the Excel file.','تعذر إنشاء ملف Excel.','Unable to create the Excel file.',true,now()),
  ('reportsOverview.export.excelMissing','reportsOverview','crm','error','مكتبة Excel غير محملة.','Excel library is not loaded.','مكتبة Excel غير محملة.','Excel library is not loaded.',true,now()),
  ('reportsOverview.export.executiveSalesReport','reportsOverview','crm','label','تقرير المبيعات التنفيذي','Executive Sales Report','تقرير المبيعات التنفيذي','Executive Sales Report',true,now()),
  ('reportsOverview.export.exportPng','reportsOverview','crm','button','تصدير PNG','Export PNG','تصدير PNG','Export PNG',true,now()),
  ('reportsOverview.export.footer','reportsOverview','crm','note','تم الإنشاء بواسطة PETATOE — مركز التقارير المؤسسي','Generated by PETATOE — Enterprise Reports Center','تم الإنشاء بواسطة PETATOE — مركز التقارير المؤسسي','Generated by PETATOE — Enterprise Reports Center',true,now()),
  ('reportsOverview.export.from','reportsOverview','crm','label','من','From','من','From',true,now()),
  ('reportsOverview.export.generatedAt','reportsOverview','crm','label','تاريخ الإنشاء','Generated at','تاريخ الإنشاء','Generated at',true,now()),
  ('reportsOverview.export.kpi','reportsOverview','crm','label','المؤشر','KPI','المؤشر','KPI',true,now()),
  ('reportsOverview.export.noData','reportsOverview','crm','label','لا توجد بيانات تقرير متاحة.','No report data is available.','لا توجد بيانات تقرير متاحة.','No report data is available.',true,now()),
  ('reportsOverview.export.overdueFollowups','reportsOverview','crm','label','المتابعات المتأخرة','Overdue follow-ups','المتابعات المتأخرة','Overdue follow-ups',true,now()),
  ('reportsOverview.export.period','reportsOverview','crm','label','الفترة','Period','الفترة','Period',true,now()),
  ('reportsOverview.export.pngError','reportsOverview','crm','error','تعذر إنشاء صورة PNG.','Unable to create the PNG image.','تعذر إنشاء صورة PNG.','Unable to create the PNG image.',true,now()),
  ('reportsOverview.export.pngMissing','reportsOverview','crm','error','مكتبة PNG غير محملة.','PNG library is not loaded.','مكتبة PNG غير محملة.','PNG library is not loaded.',true,now()),
  ('reportsOverview.export.popupRequired','reportsOverview','crm','label','اسمح بالنوافذ المنبثقة لإنشاء تقرير PDF.','Allow pop-ups to create the PDF report.','اسمح بالنوافذ المنبثقة لإنشاء تقرير PDF.','Allow pop-ups to create the PDF report.',true,now()),
  ('reportsOverview.export.rank','reportsOverview','crm','label','الترتيب','Rank','الترتيب','Rank',true,now()),
  ('reportsOverview.export.repPerformance','reportsOverview','crm','label','أداء المندوبين','Representative Performance','أداء المندوبين','Representative Performance',true,now()),
  ('reportsOverview.export.sheetFunnel','reportsOverview','crm','label','مسار المبيعات','Sales Funnel','مسار المبيعات','Sales Funnel',true,now()),
  ('reportsOverview.export.sheetRepresentatives','reportsOverview','crm','label','المندوبون','Representatives','المندوبون','Representatives',true,now()),
  ('reportsOverview.export.sheetSummary','reportsOverview','crm','label','الملخص التنفيذي','Executive Summary','الملخص التنفيذي','Executive Summary',true,now()),
  ('reportsOverview.export.sheetTop10','reportsOverview','crm','label','أفضل 10','Top 10','أفضل 10','Top 10',true,now()),
  ('reportsOverview.export.stage','reportsOverview','crm','label','المرحلة','Stage','المرحلة','Stage',true,now()),
  ('reportsOverview.export.stageConversion','reportsOverview','crm','label','تحويل المرحلة %','Stage Conversion %','تحويل المرحلة %','Stage Conversion %',true,now()),
  ('reportsOverview.export.summaryTitle','reportsOverview','crm','title','PETATOE — ملخص التقرير التنفيذي','PETATOE — Executive Report Summary','PETATOE — ملخص التقرير التنفيذي','PETATOE — Executive Report Summary',true,now()),
  ('reportsOverview.export.to','reportsOverview','crm','label','إلى','to','إلى','to',true,now()),
  ('reportsOverview.export.topCustomer','reportsOverview','crm','label','أعلى عميل قيمة','Top customer by value','أعلى عميل قيمة','Top customer by value',true,now()),
  ('reportsOverview.export.topLossReason','reportsOverview','crm','label','أكثر سبب خسارة','Top loss reason','أكثر سبب خسارة','Top loss reason',true,now()),
  ('reportsOverview.export.topRepresentative','reportsOverview','crm','label','أفضل مندوب','Top representative','أفضل مندوب','Top representative',true,now()),
  ('reportsOverview.export.totalConversion','reportsOverview','crm','label','التحويل الكلي %','Total Conversion %','التحويل الكلي %','Total Conversion %',true,now()),
  ('shared.export.actions','shared','core','label','الإجراءات','Actions','الإجراءات','Actions',true,now()),
  ('shared.export.all','shared','core','label','الكل','All','الكل','All',true,now()),
  ('shared.export.close','shared','core','button','إغلاق','Close','إغلاق','Close',true,now()),
  ('shared.export.customer','shared','core','label','العميل','Customer','العميل','Customer',true,now()),
  ('shared.export.customerPhone','shared','core','label','رقم العميل','Customer phone','رقم العميل','Customer phone',true,now()),
  ('shared.export.exportFailed','shared','core','label','تعذر التصدير','Export failed','تعذر التصدير','Export failed',true,now()),
  ('shared.export.exportPdf','shared','core','button','تصدير PDF','Export PDF','تصدير PDF','Export PDF',true,now()),
  ('shared.export.exported','shared','core','label','تم التصدير','Exported','تم التصدير','Exported',true,now()),
  ('shared.export.exportedAt','shared','core','label','وقت التصدير','Exported at','وقت التصدير','Exported at',true,now()),
  ('shared.export.filteredWhatsappMessage','shared','core','format','{title}
عدد النتائج: {count}
مرفق التقرير بصيغة PDF وفق الفلاتر المحددة.','{title}
Results: {count}
The PDF report is attached using the selected filters.','{title}
عدد النتائج: {count}
مرفق التقرير بصيغة PDF وفق الفلاتر المحددة.','{title}
Results: {count}
The PDF report is attached using the selected filters.',true,now()),
  ('shared.export.filters','shared','core','label','الفلاتر','Filters','الفلاتر','Filters',true,now()),
  ('shared.export.noMatchingData','shared','core','label','لا توجد بيانات مطابقة للفلاتر المحددة.','No data matches the selected filters.','لا توجد بيانات مطابقة للفلاتر المحددة.','No data matches the selected filters.',true,now()),
  ('shared.export.noSearch','shared','core','label','بدون بحث','No search','بدون بحث','No search',true,now()),
  ('shared.export.pdfDownloadedAttach','shared','core','label','تم تنزيل ملف PDF على الجهاز لإرفاقه بالمحادثة.','The PDF was downloaded to the device. Attach it to the conversation.','تم تنزيل ملف PDF على الجهاز لإرفاقه بالمحادثة.','The PDF was downloaded to the device. Attach it to the conversation.',true,now()),
  ('shared.export.pdfToolsMissing','shared','core','error','تعذر تحميل أدوات إنشاء ملف PDF.','Unable to load PDF generation tools.','تعذر تحميل أدوات إنشاء ملف PDF.','Unable to load PDF generation tools.',true,now()),
  ('shared.export.prepareError','shared','core','error','تعذر تجهيز التقرير.','Unable to prepare the report.','تعذر تجهيز التقرير.','Unable to prepare the report.',true,now()),
  ('shared.export.prepareFailed','shared','core','label','تعذر التجهيز','Preparation failed','تعذر التجهيز','Preparation failed',true,now()),
  ('shared.export.preparingPdf','shared','core','label','جاري تجهيز PDF...','Preparing PDF...','جاري تجهيز PDF...','Preparing PDF...',true,now()),
  ('shared.export.ready','shared','core','label','تم التجهيز','Ready','تم التجهيز','Ready',true,now()),
  ('shared.export.reportReady','shared','core','label','تم تجهيز التقرير','Report ready','تم تجهيز التقرير','Report ready',true,now()),
  ('shared.export.representative','shared','core','label','المندوب','Representative','المندوب','Representative',true,now()),
  ('shared.export.resultCount','shared','core','label','عدد النتائج','Result count','عدد النتائج','Result count',true,now()),
  ('shared.export.search','shared','core','label','البحث','Search','البحث','Search',true,now()),
  ('shared.export.shareWhatsappPdf','shared','core','button','إرسال التقرير واتساب PDF','Share report via WhatsApp PDF','إرسال التقرير واتساب PDF','Share report via WhatsApp PDF',true,now()),
  ('shared.export.status','shared','core','label','الحالة','Status','الحالة','Status',true,now()),
  ('shared.export.value','shared','core','label','القيمة','Value','القيمة','Value',true,now()),
  ('shared.notifications.body.requestUpdated','shared','core','label','تم التعديل على الطلب رقم ','Request updated: ','تم التعديل على الطلب رقم ','Request updated: ',true,now()),
  ('shared.notifications.center.allEnabledAria','shared','core','aria','تفعيل أو إلغاء جميع الأحداث','Enable or disable all events','تفعيل أو إلغاء جميع الأحداث','Enable or disable all events',true,now()),
  ('shared.notifications.center.allInAppAria','shared','core','aria','تفعيل أو إلغاء الإشعارات داخل البرنامج لجميع الأحداث','Enable or disable in-app notifications for all events','تفعيل أو إلغاء الإشعارات داخل البرنامج لجميع الأحداث','Enable or disable in-app notifications for all events',true,now()),
  ('shared.notifications.center.allOwnerAria','shared','core','aria','تفعيل أو إلغاء إرسال جميع الأحداث لصاحب الطلب','Enable or disable all events for request owners','تفعيل أو إلغاء إرسال جميع الأحداث لصاحب الطلب','Enable or disable all events for request owners',true,now()),
  ('shared.notifications.center.allPushAria','shared','core','aria','تفعيل أو إلغاء Push لجميع الأحداث','Enable or disable Push for all events','تفعيل أو إلغاء Push لجميع الأحداث','Enable or disable Push for all events',true,now()),
  ('shared.notifications.center.allRoleAria','shared','core','aria','تفعيل أو إلغاء جميع الأحداث للدور المحدد','Enable or disable all events for the selected role','تفعيل أو إلغاء جميع الأحداث للدور المحدد','Enable or disable all events for the selected role',true,now()),
  ('shared.notifications.center.enabled','shared','core','label','مفعّل','Enabled','مفعّل','Enabled',true,now()),
  ('shared.notifications.center.error.generic','shared','core','error','تعذر تنفيذ العملية.','Unable to complete the operation.','تعذر تنفيذ العملية.','Unable to complete the operation.',true,now()),
  ('shared.notifications.center.event','shared','core','label','الحدث','Event','الحدث','Event',true,now()),
  ('shared.notifications.center.eventEnabled','shared','core','label','تفعيل الحدث','Enable Event','تفعيل الحدث','Enable Event',true,now()),
  ('shared.notifications.center.inApp','shared','core','label','داخل البرنامج','In App','داخل البرنامج','In App',true,now()),
  ('shared.notifications.center.loading','shared','core','label','جاري تحميل مركز الإشعارات...','Loading Notification Center...','جاري تحميل مركز الإشعارات...','Loading Notification Center...',true,now()),
  ('shared.notifications.center.matrixNote','shared','core','note','اختر الدور أولًا، ثم فعّل من المصفوفة الأحداث والقنوات التي يستقبلها هذا الدور. لا يوجد اختيار مباشر للمستخدمين؛ التوزيع يعتمد على الدور المحدد وصاحب الطلب فقط.','Select a role first, then enable the events and channels that role receives. There is no direct user selection; delivery depends on the selected role and request owner only.','اختر الدور أولًا، ثم فعّل من المصفوفة الأحداث والقنوات التي يستقبلها هذا الدور. لا يوجد اختيار مباشر للمستخدمين؛ التوزيع يعتمد على الدور المحدد وصاحب الطلب فقط.','Select a role first, then enable the events and channels that role receives. There is no direct user selection; delivery depends on the selected role and request owner only.',true,now()),
  ('shared.notifications.center.matrixTitle','shared','core','title','مصفوفة الإشعارات','Notification Matrix','مصفوفة الإشعارات','Notification Matrix',true,now()),
  ('shared.notifications.center.moduleInstallations','shared','core','label','التركيبات','Appointments','التركيبات','Appointments',true,now()),
  ('shared.notifications.center.noRole','shared','core','label','لا يوجد دور','No role','لا يوجد دور','No role',true,now()),
  ('shared.notifications.center.note','shared','core','note','تحديد أحداث النظام وقنوات الإشعار والمستلمين ديناميكيًا بدون ربط المستلمين بدور ثابت داخل الكود.','Configure system events, notification channels, and recipients dynamically without hard-coding recipients to a role.','تحديد أحداث النظام وقنوات الإشعار والمستلمين ديناميكيًا بدون ربط المستلمين بدور ثابت داخل الكود.','Configure system events, notification channels, and recipients dynamically without hard-coding recipients to a role.',true,now()),
  ('shared.notifications.center.owner','shared','core','label','صاحب الطلب','Request Owner','صاحب الطلب','Request Owner',true,now()),
  ('shared.notifications.center.push','shared','core','label','Push','Push','Push','Push',true,now()),
  ('shared.notifications.center.pushActive','shared','core','label','Push مفعّل على هذا الجهاز','Push is enabled on this device','Push مفعّل على هذا الجهاز','Push is enabled on this device',true,now()),
  ('shared.notifications.center.pushBlocked','shared','core','error','الإشعارات محظورة من إعدادات المتصفح','Notifications are blocked in browser settings','الإشعارات محظورة من إعدادات المتصفح','Notifications are blocked in browser settings',true,now()),
  ('shared.notifications.center.pushCellTitle','shared','core','title','إرسال Push خارج البرنامج للأجهزة المشتركة','Send Push outside the app to subscribed devices','إرسال Push خارج البرنامج للأجهزة المشتركة','Send Push outside the app to subscribed devices',true,now()),
  ('shared.notifications.center.pushChecking','shared','core','label','جاري فحص حالة الجهاز...','Checking device status...','جاري فحص حالة الجهاز...','Checking device status...',true,now()),
  ('shared.notifications.center.pushDisable','shared','core','button','إيقاف Push على هذا الجهاز','Disable Push on This Device','إيقاف Push على هذا الجهاز','Disable Push on This Device',true,now()),
  ('shared.notifications.center.pushDisabled','shared','core','label','تم إيقاف Push على هذا الجهاز.','Push was disabled on this device.','تم إيقاف Push على هذا الجهاز.','Push was disabled on this device.',true,now()),
  ('shared.notifications.center.pushEnable','shared','core','button','تفعيل Push على هذا الجهاز','Enable Push on This Device','تفعيل Push على هذا الجهاز','Enable Push on This Device',true,now()),
  ('shared.notifications.center.pushEnabled','shared','core','label','تم تفعيل إشعارات Push لهذا الجهاز.','Push notifications were enabled for this device.','تم تفعيل إشعارات Push لهذا الجهاز.','Push notifications were enabled for this device.',true,now()),
  ('shared.notifications.center.pushEnabling','shared','core','label','جاري تفعيل Push لهذا الجهاز...','Enabling Push for this device...','جاري تفعيل Push لهذا الجهاز...','Enabling Push for this device...',true,now()),
  ('shared.notifications.center.pushInactive','shared','core','label','Push غير مفعّل على هذا الجهاز','Push is not enabled on this device','Push غير مفعّل على هذا الجهاز','Push is not enabled on this device',true,now()),
  ('shared.notifications.center.pushNote','shared','core','note','فعّل الجهاز مرة واحدة لاستقبال إشعارات PETATOE خارج البرنامج حسب مصفوفة الأحداث أدناه.','Enable this device once to receive PETATOE notifications outside the app according to the event matrix below.','فعّل الجهاز مرة واحدة لاستقبال إشعارات PETATOE خارج البرنامج حسب مصفوفة الأحداث أدناه.','Enable this device once to receive PETATOE notifications outside the app according to the event matrix below.',true,now()),
  ('shared.notifications.center.pushServerNotConfigured','shared','core','label','الخادم غير مهيأ بمفاتيح Web Push','Server is not configured with Web Push keys','الخادم غير مهيأ بمفاتيح Web Push','Server is not configured with Web Push keys',true,now()),
  ('shared.notifications.center.pushTitle','shared','core','title','إشعارات Push لهذا الجهاز','Push Notifications for This Device','إشعارات Push لهذا الجهاز','Push Notifications for This Device',true,now()),
  ('shared.notifications.center.pushUnsupported','shared','core','label','غير مدعوم على هذا الجهاز','Not supported on this device','غير مدعوم على هذا الجهاز','Not supported on this device',true,now()),
  ('shared.notifications.center.role','shared','core','label','الدور','Role','الدور','Role',true,now()),
  ('shared.notifications.center.roleAria','shared','core','aria','اختيار الدور لإدارة إشعاراته','Select a role to manage its notifications','اختيار الدور لإدارة إشعاراته','Select a role to manage its notifications',true,now()),
  ('shared.notifications.center.roleNote','shared','core','note','تعديلات المصفوفة أدناه تخص الدور المحدد حاليًا، مع الاحتفاظ بإعدادات بقية الأدوار.','Matrix changes below apply to the currently selected role while preserving settings for other roles.','تعديلات المصفوفة أدناه تخص الدور المحدد حاليًا، مع الاحتفاظ بإعدادات بقية الأدوار.','Matrix changes below apply to the currently selected role while preserving settings for other roles.',true,now()),
  ('shared.notifications.center.roleRecipient','shared','core','label','إرسال للدور المحدد','Send to Selected Role','إرسال للدور المحدد','Send to Selected Role',true,now()),
  ('shared.notifications.center.save','shared','core','button','حفظ الإعدادات','Save Settings','حفظ الإعدادات','Save Settings',true,now()),
  ('shared.notifications.center.savedForRole','shared','core','format','تم حفظ مصفوفة الإشعارات للدور {role} بنجاح.','Notification matrix for role {role} was saved successfully.','تم حفظ مصفوفة الإشعارات للدور {role} بنجاح.','Notification matrix for role {role} was saved successfully.',true,now()),
  ('shared.notifications.center.saving','shared','core','label','جاري الحفظ...','Saving...','جاري الحفظ...','Saving...',true,now()),
  ('shared.notifications.center.systemNote','shared','core','note','عند الإيقاف لن يتم إنشاء إشعارات جديدة داخل البرنامج أو عبر Push حتى إعادة التفعيل.','When disabled, no new in-app or push notifications will be created until re-enabled.','عند الإيقاف لن يتم إنشاء إشعارات جديدة داخل البرنامج أو عبر Push حتى إعادة التفعيل.','When disabled, no new in-app or push notifications will be created until re-enabled.',true,now()),
  ('shared.notifications.center.systemTitle','shared','core','title','نظام الإشعارات','Notification System','نظام الإشعارات','Notification System',true,now()),
  ('shared.notifications.center.title','shared','core','title','مركز الإشعارات','Notification Center','مركز الإشعارات','Notification Center',true,now()),
  ('shared.notifications.event.installation.arrived','shared','core','label','وصل الموقع','Arrived at location','وصل الموقع','Arrived at location',true,now()),
  ('shared.notifications.event.installation.completed','shared','core','label','تم الانتهاء','Appointment completed','تم الانتهاء','Appointment completed',true,now()),
  ('shared.notifications.event.installation.execution.selected','shared','core','label','تم اختيار الموعد للتنفيذ','Appointment selected for execution','تم اختيار الموعد للتنفيذ','Appointment selected for execution',true,now()),
  ('shared.notifications.event.installation.map.opened','shared','core','label','فتح موقع العميل','Customer location opened','فتح موقع العميل','Customer location opened',true,now()),
  ('shared.notifications.event.installation.on.route','shared','core','label','بدء التحرك','On route','بدء التحرك','On route',true,now()),
  ('shared.notifications.event.installation.quantities.confirmed','shared','core','label','تم تأكيد الكميات','Quantities confirmed','تم تأكيد الكميات','Quantities confirmed',true,now()),
  ('shared.notifications.event.installation.remaining.added.to.next','shared','core','label','تم إضافة المتبقي للموعد التالي','Remaining quantity added to next appointment','تم إضافة المتبقي للموعد التالي','Remaining quantity added to next appointment',true,now()),
  ('shared.notifications.event.installation.remaining.to.schedule','shared','core','label','متبقي يحتاج جدولة','Remaining quantity requires scheduling','متبقي يحتاج جدولة','Remaining quantity requires scheduling',true,now()),
  ('shared.notifications.event.installation.request.created','shared','core','label','إنشاء طلب تركيب جديد','New appointment request created','إنشاء طلب تركيب جديد','New appointment request created',true,now()),
  ('shared.notifications.event.installation.request.updated','shared','core','label','تم تعديل الطلب','Appointment request updated','تم تعديل الطلب','Appointment request updated',true,now()),
  ('shared.notifications.event.installation.rescheduled','shared','core','label','تمت إعادة جدولة الموعد','Appointment rescheduled','تمت إعادة جدولة الموعد','Appointment rescheduled',true,now()),
  ('shared.notifications.event.installation.revisit.scheduled','shared','core','label','تمت جدولة إعادة الزيارة','Revisit scheduled','تمت جدولة إعادة الزيارة','Revisit scheduled',true,now()),
  ('shared.notifications.event.installation.schedule.cancelled','shared','core','label','تم إلغاء الجدولة','Schedule cancelled','تم إلغاء الجدولة','Schedule cancelled',true,now()),
  ('shared.notifications.event.installation.scheduled','shared','core','label','تمت جدولة الموعد','Appointment scheduled','تمت جدولة الموعد','Appointment scheduled',true,now()),
  ('shared.notifications.event.installation.work.started','shared','core','label','بدء الموعد','Appointment started','بدء الموعد','Appointment started',true,now()),
  ('shared.notifications.service.error.e01','shared','core','error','اتصال Supabase غير جاهز.','Supabase connection is not ready.','اتصال Supabase غير جاهز.','Supabase connection is not ready.',true,now()),
  ('shared.notifications.service.error.e02','shared','core','error','تعذر تحميل الإشعارات:','Unable to load notifications:','تعذر تحميل الإشعارات:','Unable to load notifications:',true,now()),
  ('shared.notifications.service.error.e03','shared','core','error','تعذر تحميل إعدادات الإشعارات:','Unable to load notification settings:','تعذر تحميل إعدادات الإشعارات:','Unable to load notification settings:',true,now()),
  ('shared.notifications.service.error.e04','shared','core','error','تعذر تحميل أحداث الإشعارات:','Unable to load notification events:','تعذر تحميل أحداث الإشعارات:','Unable to load notification events:',true,now()),
  ('shared.notifications.service.error.e05','shared','core','error','تعذر تحميل مستلمي الإشعارات:','Unable to load notification recipients:','تعذر تحميل مستلمي الإشعارات:','Unable to load notification recipients:',true,now()),
  ('shared.notifications.service.error.e06','shared','core','error','تعذر تحميل المستخدمين:','Unable to load users:','تعذر تحميل المستخدمين:','Unable to load users:',true,now()),
  ('shared.notifications.service.error.e07','shared','core','error','ليس لديك صلاحية تعديل مركز الإشعارات.','You do not have permission to edit Notification Center.','ليس لديك صلاحية تعديل مركز الإشعارات.','You do not have permission to edit Notification Center.',true,now()),
  ('shared.notifications.service.error.e08','shared','core','error','تعذر حفظ حالة نظام الإشعارات:','Unable to save notification system status:','تعذر حفظ حالة نظام الإشعارات:','Unable to save notification system status:',true,now()),
  ('shared.notifications.service.error.e09','shared','core','error','تعذر حفظ إعدادات الأحداث:','Unable to save event settings:','تعذر حفظ إعدادات الأحداث:','Unable to save event settings:',true,now()),
  ('shared.notifications.service.error.e10','shared','core','error','تعذر تحديث مستلمي الإشعارات:','Unable to update notification recipients:','تعذر تحديث مستلمي الإشعارات:','Unable to update notification recipients:',true,now()),
  ('shared.notifications.service.error.e11','shared','core','error','تعذر حفظ مصفوفة المستلمين:','Unable to save recipient matrix:','تعذر حفظ مصفوفة المستلمين:','Unable to save recipient matrix:',true,now()),
  ('shared.notifications.service.error.e12','shared','core','error','لم يتم منح صلاحية الإشعارات لهذا الجهاز.','Notification permission was not granted for this device.','لم يتم منح صلاحية الإشعارات لهذا الجهاز.','Notification permission was not granted for this device.',true,now()),
  ('shared.notifications.service.error.e13','shared','core','error','تعذر حفظ اشتراك Push:','Unable to save Push subscription:','تعذر حفظ اشتراك Push:','Unable to save Push subscription:',true,now()),
  ('shared.notifications.service.error.e14','shared','core','error','تعذر تحميل إعداد Web Push:','Unable to load Web Push settings:','تعذر تحميل إعداد Web Push:','Unable to load Web Push settings:',true,now()),
  ('shared.notifications.service.error.e15','shared','core','error','تحديث حالة الإشعار تحتاج اتصالًا بالإنترنت.','Updating notification status requires an internet connection.','تحديث حالة الإشعار تحتاج اتصالًا بالإنترنت.','Updating notification status requires an internet connection.',true,now()),
  ('shared.notifications.service.error.e16','shared','core','error','تحديث حالات الإشعارات تحتاج اتصالًا بالإنترنت.','Updating notification statuses requires an internet connection.','تحديث حالات الإشعارات تحتاج اتصالًا بالإنترنت.','Updating notification statuses requires an internet connection.',true,now()),
  ('pwa.update.release.r44r37.title','aboutApp','system','title','استكمال ترجمة التصدير والإشعارات والمحتوى المولد واعتماد L6 — R44R37','Complete exports, notifications, generated content localization and L6 certification — R44R37','استكمال ترجمة التصدير والإشعارات والمحتوى المولد واعتماد L6 — R44R37','Complete exports, notifications, generated content localization and L6 certification — R44R37',true,now()),
  ('pwa.update.release.r44r37.note1','aboutApp','system','note','ترجمة محتوى PDF وExcel وCSV وWhatsApp والتقارير المولدة حسب اللغة الحالية دون تغيير الحسابات.','Localize PDF, Excel, CSV, WhatsApp, and generated report content using the active language without changing calculations.','ترجمة محتوى PDF وExcel وCSV وWhatsApp والتقارير المولدة حسب اللغة الحالية دون تغيير الحسابات.','Localize PDF, Excel, CSV, WhatsApp, and generated report content using the active language without changing calculations.',true,now()),
  ('pwa.update.release.r44r37.note2','aboutApp','system','note','استكمال مركز الإشعارات ورسائل Push وأسماء الأحداث في طبقة العرض مع بقاء خدمات الإشعارات دون تعديل.','Complete Notification Center, Push messages, and event names in the display layer while keeping notification services unchanged.','استكمال مركز الإشعارات ورسائل Push وأسماء الأحداث في طبقة العرض مع بقاء خدمات الإشعارات دون تعديل.','Complete Notification Center, Push messages, and event names in the display layer while keeping notification services unchanged.',true,now()),
  ('pwa.update.release.r44r37.note3','aboutApp','system','note','الحفاظ على منطق الأعمال وOffline/Sync/Permissions وCSS دون تعديل مع اعتماد L6.','Preserve business logic, Offline/Sync/Permissions, and CSS unchanged while certifying L6.','الحفاظ على منطق الأعمال وOffline/Sync/Permissions وCSS دون تعديل مع اعتماد L6.','Preserve business logic, Offline/Sync/Permissions, and CSS unchanged while certifying L6.',true,now())
)
insert into public.app_translations (translation_key,screen_key,module_name,text_type,ar_text,en_text,default_ar,default_en,is_active,updated_at)
select translation_key,screen_key,module_name,text_type,ar_text,en_text,default_ar,default_en,is_active,updated_at
from translation_seed
on conflict (translation_key) do update set
  screen_key=excluded.screen_key,
  module_name=excluded.module_name,
  text_type=excluded.text_type,
  ar_text=case when nullif(btrim(public.app_translations.ar_text),'') is null then excluded.ar_text else public.app_translations.ar_text end,
  en_text=case when nullif(btrim(public.app_translations.en_text),'') is null then excluded.en_text else public.app_translations.en_text end,
  default_ar=excluded.default_ar,
  default_en=excluded.default_en,
  is_active=true,
  updated_at=now();

commit;
