-- R44R31 — CRM L2-A localization + selectable Contact Data date
-- Non-destructive seed for the canonical public.app_translations owner.
-- Existing customized ar_text/en_text values are preserved; only blank translations are filled.

begin;

with translation_seed(translation_key,screen_key,module_name,text_type,ar_text,en_text,default_ar,default_en,is_active,updated_at) as (
values
  ('representatives.page.title','representatives','crm','title','مندوبو المبيعات','Sales Representatives','مندوبو المبيعات','Sales Representatives',true,now()),
  ('representatives.page.subtitle','representatives','crm','subtitle','قائمة مسؤولي متابعة العملاء','Manage sales representatives responsible for customer follow-up','قائمة مسؤولي متابعة العملاء','Manage sales representatives responsible for customer follow-up',true,now()),
  ('representatives.action.template','representatives','crm','button','تنزيل نموذج Excel','Download Excel Template','تنزيل نموذج Excel','Download Excel Template',true,now()),
  ('representatives.action.import','representatives','crm','button','رفع مندوبي Excel','Import Representatives Excel','رفع مندوبي Excel','Import Representatives Excel',true,now()),
  ('representatives.action.add','representatives','crm','button','إضافة مندوب','Add Representative','إضافة مندوب','Add Representative',true,now()),
  ('representatives.action.save','representatives','crm','button','حفظ المندوب','Save Representative','حفظ المندوب','Save Representative',true,now()),
  ('representatives.action.edit','representatives','crm','button','تعديل','Edit','تعديل','Edit',true,now()),
  ('representatives.action.activate','representatives','crm','button','تفعيل','Activate','تفعيل','Activate',true,now()),
  ('representatives.action.deactivate','representatives','crm','button','إيقاف','Deactivate','إيقاف','Deactivate',true,now()),
  ('representatives.action.delete','representatives','crm','button','حذف','Delete','حذف','Delete',true,now()),
  ('representatives.filter.search','representatives','crm','label','بحث','Search','بحث','Search',true,now()),
  ('representatives.filter.searchPlaceholder','representatives','crm','placeholder','الاسم، الكود، الجوال أو البريد','Name, code, mobile, or email','الاسم، الكود، الجوال أو البريد','Name, code, mobile, or email',true,now()),
  ('representatives.filter.status','representatives','crm','label','الحالة','Status','الحالة','Status',true,now()),
  ('representatives.filter.allStatuses','representatives','crm','option','كل الحالات','All statuses','كل الحالات','All statuses',true,now()),
  ('representatives.status.active','representatives','crm','status','نشط','Active','نشط','Active',true,now()),
  ('representatives.status.inactive','representatives','crm','status','موقوف','Suspended','موقوف','Suspended',true,now()),
  ('representatives.status.inactiveLong','representatives','crm','status','غير نشط','Inactive','غير نشط','Inactive',true,now()),
  ('representatives.col.code','representatives','crm','table','كود المندوب','Representative Code','كود المندوب','Representative Code',true,now()),
  ('representatives.col.name','representatives','crm','table','اسم المندوب','Representative Name','اسم المندوب','Representative Name',true,now()),
  ('representatives.col.phone','representatives','crm','table','الجوال','Mobile','الجوال','Mobile',true,now()),
  ('representatives.col.email','representatives','crm','table','البريد الإلكتروني','Email','البريد الإلكتروني','Email',true,now()),
  ('representatives.col.customers','representatives','crm','table','العملاء المرتبطون','Linked Customers','العملاء المرتبطون','Linked Customers',true,now()),
  ('representatives.col.status','representatives','crm','table','الحالة','Status','الحالة','Status',true,now()),
  ('representatives.col.actions','representatives','crm','table','الإجراءات','Actions','الإجراءات','Actions',true,now()),
  ('representatives.empty','representatives','crm','empty','لا توجد نتائج مطابقة للمندوبين.','No matching representatives found.','لا توجد نتائج مطابقة للمندوبين.','No matching representatives found.',true,now()),
  ('representatives.dialog.addTitle','representatives','crm','title','إضافة مندوب مبيعات','Add Sales Representative','إضافة مندوب مبيعات','Add Sales Representative',true,now()),
  ('representatives.dialog.editTitle','representatives','crm','title','تعديل مندوب المبيعات','Edit Sales Representative','تعديل مندوب المبيعات','Edit Sales Representative',true,now()),
  ('representatives.field.code','representatives','crm','label','كود المندوب','Representative Code','كود المندوب','Representative Code',true,now()),
  ('representatives.field.name','representatives','crm','label','اسم المندوب','Representative Name','اسم المندوب','Representative Name',true,now()),
  ('representatives.field.phone','representatives','crm','label','رقم الجوال','Mobile Number','رقم الجوال','Mobile Number',true,now()),
  ('representatives.field.email','representatives','crm','label','البريد الإلكتروني','Email','البريد الإلكتروني','Email',true,now()),
  ('representatives.field.status','representatives','crm','label','حالة المندوب','Representative Status','حالة المندوب','Representative Status',true,now()),
  ('representatives.confirm.activate','representatives','crm','confirm','هل تريد إعادة تفعيل المندوب «{name}»؟','Reactivate representative “{name}”?','هل تريد إعادة تفعيل المندوب «{name}»؟','Reactivate representative “{name}”?',true,now()),
  ('representatives.confirm.deactivate','representatives','crm','confirm','هل تريد إيقاف المندوب «{name}»؟','Deactivate representative “{name}”?','هل تريد إيقاف المندوب «{name}»؟','Deactivate representative “{name}”?',true,now()),
  ('representatives.confirm.delete','representatives','crm','confirm','سيتم حذف المندوب «{name}» نهائيًا. هل تريد المتابعة؟','Representative “{name}” will be permanently deleted. Continue?','سيتم حذف المندوب «{name}» نهائيًا. هل تريد المتابعة؟','Representative “{name}” will be permanently deleted. Continue?',true,now()),
  ('representatives.status.changingActivate','representatives','crm','status','جاري إعادة تفعيل المندوب...','Reactivating representative...','جاري إعادة تفعيل المندوب...','Reactivating representative...',true,now()),
  ('representatives.status.changingDeactivate','representatives','crm','status','جاري إيقاف المندوب...','Deactivating representative...','جاري إيقاف المندوب...','Deactivating representative...',true,now()),
  ('representatives.status.activated','representatives','crm','status','تم تفعيل المندوب بنجاح.','Representative activated successfully.','تم تفعيل المندوب بنجاح.','Representative activated successfully.',true,now()),
  ('representatives.status.deactivated','representatives','crm','status','تم إيقاف المندوب بنجاح.','Representative deactivated successfully.','تم إيقاف المندوب بنجاح.','Representative deactivated successfully.',true,now()),
  ('representatives.status.deleting','representatives','crm','status','جاري حذف المندوب...','Deleting representative...','جاري حذف المندوب...','Deleting representative...',true,now()),
  ('representatives.status.deleted','representatives','crm','status','تم حذف المندوب بنجاح.','Representative deleted successfully.','تم حذف المندوب بنجاح.','Representative deleted successfully.',true,now()),
  ('representatives.error.status','representatives','crm','error','تعذر تغيير حالة المندوب.','Unable to change representative status.','تعذر تغيير حالة المندوب.','Unable to change representative status.',true,now()),
  ('representatives.error.linkedCustomers','representatives','crm','error','لا يمكن حذف «{name}» لأنه مرتبط بـ {count} عميل. انقل العملاء إلى مندوب آخر أو استخدم الإيقاف.','Cannot delete “{name}” because {count} customer(s) are linked. Reassign them or deactivate the representative.','لا يمكن حذف «{name}» لأنه مرتبط بـ {count} عميل. انقل العملاء إلى مندوب آخر أو استخدم الإيقاف.','Cannot delete “{name}” because {count} customer(s) are linked. Reassign them or deactivate the representative.',true,now()),
  ('representatives.error.linkedDeleteTitle','representatives','crm','title','لا يمكن الحذف قبل نقل العملاء المرتبطين','Linked customers must be reassigned before deletion','لا يمكن الحذف قبل نقل العملاء المرتبطين','Linked customers must be reassigned before deletion',true,now()),
  ('representatives.error.deleteLinked','representatives','crm','error','لا يمكن حذف المندوب لوجود بيانات مرتبطة به. استخدم الإيقاف بدلًا من الحذف.','The representative cannot be deleted because linked data exists. Deactivate instead.','لا يمكن حذف المندوب لوجود بيانات مرتبطة به. استخدم الإيقاف بدلًا من الحذف.','The representative cannot be deleted because linked data exists. Deactivate instead.',true,now()),
  ('representatives.error.delete','representatives','crm','error','تعذر حذف المندوب.','Unable to delete representative.','تعذر حذف المندوب.','Unable to delete representative.',true,now()),
  ('representatives.error.save','representatives','crm','error','تعذر حفظ المندوب.','Unable to save representative.','تعذر حفظ المندوب.','Unable to save representative.',true,now()),
  ('representatives.permission.manage','representatives','crm','error','لا توجد صلاحية إدارة مندوبي المبيعات.','You do not have permission to manage sales representatives.','لا توجد صلاحية إدارة مندوبي المبيعات.','You do not have permission to manage sales representatives.',true,now()),
  ('representatives.permission.save','representatives','crm','error','لا توجد صلاحية حفظ مندوبي المبيعات.','You do not have permission to save sales representatives.','لا توجد صلاحية حفظ مندوبي المبيعات.','You do not have permission to save sales representatives.',true,now()),
  ('representatives.permission.delete','representatives','crm','error','لا توجد صلاحية حذف مندوبي المبيعات.','You do not have permission to delete sales representatives.','لا توجد صلاحية حذف مندوبي المبيعات.','You do not have permission to delete sales representatives.',true,now()),
  ('representatives.permission.import','representatives','crm','error','لا توجد صلاحية استيراد مندوبي المبيعات.','You do not have permission to import sales representatives.','لا توجد صلاحية استيراد مندوبي المبيعات.','You do not have permission to import sales representatives.',true,now()),
  ('representatives.permission.template','representatives','crm','error','لا توجد صلاحية تنزيل نموذج المندوبين.','You do not have permission to download the representative template.','لا توجد صلاحية تنزيل نموذج المندوبين.','You do not have permission to download the representative template.',true,now()),
  ('representatives.import.title','representatives','crm','title','استيراد مندوبي المبيعات من Excel','Import Sales Representatives from Excel','استيراد مندوبي المبيعات من Excel','Import Sales Representatives from Excel',true,now()),
  ('representatives.import.note','representatives','crm','help','يتم التحقق من جميع الصفوف قبل حفظ أي بيانات.','All rows are validated before any data is saved.','يتم التحقق من جميع الصفوف قبل حفظ أي بيانات.','All rows are validated before any data is saved.',true,now()),
  ('representatives.import.chooseFile','representatives','crm','button','اختيار ملف Excel','Choose Excel File','اختيار ملف Excel','Choose Excel File',true,now()),
  ('representatives.import.noFile','representatives','crm','status','لم يتم اختيار ملف','No file selected','لم يتم اختيار ملف','No file selected',true,now()),
  ('representatives.import.totalRows','representatives','crm','label','إجمالي الصفوف','Total Rows','إجمالي الصفوف','Total Rows',true,now()),
  ('representatives.import.validRows','representatives','crm','label','صفوف صحيحة','Valid Rows','صفوف صحيحة','Valid Rows',true,now()),
  ('representatives.import.errorRows','representatives','crm','label','صفوف بها أخطاء','Rows with Errors','صفوف بها أخطاء','Rows with Errors',true,now()),
  ('representatives.import.newRows','representatives','crm','label','مندوبي مبيعات جدد','New Representatives','مندوبي مبيعات جدد','New Representatives',true,now()),
  ('representatives.import.duplicateRows','representatives','crm','label','مكرر داخل الملف','Duplicates in File','مكرر داخل الملف','Duplicates in File',true,now()),
  ('representatives.import.existingRows','representatives','crm','label','موجود بالنظام','Already in System','موجود بالنظام','Already in System',true,now()),
  ('representatives.import.notes','representatives','crm','table','الملاحظات','Notes','الملاحظات','Notes',true,now()),
  ('representatives.import.previewEmpty','representatives','crm','empty','اختر ملف Excel لعرض المعاينة.','Choose an Excel file to preview it.','اختر ملف Excel لعرض المعاينة.','Choose an Excel file to preview it.',true,now()),
  ('representatives.import.downloadFailed','representatives','crm','button','تنزيل الصفوف الفاشلة','Download Failed Rows','تنزيل الصفوف الفاشلة','Download Failed Rows',true,now()),
  ('representatives.import.execute','representatives','crm','button','اعتماد الاستيراد','Import Valid Rows','اعتماد الاستيراد','Import Valid Rows',true,now()),
  ('representatives.import.status.error','representatives','crm','status','خطأ','Error','خطأ','Error',true,now()),
  ('representatives.import.status.new','representatives','crm','status','جديد','New','جديد','New',true,now()),
  ('representatives.import.status.ready','representatives','crm','status','جاهز','Ready','جاهز','Ready',true,now()),
  ('representatives.import.previewLimited','representatives','crm','help','يتم عرض أول {limit} صف فقط من أصل {total} صف للحفاظ على سرعة الواجهة. سيتم استيراد جميع الصفوف الصحيحة.','Only the first {limit} of {total} rows are shown to keep the interface responsive. All valid rows will be imported.','يتم عرض أول {limit} صف فقط من أصل {total} صف للحفاظ على سرعة الواجهة. سيتم استيراد جميع الصفوف الصحيحة.','Only the first {limit} of {total} rows are shown to keep the interface responsive. All valid rows will be imported.',true,now()),
  ('representatives.import.reading','representatives','crm','status','جاري قراءة الملف والتحقق من البيانات...','Reading the file and validating data...','جاري قراءة الملف والتحقق من البيانات...','Reading the file and validating data...',true,now()),
  ('representatives.import.checkedWithErrors','representatives','crm','status','تم التحقق: سيتم استيراد {valid} صف صحيح وتجاهل {errors} صف به أخطاء.','Validated: {valid} valid row(s) will be imported and {errors} row(s) with errors will be skipped.','تم التحقق: سيتم استيراد {valid} صف صحيح وتجاهل {errors} صف به أخطاء.','Validated: {valid} valid row(s) will be imported and {errors} row(s) with errors will be skipped.',true,now()),
  ('representatives.import.checkedReady','representatives','crm','status','تم التحقق من الملف وهو جاهز للاستيراد.','The file has been validated and is ready to import.','تم التحقق من الملف وهو جاهز للاستيراد.','The file has been validated and is ready to import.',true,now()),
  ('representatives.import.error.read','representatives','crm','error','تعذر قراءة ملف Excel.','Unable to read the Excel file.','تعذر قراءة ملف Excel.','Unable to read the Excel file.',true,now()),
  ('representatives.import.error.downloadTemplate','representatives','crm','error','تعذر تنزيل النموذج.','Unable to download the template.','تعذر تنزيل النموذج.','Unable to download the template.',true,now()),
  ('representatives.import.error.exportFailed','representatives','crm','error','تعذر تصدير الصفوف الفاشلة.','Unable to export failed rows.','تعذر تصدير الصفوف الفاشلة.','Unable to export failed rows.',true,now()),
  ('representatives.import.progress','representatives','crm','status','جاري استيراد {current} من {total}...','Importing {current} of {total}...','جاري استيراد {current} من {total}...','Importing {current} of {total}...',true,now()),
  ('representatives.import.complete','representatives','crm','status','اكتمل الاستيراد: {inserted} مندوب جديد، {failed} فشل.','Import complete: {inserted} new representative(s), {failed} failed.','اكتمل الاستيراد: {inserted} مندوب جديد، {failed} فشل.','Import complete: {inserted} new representative(s), {failed} failed.',true,now()),
  ('representatives.import.error.execute','representatives','crm','error','تعذر تنفيذ الاستيراد.','Unable to complete the import.','تعذر تنفيذ الاستيراد.','Unable to complete the import.',true,now()),
  ('representatives.import.excelMissing','representatives','crm','error','مكتبة Excel غير محملة.','Excel library is not loaded.','مكتبة Excel غير محملة.','Excel library is not loaded.',true,now()),
  ('representatives.import.fileRequired','representatives','crm','error','اختر ملف Excel أولًا.','Choose an Excel file first.','اختر ملف Excel أولًا.','Choose an Excel file first.',true,now()),
  ('representatives.import.sheetMissing','representatives','crm','error','ملف Excel لا يحتوي على ورقة بيانات.','The Excel file does not contain a data sheet.','ملف Excel لا يحتوي على ورقة بيانات.','The Excel file does not contain a data sheet.',true,now()),
  ('representatives.import.validation.codeRequired','representatives','crm','validation','كود المندوب إلزامي','Representative code is required','كود المندوب إلزامي','Representative code is required',true,now()),
  ('representatives.import.validation.nameRequired','representatives','crm','validation','اسم المندوب إلزامي','Representative name is required','اسم المندوب إلزامي','Representative name is required',true,now()),
  ('representatives.import.validation.phoneInvalid','representatives','crm','validation','رقم الجوال غير صحيح','Invalid mobile number','رقم الجوال غير صحيح','Invalid mobile number',true,now()),
  ('representatives.import.validation.emailInvalid','representatives','crm','validation','البريد الإلكتروني غير صحيح','Invalid email address','البريد الإلكتروني غير صحيح','Invalid email address',true,now()),
  ('representatives.import.validation.statusInvalid','representatives','crm','validation','الحالة يجب أن تكون نشط أو موقوف','Status must be Active or Suspended','الحالة يجب أن تكون نشط أو موقوف','Status must be Active or Suspended',true,now()),
  ('representatives.import.validation.duplicateFile','representatives','crm','validation','مكرر داخل الملف','Duplicate in file','مكرر داخل الملف','Duplicate in file',true,now()),
  ('representatives.import.validation.exists','representatives','crm','validation','مندوب موجود مسبقًا في النظام','Representative already exists in the system','مندوب موجود مسبقًا في النظام','Representative already exists in the system',true,now()),
  ('representatives.import.error.saveService','representatives','crm','error','خدمة حفظ المندوبين غير متاحة.','Representative save service is unavailable.','خدمة حفظ المندوبين غير متاحة.','Representative save service is unavailable.',true,now()),
  ('representatives.import.error.noFailedRows','representatives','crm','error','لا توجد صفوف فاشلة للتصدير.','There are no failed rows to export.','لا توجد صفوف فاشلة للتصدير.','There are no failed rows to export.',true,now()),
  ('representatives.import.sheet.template','representatives','crm','label','نموذج المندوبين','Representative Template','نموذج المندوبين','Representative Template',true,now()),
  ('representatives.import.sheet.failed','representatives','crm','label','الصفوف الفاشلة','Failed Rows','الصفوف الفاشلة','Failed Rows',true,now()),
  ('representatives.import.header.row','representatives','crm','table','رقم الصف','Row Number','رقم الصف','Row Number',true,now()),
  ('representatives.import.header.failure','representatives','crm','table','سبب الفشل','Failure Reason','سبب الفشل','Failure Reason',true,now()),
  ('referenceData.page.title','settings','crm','title','البيانات المرجعية','Reference Data','البيانات المرجعية','Reference Data',true,now()),
  ('referenceData.page.subtitle','settings','crm','subtitle','مجالات الاهتمام وأسباب عدم البيع','Customer interests and no-sale reasons','مجالات الاهتمام وأسباب عدم البيع','Customer interests and no-sale reasons',true,now()),
  ('referenceData.filter.section','settings','crm','label','اختر التبويب','Choose Section','اختر التبويب','Choose Section',true,now()),
  ('referenceData.section.interests','settings','crm','option','مجالات اهتمام العملاء','Customer Interest Categories','مجالات اهتمام العملاء','Customer Interest Categories',true,now()),
  ('referenceData.section.reasons','settings','crm','option','أسباب عدم البيع','No-sale Reasons','أسباب عدم البيع','No-sale Reasons',true,now()),
  ('referenceData.section.customers','settings','crm','option','العملاء','Customers','العملاء','Customers',true,now()),
  ('referenceData.interests.title','settings','crm','title','مجالات اهتمام العملاء','Customer Interest Categories','مجالات اهتمام العملاء','Customer Interest Categories',true,now()),
  ('referenceData.interests.note','settings','crm','help','إضافة وتعديل وتفعيل وحذف مجالات الاهتمام.','Add, edit, activate, and delete interest categories.','إضافة وتعديل وتفعيل وحذف مجالات الاهتمام.','Add, edit, activate, and delete interest categories.',true,now()),
  ('referenceData.reasons.title','settings','crm','title','أسباب عدم البيع','No-sale Reasons','أسباب عدم البيع','No-sale Reasons',true,now()),
  ('referenceData.reasons.note','settings','crm','help','إدارة وتعديل وتفعيل وحذف أسباب الرفض المستخدمة في العقود والمتابعات.','Manage the rejection reasons used in contracts and follow-ups.','إدارة وتعديل وتفعيل وحذف أسباب الرفض المستخدمة في العقود والمتابعات.','Manage the rejection reasons used in contracts and follow-ups.',true,now()),
  ('referenceData.action.add','settings','crm','button','إضافة','Add','إضافة','Add',true,now()),
  ('referenceData.action.edit','settings','crm','button','تعديل','Edit','تعديل','Edit',true,now()),
  ('referenceData.action.delete','settings','crm','button','حذف','Delete','حذف','Delete',true,now()),
  ('referenceData.customers.title','settings','crm','title','العملاء','Customers','العملاء','Customers',true,now()),
  ('referenceData.customers.note','settings','crm','help','سجل العميل الأساسي: code و name و address و mobile فقط.','Basic customer record: code, name, address, and mobile only.','سجل العميل الأساسي: code و name و address و mobile فقط.','Basic customer record: code, name, address, and mobile only.',true,now()),
  ('referenceData.customers.import','settings','crm','button','رفع Excel','Import Excel','رفع Excel','Import Excel',true,now()),
  ('referenceData.customers.export','settings','crm','button','تصدير Excel','Export Excel','تصدير Excel','Export Excel',true,now()),
  ('referenceData.customers.template','settings','crm','button','تنزيل النموذج','Download Template','تنزيل النموذج','Download Template',true,now()),
  ('referenceData.customers.add','settings','crm','button','إضافة عميل','Add Customer','إضافة عميل','Add Customer',true,now()),
  ('referenceData.customers.search','settings','crm','label','بحث','Search','بحث','Search',true,now()),
  ('referenceData.customers.searchPlaceholder','settings','crm','placeholder','الكود أو الاسم أو العنوان أو الجوال','Code, name, address, or mobile','الكود أو الاسم أو العنوان أو الجوال','Code, name, address, or mobile',true,now()),
  ('referenceData.customers.previous','settings','crm','button','السابق','Previous','السابق','Previous',true,now()),
  ('referenceData.customers.next','settings','crm','button','التالي','Next','التالي','Next',true,now()),
  ('referenceData.customers.empty','settings','crm','empty','لا توجد نتائج مطابقة.','No matching results.','لا توجد نتائج مطابقة.','No matching results.',true,now()),
  ('referenceData.customers.loading','settings','crm','status','جاري تحميل بيانات العملاء...','Loading customer data...','جاري تحميل بيانات العملاء...','Loading customer data...',true,now()),
  ('referenceData.customers.open','settings','crm','button','فتح','Open','فتح','Open',true,now()),
  ('referenceData.dialog.addTitle','settings','crm','title','إضافة بيانات مرجعية','Add Reference Data','إضافة بيانات مرجعية','Add Reference Data',true,now()),
  ('referenceData.dialog.editTitle','settings','crm','title','تعديل {item}','Edit {item}','تعديل {item}','Edit {item}',true,now()),
  ('referenceData.dialog.addItemTitle','settings','crm','title','إضافة {item}','Add {item}','إضافة {item}','Add {item}',true,now()),
  ('referenceData.dialog.note','settings','crm','help','يتم منع تكرار الاسم داخل قاعدة البيانات.','Duplicate names are prevented in the database.','يتم منع تكرار الاسم داخل قاعدة البيانات.','Duplicate names are prevented in the database.',true,now()),
  ('referenceData.dialog.name','settings','crm','label','الاسم','Name','الاسم','Name',true,now()),
  ('referenceData.dialog.status','settings','crm','label','الحالة','Status','الحالة','Status',true,now()),
  ('referenceData.status.active','settings','crm','status','نشط','Active','نشط','Active',true,now()),
  ('referenceData.status.inactive','settings','crm','status','غير نشط','Inactive','غير نشط','Inactive',true,now()),
  ('referenceData.empty','settings','crm','empty','لا توجد بيانات مسجلة.','No data has been recorded.','لا توجد بيانات مسجلة.','No data has been recorded.',true,now()),
  ('referenceData.item.interest','settings','crm','noun','مجال الاهتمام','interest category','مجال الاهتمام','interest category',true,now()),
  ('referenceData.item.reason','settings','crm','noun','سبب عدم البيع','no-sale reason','سبب عدم البيع','no-sale reason',true,now()),
  ('referenceData.confirm.delete','settings','crm','confirm','سيتم حذف {item} «{name}» نهائيًا. هل تريد المتابعة؟','{item} “{name}” will be permanently deleted. Continue?','سيتم حذف {item} «{name}» نهائيًا. هل تريد المتابعة؟','{item} “{name}” will be permanently deleted. Continue?',true,now()),
  ('referenceData.status.deleting','settings','crm','status','جاري حذف {item}...','Deleting {item}...','جاري حذف {item}...','Deleting {item}...',true,now()),
  ('referenceData.status.deleted','settings','crm','status','تم حذف {item} بنجاح.','{item} deleted successfully.','تم حذف {item} بنجاح.','{item} deleted successfully.',true,now()),
  ('referenceData.error.linked','settings','crm','error','لا يمكن حذف {item} لأنه مستخدم في بيانات حالية. عدّل حالته إلى «غير نشط» بدل الحذف.','Cannot delete {item} because it is used by current data. Set it to Inactive instead.','لا يمكن حذف {item} لأنه مستخدم في بيانات حالية. عدّل حالته إلى «غير نشط» بدل الحذف.','Cannot delete {item} because it is used by current data. Set it to Inactive instead.',true,now()),
  ('referenceData.error.delete','settings','crm','error','تعذر حذف {item}.','Unable to delete {item}.','تعذر حذف {item}.','Unable to delete {item}.',true,now()),
  ('referenceData.error.save','settings','crm','error','تعذر حفظ البيانات المرجعية.','Unable to save reference data.','تعذر حفظ البيانات المرجعية.','Unable to save reference data.',true,now()),
  ('referenceData.permission.manage','settings','crm','error','لا توجد صلاحية إدارة البيانات المرجعية.','You do not have permission to manage reference data.','لا توجد صلاحية إدارة البيانات المرجعية.','You do not have permission to manage reference data.',true,now()),
  ('referenceData.permission.save','settings','crm','error','لا توجد صلاحية حفظ البيانات المرجعية.','You do not have permission to save reference data.','لا توجد صلاحية حفظ البيانات المرجعية.','You do not have permission to save reference data.',true,now()),
  ('referenceData.permission.delete','settings','crm','error','لا توجد صلاحية حذف البيانات المرجعية.','You do not have permission to delete reference data.','لا توجد صلاحية حذف البيانات المرجعية.','You do not have permission to delete reference data.',true,now()),
  ('referenceData.service.operation','settings','crm','label','هذه العملية','This operation','هذه العملية','This operation',true,now()),
  ('referenceData.service.dbNotReady','settings','crm','error','اتصال Supabase غير جاهز.','Supabase connection is not ready.','اتصال Supabase غير جاهز.','Supabase connection is not ready.',true,now()),
  ('referenceData.service.onlineRequired','settings','crm','error','{operation} تحتاج اتصالًا بالإنترنت.','{operation} requires an internet connection.','{operation} تحتاج اتصالًا بالإنترنت.','{operation} requires an internet connection.',true,now()),
  ('referenceData.service.duplicate','settings','crm','error','لا يمكن الحفظ لأن القيمة مسجلة مسبقًا.','Cannot save because the value already exists.','لا يمكن الحفظ لأن القيمة مسجلة مسبقًا.','Cannot save because the value already exists.',true,now()),
  ('referenceData.service.loadRepresentatives','settings','crm','error','تعذر تحميل المندوبين','Unable to load representatives','تعذر تحميل المندوبين','Unable to load representatives',true,now()),
  ('referenceData.service.addRepresentative','settings','crm','label','إضافة المندوب','Add representative','إضافة المندوب','Add representative',true,now()),
  ('referenceData.service.editRepresentative','settings','crm','label','تعديل المندوب','Edit representative','تعديل المندوب','Edit representative',true,now()),
  ('referenceData.service.changeRepresentativeStatus','settings','crm','label','تغيير حالة المندوب','Change representative status','تغيير حالة المندوب','Change representative status',true,now()),
  ('referenceData.service.deleteRepresentative','settings','crm','label','حذف المندوب','Delete representative','حذف المندوب','Delete representative',true,now()),
  ('referenceData.service.errorAddRepresentative','settings','crm','error','تعذر إضافة المندوب','Unable to add representative','تعذر إضافة المندوب','Unable to add representative',true,now()),
  ('referenceData.service.errorEditRepresentative','settings','crm','error','تعذر تعديل المندوب','Unable to edit representative','تعذر تعديل المندوب','Unable to edit representative',true,now()),
  ('referenceData.service.errorStatusRepresentative','settings','crm','error','تعذر تغيير حالة المندوب','Unable to change representative status','تعذر تغيير حالة المندوب','Unable to change representative status',true,now()),
  ('referenceData.service.errorDeleteRepresentative','settings','crm','error','تعذر حذف المندوب','Unable to delete representative','تعذر حذف المندوب','Unable to delete representative',true,now()),
  ('referenceData.service.loadReference','settings','crm','error','تعذر تحميل البيانات المرجعية','Unable to load reference data','تعذر تحميل البيانات المرجعية','Unable to load reference data',true,now()),
  ('referenceData.service.addReference','settings','crm','label','إضافة البيانات المرجعية','Add reference data','إضافة البيانات المرجعية','Add reference data',true,now()),
  ('referenceData.service.editReference','settings','crm','label','تعديل البيانات المرجعية','Edit reference data','تعديل البيانات المرجعية','Edit reference data',true,now()),
  ('referenceData.service.deleteReference','settings','crm','label','حذف البيانات المرجعية','Delete reference data','حذف البيانات المرجعية','Delete reference data',true,now()),
  ('referenceData.service.errorAddReference','settings','crm','error','تعذر إضافة البيانات المرجعية','Unable to add reference data','تعذر إضافة البيانات المرجعية','Unable to add reference data',true,now()),
  ('referenceData.service.errorEditReference','settings','crm','error','تعذر تعديل البيانات المرجعية','Unable to edit reference data','تعذر تعديل البيانات المرجعية','Unable to edit reference data',true,now()),
  ('referenceData.service.errorDeleteReference','settings','crm','error','تعذر حذف البيانات المرجعية','Unable to delete reference data','تعذر حذف البيانات المرجعية','Unable to delete reference data',true,now()),
  ('appointments.contact.context.dateAria','installationContactData','appointments','aria','اختر تاريخ البيانات','Choose data date','اختر تاريخ البيانات','Choose data date',true,now()),
  ('appointments.contact.loadedSelected','installationContactData','appointments','status','تم تحميل البيانات المحفوظة للتاريخ المحدد.','Saved data for the selected date has been loaded.','تم تحميل البيانات المحفوظة للتاريخ المحدد.','Saved data for the selected date has been loaded.',true,now()),
  ('appointments.contact.readySelected','installationContactData','appointments','status','جاهز لتسجيل بيانات التاريخ المحدد.','Ready to record data for the selected date.','جاهز لتسجيل بيانات التاريخ المحدد.','Ready to record data for the selected date.',true,now()),
  ('appointments.contact.savingSelected','installationContactData','appointments','status','جاري حفظ بيانات التاريخ المحدد...','Saving data for the selected date...','جاري حفظ بيانات التاريخ المحدد...','Saving data for the selected date...',true,now()),
  ('appointments.contact.savedSelected','installationContactData','appointments','status','تم حفظ بيانات التاريخ المحدد بنجاح.','Data for the selected date was saved successfully.','تم حفظ بيانات التاريخ المحدد بنجاح.','Data for the selected date was saved successfully.',true,now()),
  ('appointments.contact.dateChange.confirm','installationContactData','appointments','confirm','توجد تعديلات غير محفوظة. هل تريد تغيير التاريخ وتجاهلها؟','There are unsaved changes. Change the date and discard them?','توجد تعديلات غير محفوظة. هل تريد تغيير التاريخ وتجاهلها؟','There are unsaved changes. Change the date and discard them?',true,now()),
  ('pwa.update.release.r44r31.title','aboutApp','system','title','استكمال ترجمة CRM واختيار تاريخ بيانات التواصل','CRM Localization & Selectable Contact Data Date','استكمال ترجمة CRM واختيار تاريخ بيانات التواصل','CRM Localization & Selectable Contact Data Date',true,now()),
  ('pwa.update.release.r44r31.note1','aboutApp','system','help','استكمال ترجمة شاشات مندوبي المبيعات والبيانات المرجعية ورسائلها التشغيلية بالعربية والإنجليزية.','Completes Arabic/English localization for Sales Representatives, Reference Data, and their runtime messages.','استكمال ترجمة شاشات مندوبي المبيعات والبيانات المرجعية ورسائلها التشغيلية بالعربية والإنجليزية.','Completes Arabic/English localization for Sales Representatives, Reference Data, and their runtime messages.',true,now()),
  ('pwa.update.release.r44r31.note2','aboutApp','system','help','إتاحة اختيار تاريخ بيانات التواصل وتحميل أو إنشاء سجل اليوم المحدد باستخدام نفس work_date المعتمد.','Allows selecting the Contact Data date and loading or creating the record for that date using the existing work_date contract.','إتاحة اختيار تاريخ بيانات التواصل وتحميل أو إنشاء سجل اليوم المحدد باستخدام نفس work_date المعتمد.','Allows selecting the Contact Data date and loading or creating the record for that date using the existing work_date contract.',true,now()),
  ('pwa.update.release.r44r31.note3','aboutApp','system','help','إصلاح Migration Manifest metadata وإبقاء منطق المواعيد والمالية والمزامنة والصلاحيات دون تغيير.','Reconciles Migration Manifest metadata while leaving appointment, finance, sync, and permission logic unchanged.','إصلاح Migration Manifest metadata وإبقاء منطق المواعيد والمالية والمزامنة والصلاحيات دون تغيير.','Reconciles Migration Manifest metadata while leaving appointment, finance, sync, and permission logic unchanged.',true,now())
)
insert into public.app_translations (translation_key,screen_key,module_name,text_type,ar_text,en_text,default_ar,default_en,is_active,updated_at)
select * from translation_seed
on conflict (translation_key) do update set
  screen_key=excluded.screen_key,
  module_name=excluded.module_name,
  text_type=excluded.text_type,
  ar_text=case when nullif(trim(public.app_translations.ar_text),'') is null then excluded.ar_text else public.app_translations.ar_text end,
  en_text=case when nullif(trim(public.app_translations.en_text),'') is null then excluded.en_text else public.app_translations.en_text end,
  default_ar=excluded.default_ar,
  default_en=excluded.default_en,
  is_active=true,
  updated_at=now();

commit;
