begin;
create or replace function public.petatoe_neighborhood_key(p_value text) returns text language sql immutable set search_path=public as $$ select nullif(btrim(regexp_replace(regexp_replace(translate(regexp_replace(coalesce(p_value,''), '[ًٌٍَُِّْـ]', '', 'g'),'أإآى','اااي'),'^[[:space:]]*حي[[:space:]]+','','i'),'[[:space:]]+(مدينة[[:space:]]+)?جدة[[:space:]]*$','','i')),'') $$;
create or replace function public.resolve_petatoe_customer_neighborhood(p_customer_id uuid) returns uuid language plpgsql stable security definer set search_path=public as $$ declare v_existing uuid; v_address text; v_key text; v_match uuid; v_count integer; begin if auth.uid() is null then raise exception 'Authentication required'; end if; select c.neighborhood_id,c.address into v_existing,v_address from public.customers c where c.id=p_customer_id; if v_existing is not null then return v_existing; end if; v_key=public.petatoe_neighborhood_key(v_address); if v_key is null then return null; end if; select min(n.id),count(*) into v_match,v_count from public.installation_neighborhoods n where n.is_active=true and public.petatoe_neighborhood_key(n.name)=v_key; if v_count=1 then return v_match; end if; return null; end $$;
revoke all on function public.resolve_petatoe_customer_neighborhood(uuid) from public,anon; grant execute on function public.resolve_petatoe_customer_neighborhood(uuid) to authenticated,service_role;
with matches as (select c.id customer_id,min(n.id) neighborhood_id,count(*) matches from public.customers c join public.installation_neighborhoods n on n.is_active=true and public.petatoe_neighborhood_key(n.name)=public.petatoe_neighborhood_key(c.address) where c.neighborhood_id is null and public.petatoe_neighborhood_key(c.address) is not null group by c.id) update public.customers c set neighborhood_id=m.neighborhood_id,updated_at=now() from matches m where c.id=m.customer_id and m.matches=1;
create or replace function public.get_customer_appointment_defaults(p_customer_id uuid) returns jsonb language plpgsql stable security definer set search_path=public as $$ declare v_customer record; v_request_id uuid; v_last_neighborhood_id uuid; v_last_map_url text; v_resolved uuid; v_name text; v_result jsonb; begin if auth.uid() is null then raise exception 'Authentication required'; end if; select c.neighborhood_id,c.google_maps_url,c.address into v_customer from public.customers c where c.id=p_customer_id; select r.id,r.neighborhood_id,r.customer_map_url into v_request_id,v_last_neighborhood_id,v_last_map_url from public.installation_requests r where r.customer_id=p_customer_id order by coalesce(r.scheduled_date,r.created_at::date) desc,r.created_at desc limit 1; v_resolved=coalesce(v_customer.neighborhood_id,v_last_neighborhood_id,public.resolve_petatoe_customer_neighborhood(p_customer_id)); select n.name into v_name from public.installation_neighborhoods n where n.id=v_resolved; select jsonb_build_object('neighborhood_id',v_resolved,'neighborhood_name',coalesce(v_name,''),'google_maps_url',coalesce(nullif(v_customer.google_maps_url,''),v_last_map_url,''),'address',coalesce(v_customer.address,''),'last_request_id',v_request_id,'animals',coalesce((select jsonb_agg(jsonb_build_object('pet_name',a.pet_name,'pet_type',a.pet_type,'breed',a.breed,'pet_size',a.pet_size,'quantity',a.quantity) order by a.display_order) from public.installation_request_animals a where a.installation_request_id=v_request_id),'[]'::jsonb),'collection',coalesce((select jsonb_build_object('amount_collected',x.amount_collected,'collection_status',x.collection_status,'payment_method',x.payment_method,'appointment_status',x.appointment_status) from public.installation_request_collection x where x.installation_request_id=v_request_id),'{}'::jsonb)) into v_result; return coalesce(v_result,'{}'::jsonb); end $$;
revoke all on function public.get_customer_appointment_defaults(uuid) from public,anon; grant execute on function public.get_customer_appointment_defaults(uuid) to authenticated,service_role; notify pgrst,'reload schema'; commit;
select count(*)::bigint unresolved_customer_neighborhoods from public.customers c where c.neighborhood_id is null and nullif(btrim(coalesce(c.address,'')),'') is not null;
select c.customer_number code,c.customer_name name,c.address,public.petatoe_neighborhood_key(c.address) normalized_address from public.customers c where c.neighborhood_id is null and nullif(btrim(coalesce(c.address,'')),'') is not null order by c.customer_number limit 100;
