-- R44R32 — CRM L2-B Daily Operations / Daily Tasks / Daily Performance localization
-- Non-destructive seed for the canonical public.app_translations owner.
-- Existing customized ar_text/en_text values are preserved; only blank translations are filled.

begin;

with translation_seed(translation_key,screen_key,module_name,text_type,ar_text,en_text,default_ar,default_en,is_active,updated_at) as (
values
  ('dailyOperations.page.title','dailyOperations','crm','title','إدارة المهام اليومية','Daily Operations','إدارة المهام اليومية','Daily Operations',true,now()),
  ('dailyOperations.page.subtitle','dailyOperations','crm','subtitle','مركز التشغيل اليومي للمندوبين','Daily operations center for sales representatives','مركز التشغيل اليومي للمندوبين','Daily operations center for sales representatives',true,now()),
  ('dailyOperations.phoneLookup.title','dailyOperations','crm','title','التحقق من رقم العميل','Customer Number Check','التحقق من رقم العميل','Customer Number Check',true,now()),
  ('dailyOperations.phoneLookup.note','dailyOperations','crm','help','اكتب رقم الجوال لمعرفة العميل والمندوب المرتبط به قبل التواصل أو الإضافة.','Enter the mobile number to identify the customer and assigned representative before contacting or adding.','اكتب رقم الجوال لمعرفة العميل والمندوب المرتبط به قبل التواصل أو الإضافة.','Enter the mobile number to identify the customer and assigned representative before contacting or adding.',true,now()),
  ('dailyOperations.phoneLookup.phone','dailyOperations','crm','label','رقم الجوال','Mobile Number','رقم الجوال','Mobile Number',true,now()),
  ('dailyOperations.phoneLookup.search','dailyOperations','crm','button','بحث','Search','بحث','Search',true,now()),
  ('dailyOperations.phoneLookup.searching','dailyOperations','crm','status','جاري البحث...','Searching...','جاري البحث...','Searching...',true,now()),
  ('dailyOperations.phoneLookup.invalid','dailyOperations','crm','error','أدخل رقم جوال سعودي صحيحًا بصيغة 05XXXXXXXX.','Enter a valid Saudi mobile number in the format 05XXXXXXXX.','أدخل رقم جوال سعودي صحيحًا بصيغة 05XXXXXXXX.','Enter a valid Saudi mobile number in the format 05XXXXXXXX.',true,now()),
  ('dailyOperations.phoneLookup.notLinked','dailyOperations','crm','status','الرقم {phone} غير مرتبط بأي عميل مسجل.','Number {phone} is not linked to any registered customer.','الرقم {phone} غير مرتبط بأي عميل مسجل.','Number {phone} is not linked to any registered customer.',true,now()),
  ('dailyOperations.phoneLookup.assignedRep','dailyOperations','crm','status','العميل يتبع المندوب «{name}».','Customer is assigned to representative “{name}”.','العميل يتبع المندوب «{name}».','Customer is assigned to representative “{name}”.',true,now()),
  ('dailyOperations.phoneLookup.noRep','dailyOperations','crm','status','لم يتم تعيين مندوب لهذا العميل حتى الآن.','No representative has been assigned to this customer yet.','لم يتم تعيين مندوب لهذا العميل حتى الآن.','No representative has been assigned to this customer yet.',true,now()),
  ('dailyOperations.phoneLookup.contactPerson','dailyOperations','crm','label','المسؤول: «{name}».','Contact person: “{name}”.','المسؤول: «{name}».','Contact person: “{name}”.',true,now()),
  ('dailyOperations.phoneLookup.outOfScope','dailyOperations','crm','error','هذا العميل خارج نطاق البيانات المسموح لك بالوصول إليه، لذلك لا يمكنك استعراض بياناته.','This customer is outside your permitted data scope, so you cannot view their details.','هذا العميل خارج نطاق البيانات المسموح لك بالوصول إليه، لذلك لا يمكنك استعراض بياناته.','This customer is outside your permitted data scope, so you cannot view their details.',true,now()),
  ('dailyOperations.phoneLookup.linkedWarning','dailyOperations','crm','status','تنبيه: الرقم {phone} مرتبط بالعميل «{name}».','Notice: number {phone} is linked to customer “{name}”.','تنبيه: الرقم {phone} مرتبط بالعميل «{name}».','Notice: number {phone} is linked to customer “{name}”.',true,now()),
  ('dailyOperations.phoneLookup.openCustomer','dailyOperations','crm','button','فتح العميل الحالي','Open Existing Customer','فتح العميل الحالي','Open Existing Customer',true,now()),
  ('dailyOperations.phoneLookup.error','dailyOperations','crm','error','تعذر التحقق من رقم الجوال.','Unable to verify the mobile number.','تعذر التحقق من رقم الجوال.','Unable to verify the mobile number.',true,now()),
  ('dailyOperations.header.title','dailyOperations','crm','title','مركز التشغيل اليومي','Daily Operations Center','مركز التشغيل اليومي','Daily Operations Center',true,now()),
  ('dailyOperations.header.note','dailyOperations','crm','help','المهام والمتابعات والعملاء المطلوب إنجازهم خلال اليوم.','Tasks, follow-ups, and customers that need action today.','المهام والمتابعات والعملاء المطلوب إنجازهم خلال اليوم.','Tasks, follow-ups, and customers that need action today.',true,now()),
  ('dailyOperations.workDate','dailyOperations','crm','label','تاريخ العمل','Work Date','تاريخ العمل','Work Date',true,now()),
  ('dailyOperations.session.current','dailyOperations','crm','label','جلسة العمل الحالية','Current Work Session','جلسة العمل الحالية','Current Work Session',true,now()),
  ('dailyOperations.session.checking','dailyOperations','crm','status','جاري التحقق...','Checking...','جاري التحقق...','Checking...',true,now()),
  ('dailyOperations.session.end','dailyOperations','crm','button','إنهاء يوم العمل','End Work Day','إنهاء يوم العمل','End Work Day',true,now()),
  ('dailyOperations.session.endConfirm','dailyOperations','crm','confirm','هل تريد إنهاء يوم العمل الحالي؟','End the current work day?','هل تريد إنهاء يوم العمل الحالي؟','End the current work day?',true,now()),
  ('dailyOperations.session.ended','dailyOperations','crm','status','تم تسجيل إنهاء يوم العمل.','Work day end was recorded.','تم تسجيل إنهاء يوم العمل.','Work day end was recorded.',true,now()),
  ('dailyOperations.session.endError','dailyOperations','crm','error','تعذر إنهاء يوم العمل.','Unable to end the work day.','تعذر إنهاء يوم العمل.','Unable to end the work day.',true,now()),
  ('dailyOperations.kpi.newCustomers','dailyOperations','crm','label','العملاء الجدد اليوم','New Customers Today','العملاء الجدد اليوم','New Customers Today',true,now()),
  ('dailyOperations.kpi.completedFollowups','dailyOperations','crm','label','المتابعات المنفذة اليوم','Completed Follow-ups Today','المتابعات المنفذة اليوم','Completed Follow-ups Today',true,now()),
  ('dailyOperations.kpi.quotations','dailyOperations','crm','label','عقود العملاء اليوم','Customer Contracts Today','عقود العملاء اليوم','Customer Contracts Today',true,now()),
  ('dailyOperations.kpi.overdue','dailyOperations','crm','label','المتابعات المتأخرة','Overdue Follow-ups','المتابعات المتأخرة','Overdue Follow-ups',true,now()),
  ('dailyOperations.kpi.urgent','dailyOperations','crm','help','تحتاج إجراءً فوريًا','Requires immediate action','تحتاج إجراءً فوريًا','Requires immediate action',true,now()),
  ('dailyOperations.suggested.title','dailyOperations','crm','title','العملاء المقترح التواصل معهم','Suggested Customers to Contact','العملاء المقترح التواصل معهم','Suggested Customers to Contact',true,now()),
  ('dailyOperations.whatsapp.title','dailyOperations','crm','title','إعداد رسالة واتساب الشخصية','Personal WhatsApp Message Setup','إعداد رسالة واتساب الشخصية','Personal WhatsApp Message Setup',true,now()),
  ('dailyOperations.whatsapp.note','dailyOperations','crm','help','تُحفظ الرسالة والصورة لحسابك فقط وتُستخدم مع العملاء المقترح التواصل معهم.','The message and image are saved only for your account and used with suggested customers.','تُحفظ الرسالة والصورة لحسابك فقط وتُستخدم مع العملاء المقترح التواصل معهم.','The message and image are saved only for your account and used with suggested customers.',true,now()),
  ('dailyOperations.whatsapp.loading','dailyOperations','crm','status','جارٍ التحميل...','Loading...','جارٍ التحميل...','Loading...',true,now()),
  ('dailyOperations.whatsapp.defaultMessage','dailyOperations','crm','label','الرسالة الافتراضية','Default Message','الرسالة الافتراضية','Default Message',true,now()),
  ('dailyOperations.whatsapp.messagePlaceholder','dailyOperations','crm','placeholder','اكتب الرسالة التي تريد تجهيزها عند التواصل عبر واتساب...','Enter the message to prepare when contacting customers via WhatsApp...','اكتب الرسالة التي تريد تجهيزها عند التواصل عبر واتساب...','Enter the message to prepare when contacting customers via WhatsApp...',true,now()),
  ('dailyOperations.whatsapp.characters','dailyOperations','crm','label','حرف','characters','حرف','characters',true,now()),
  ('dailyOperations.whatsapp.defaultImage','dailyOperations','crm','label','الصورة الافتراضية','Default Image','الصورة الافتراضية','Default Image',true,now()),
  ('dailyOperations.whatsapp.chooseImage','dailyOperations','crm','button','اختيار صورة','Choose Image','اختيار صورة','Choose Image',true,now()),
  ('dailyOperations.whatsapp.previewAlt','dailyOperations','crm','alt','معاينة صورة رسالة واتساب','WhatsApp message image preview','معاينة صورة رسالة واتساب','WhatsApp message image preview',true,now()),
  ('dailyOperations.whatsapp.imageConstraints','dailyOperations','crm','help','JPG أو PNG أو WEBP، بحد أقصى 5 ميجابايت.','JPG, PNG, or WEBP, up to 5 MB.','JPG أو PNG أو WEBP، بحد أقصى 5 ميجابايت.','JPG, PNG, or WEBP, up to 5 MB.',true,now()),
  ('dailyOperations.whatsapp.removeImage','dailyOperations','crm','button','حذف الصورة','Remove Image','حذف الصورة','Remove Image',true,now()),
  ('dailyOperations.whatsapp.save','dailyOperations','crm','button','حفظ الإعداد','Save Setup','حفظ الإعداد','Save Setup',true,now()),
  ('dailyOperations.whatsapp.savedImageAlt','dailyOperations','crm','alt','صورة رسالة واتساب المحفوظة','Saved WhatsApp message image','صورة رسالة واتساب المحفوظة','Saved WhatsApp message image',true,now()),
  ('dailyOperations.whatsapp.savedImage','dailyOperations','crm','label','صورة محفوظة','Saved image','صورة محفوظة','Saved image',true,now()),
  ('dailyOperations.whatsapp.saved','dailyOperations','crm','status','الإعداد محفوظ لحسابك','Setup is saved to your account','الإعداد محفوظ لحسابك','Setup is saved to your account',true,now()),
  ('dailyOperations.whatsapp.loadError','dailyOperations','crm','error','تعذر تحميل الإعداد','Unable to load setup','تعذر تحميل الإعداد','Unable to load setup',true,now()),
  ('dailyOperations.whatsapp.saving','dailyOperations','crm','status','جارٍ الحفظ...','Saving...','جارٍ الحفظ...','Saving...',true,now()),
  ('dailyOperations.whatsapp.savedSuccess','dailyOperations','crm','status','تم حفظ الرسالة والصورة لحسابك','Message and image were saved to your account','تم حفظ الرسالة والصورة لحسابك','Message and image were saved to your account',true,now()),
  ('dailyOperations.whatsapp.imageTooLarge','dailyOperations','crm','error','حجم الصورة أكبر من 5 ميجابايت','Image size exceeds 5 MB','حجم الصورة أكبر من 5 ميجابايت','Image size exceeds 5 MB',true,now()),
  ('dailyOperations.whatsapp.invalidImage','dailyOperations','crm','error','صيغة الصورة غير مدعومة','Image format is not supported','صيغة الصورة غير مدعومة','Image format is not supported',true,now()),
  ('dailyOperations.whatsapp.messageTooLong','dailyOperations','crm','error','الرسالة أطول من الحد المسموح','Message exceeds the allowed length','الرسالة أطول من الحد المسموح','Message exceeds the allowed length',true,now()),
  ('dailyOperations.whatsapp.saveError','dailyOperations','crm','error','تعذر حفظ الإعداد','Unable to save setup','تعذر حفظ الإعداد','Unable to save setup',true,now()),
  ('dailyOperations.whatsapp.newImageReady','dailyOperations','crm','status','صورة جديدة جاهزة للحفظ','New image is ready to save','صورة جديدة جاهزة للحفظ','New image is ready to save',true,now()),
  ('dailyOperations.whatsapp.imageRemovePending','dailyOperations','crm','status','سيتم حذف الصورة عند الحفظ','Image will be removed when saved','سيتم حذف الصورة عند الحفظ','Image will be removed when saved',true,now()),
  ('dailyOperations.whatsapp.shareImageError','dailyOperations','crm','error','تعذرت مشاركة الصورة؛ استخدم زر واتساب للنص','Unable to share the image; use the WhatsApp text button','تعذرت مشاركة الصورة؛ استخدم زر واتساب للنص','Unable to share the image; use the WhatsApp text button',true,now()),
  ('dailyOperations.suggested.overall','dailyOperations','crm','label','إجمالي التواصل اليوم','Total Contacts Today','إجمالي التواصل اليوم','Total Contacts Today',true,now()),
  ('dailyOperations.suggested.loadingList','dailyOperations','crm','status','جارٍ تحميل قائمة اليوم...','Loading today’s list...','جارٍ تحميل قائمة اليوم...','Loading today’s list...',true,now()),
  ('dailyOperations.suggested.loadingCustomers','dailyOperations','crm','status','جارٍ تحميل العملاء المقترحين...','Loading suggested customers...','جارٍ تحميل العملاء المقترحين...','Loading suggested customers...',true,now()),
  ('dailyOperations.suggested.loadListError','dailyOperations','crm','error','تعذر تحميل قائمة اليوم','Unable to load today’s list','تعذر تحميل قائمة اليوم','Unable to load today’s list',true,now()),
  ('dailyOperations.suggested.loadErrorTitle','dailyOperations','crm','error','تعذر تحميل القائمة','Unable to load list','تعذر تحميل القائمة','Unable to load list',true,now()),
  ('dailyOperations.suggested.retry','dailyOperations','crm','button','إعادة المحاولة','Retry','إعادة المحاولة','Retry',true,now()),
  ('dailyOperations.suggested.summary','dailyOperations','crm','status','{completed} تم التواصل معهم، و{available} متاحون الآن','{completed} contacted; {available} available now','{completed} تم التواصل معهم، و{available} متاحون الآن','{completed} contacted; {available} available now',true,now()),
  ('dailyOperations.suggested.notContacted','dailyOperations','crm','status','لم يتم التواصل','Not contacted','لم يتم التواصل','Not contacted',true,now()),
  ('dailyOperations.suggested.addFollowup','dailyOperations','crm','button','إضافة متابعة','Add Follow-up','إضافة متابعة','Add Follow-up',true,now()),
  ('dailyOperations.suggested.contacted','dailyOperations','crm','button','تم التواصل','Contacted','تم التواصل','Contacted',true,now()),
  ('dailyOperations.suggested.whatsapp','dailyOperations','crm','button','واتساب','WhatsApp','واتساب','WhatsApp',true,now()),
  ('dailyOperations.suggested.emptyTitle','dailyOperations','crm','empty','لا يوجد عملاء مقترح التواصل معهم حاليًا','No suggested customers to contact right now','لا يوجد عملاء مقترح التواصل معهم حاليًا','No suggested customers to contact right now',true,now()),
  ('dailyOperations.suggested.emptyNote','dailyOperations','crm','help','أضف عملاء أو متابعات وسيتم تجهيز القائمة تلقائيًا.','Add customers or follow-ups and the list will be prepared automatically.','أضف عملاء أو متابعات وسيتم تجهيز القائمة تلقائيًا.','Add customers or follow-ups and the list will be prepared automatically.',true,now()),
  ('dailyOperations.suggested.serviceError','dailyOperations','crm','error','تعذر تحميل خدمة العملاء المقترحين.','Unable to load the suggested customers service.','تعذر تحميل خدمة العملاء المقترحين.','Unable to load the suggested customers service.',true,now()),
  ('dailyOperations.suggested.customersError','dailyOperations','crm','error','تعذر تحميل قائمة العملاء المقترحين.','Unable to load the suggested customers list.','تعذر تحميل قائمة العملاء المقترحين.','Unable to load the suggested customers list.',true,now()),
  ('dailyOperations.col.customerName','dailyOperations','crm','table','اسم العميل','Customer Name','اسم العميل','Customer Name',true,now()),
  ('dailyOperations.col.mobile','dailyOperations','crm','table','رقم الجوال','Mobile Number','رقم الجوال','Mobile Number',true,now()),
  ('dailyOperations.col.lastContact','dailyOperations','crm','table','آخر تواصل','Last Contact','آخر تواصل','Last Contact',true,now()),
  ('dailyOperations.col.lastContract','dailyOperations','crm','table','آخر عقد','Last Contract','آخر عقد','Last Contract',true,now()),
  ('dailyOperations.col.representative','dailyOperations','crm','table','المندوب','Representative','المندوب','Representative',true,now()),
  ('dailyOperations.col.actions','dailyOperations','crm','table','الإجراءات','Actions','الإجراءات','Actions',true,now()),
  ('dailyOperations.col.customer','dailyOperations','crm','table','العميل','Customer','العميل','Customer',true,now()),
  ('dailyOperations.col.method','dailyOperations','crm','table','طريقة التواصل','Contact Method','طريقة التواصل','Contact Method',true,now()),
  ('dailyOperations.col.result','dailyOperations','crm','table','النتيجة','Result','النتيجة','Result',true,now()),
  ('dailyOperations.col.nextFollowup','dailyOperations','crm','table','المتابعة القادمة','Next Follow-up','المتابعة القادمة','Next Follow-up',true,now()),
  ('dailyOperations.col.addedAt','dailyOperations','crm','table','وقت الإضافة','Added At','وقت الإضافة','Added At',true,now()),
  ('dailyOperations.col.contractNumber','dailyOperations','crm','table','رقم العقد','Contract Number','رقم العقد','Contract Number',true,now()),
  ('dailyOperations.col.status','dailyOperations','crm','table','الحالة','Status','الحالة','Status',true,now()),
  ('dailyOperations.col.value','dailyOperations','crm','table','القيمة','Value','القيمة','Value',true,now()),
  ('dailyOperations.col.appointment','dailyOperations','crm','table','الموعد','Due Date','الموعد','Due Date',true,now()),
  ('dailyOperations.col.delay','dailyOperations','crm','table','التأخير','Delay','التأخير','Delay',true,now()),
  ('dailyOperations.col.previousResult','dailyOperations','crm','table','النتيجة السابقة','Previous Result','النتيجة السابقة','Previous Result',true,now()),
  ('dailyOperations.section.followupsTitle','dailyOperations','crm','title','المتابعات المنفذة اليوم','Completed Follow-ups Today','المتابعات المنفذة اليوم','Completed Follow-ups Today',true,now()),
  ('dailyOperations.section.followupsNote','dailyOperations','crm','help','العملاء الذين تم تسجيل متابعة لهم خلال اليوم.','Customers with follow-ups recorded today.','العملاء الذين تم تسجيل متابعة لهم خلال اليوم.','Customers with follow-ups recorded today.',true,now()),
  ('dailyOperations.section.openFollowups','dailyOperations','crm','button','فتح المتابعات','Open Follow-ups','فتح المتابعات','Open Follow-ups',true,now()),
  ('dailyOperations.section.customersTitle','dailyOperations','crm','title','العملاء الجدد اليوم','New Customers Today','العملاء الجدد اليوم','New Customers Today',true,now()),
  ('dailyOperations.section.customersNote','dailyOperations','crm','help','العملاء الذين تمت إضافتهم إلى النظام خلال اليوم.','Customers added to the system today.','العملاء الذين تمت إضافتهم إلى النظام خلال اليوم.','Customers added to the system today.',true,now()),
  ('dailyOperations.section.openCustomers','dailyOperations','crm','button','فتح العملاء','Open Customers','فتح العملاء','Open Customers',true,now()),
  ('dailyOperations.section.quotationsTitle','dailyOperations','crm','title','عقود العملاء اليوم','Customer Contracts Today','عقود العملاء اليوم','Customer Contracts Today',true,now()),
  ('dailyOperations.section.quotationsNote','dailyOperations','crm','help','العروض التي تم إنشاؤها خلال يوم العمل الحالي.','Contracts created during the current work day.','العروض التي تم إنشاؤها خلال يوم العمل الحالي.','Contracts created during the current work day.',true,now()),
  ('dailyOperations.section.openQuotations','dailyOperations','crm','button','فتح عقود العملاء','Open Customer Contracts','فتح عقود العملاء','Open Customer Contracts',true,now()),
  ('dailyOperations.section.overdueTitle','dailyOperations','crm','title','المتابعات المتأخرة','Overdue Follow-ups','المتابعات المتأخرة','Overdue Follow-ups',true,now()),
  ('dailyOperations.section.overdueNote','dailyOperations','crm','help','مواعيد متابعة لم تُغلق وتجاوزت تاريخها.','Open follow-ups that are past their due date.','مواعيد متابعة لم تُغلق وتجاوزت تاريخها.','Open follow-ups that are past their due date.',true,now()),
  ('dailyOperations.section.handleOverdue','dailyOperations','crm','button','معالجة المتأخرات','Handle Overdue','معالجة المتأخرات','Handle Overdue',true,now()),
  ('dailyOperations.empty.followups','dailyOperations','crm','empty','لم يتم تسجيل متابعات اليوم حتى الآن.','No follow-ups have been recorded today.','لم يتم تسجيل متابعات اليوم حتى الآن.','No follow-ups have been recorded today.',true,now()),
  ('dailyOperations.empty.customers','dailyOperations','crm','empty','لا يوجد عملاء جدد مضافون اليوم.','No new customers were added today.','لا يوجد عملاء جدد مضافون اليوم.','No new customers were added today.',true,now()),
  ('dailyOperations.empty.quotations','dailyOperations','crm','empty','لا توجد عروض أسعار منشأة اليوم.','No customer contracts were created today.','لا توجد عروض أسعار منشأة اليوم.','No customer contracts were created today.',true,now()),
  ('dailyOperations.empty.overdue','dailyOperations','crm','empty','لا توجد متابعات متأخرة. ممتاز!','No overdue follow-ups. Great!','لا توجد متابعات متأخرة. ممتاز!','No overdue follow-ups. Great!',true,now()),
  ('dailyOperations.delay.days','dailyOperations','crm','label','{count} يوم','{count} day(s)','{count} يوم','{count} day(s)',true,now()),
  ('dailyOperations.status.loading','dailyOperations','crm','status','جاري تحميل مركز التشغيل اليومي...','Loading daily operations center...','جاري تحميل مركز التشغيل اليومي...','Loading daily operations center...',true,now()),
  ('dailyOperations.error.permission','dailyOperations','crm','error','لا توجد صلاحية لعرض إدارة المهام اليومية.','You do not have permission to view Daily Operations.','لا توجد صلاحية لعرض إدارة المهام اليومية.','You do not have permission to view Daily Operations.',true,now()),
  ('dailyOperations.error.load','dailyOperations','crm','error','تعذر تحميل بيانات مركز التشغيل اليومي.','Unable to load daily operations center data.','تعذر تحميل بيانات مركز التشغيل اليومي.','Unable to load daily operations center data.',true,now()),
  ('dailyOperations.task.permission','dailyOperations','crm','error','لا تملك صلاحية تغيير هذه المهمة.','You do not have permission to change this task.','لا تملك صلاحية تغيير هذه المهمة.','You do not have permission to change this task.',true,now()),
  ('dailyOperations.task.saving','dailyOperations','crm','status','جاري حفظ حالة المهمة...','Saving task status...','جاري حفظ حالة المهمة...','Saving task status...',true,now()),
  ('dailyOperations.task.completed','dailyOperations','crm','status','تم تسجيل تنفيذ المهمة بنجاح.','Task completion recorded successfully.','تم تسجيل تنفيذ المهمة بنجاح.','Task completion recorded successfully.',true,now()),
  ('dailyOperations.task.reopened','dailyOperations','crm','status','تمت إعادة فتح المهمة.','Task reopened.','تمت إعادة فتح المهمة.','Task reopened.',true,now()),
  ('dailyOperations.task.saveError','dailyOperations','crm','error','تعذر حفظ المهمة.','Unable to save the task.','تعذر حفظ المهمة.','Unable to save the task.',true,now()),
  ('dailyOperations.task.notRequired','dailyOperations','crm','status','غير مطلوب','Not required','غير مطلوب','Not required',true,now()),
  ('dailyOperations.task.notSubject','dailyOperations','crm','status','غير خاضع للمهام','Not assigned daily tasks','غير خاضع للمهام','Not assigned daily tasks',true,now()),
  ('dailyOperations.task.noneRequired','dailyOperations','crm','empty','لا توجد مهام يومية مطلوبة من حسابك وفق إعدادات الإدارة.','No daily tasks are required for your account based on management settings.','لا توجد مهام يومية مطلوبة من حسابك وفق إعدادات الإدارة.','No daily tasks are required for your account based on management settings.',true,now()),
  ('dailyOperations.task.editableCount','dailyOperations','crm','status','مصرح بـ {count} مهمة','Can update {count} task(s)','مصرح بـ {count} مهمة','Can update {count} task(s)',true,now()),
  ('dailyOperations.task.readOnly','dailyOperations','crm','status','عرض فقط','View only','عرض فقط','View only',true,now()),
  ('dailyOperations.task.completedPrefix','dailyOperations','crm','status','تم {task}','Completed: {task}','تم {task}','Completed: {task}',true,now()),
  ('dailyOperations.task.completedBy','dailyOperations','crm','status','تم بواسطة {name} في {time}','Completed by {name} at {time}','تم بواسطة {name} في {time}','Completed by {name} at {time}',true,now()),
  ('dailyOperations.task.currentUser','dailyOperations','crm','label','المستخدم الحالي','Current user','المستخدم الحالي','Current user',true,now()),
  ('dailyOperations.task.markAfter','dailyOperations','crm','help','حدد المهمة بعد التنفيذ.','Mark the task after completion.','حدد المهمة بعد التنفيذ.','Mark the task after completion.',true,now()),
  ('dailyOperations.task.done','dailyOperations','crm','status','تم التنفيذ','Completed','تم التنفيذ','Completed',true,now()),
  ('dailyOperations.task.notDone','dailyOperations','crm','status','لم يتم التنفيذ','Not completed','لم يتم التنفيذ','Not completed',true,now()),
  ('dailyOperations.task.noneActive','dailyOperations','crm','empty','لا توجد مهام يومية مفعلة.','No active daily tasks.','لا توجد مهام يومية مفعلة.','No active daily tasks.',true,now()),
  ('dailyOperations.targets.target','dailyOperations','crm','label','الهدف: {count}','Target: {count}','الهدف: {count}','Target: {count}',true,now()),
  ('dailyOperations.targets.saved','dailyOperations','crm','status','تم حفظ الأهداف اليومية.','Daily targets saved.','تم حفظ الأهداف اليومية.','Daily targets saved.',true,now()),
  ('dailyOperations.targets.saveError','dailyOperations','crm','error','تعذر حفظ الأهداف.','Unable to save daily targets.','تعذر حفظ الأهداف.','Unable to save daily targets.',true,now()),
  ('dailyPerformance.page.title','dailyPerformanceReport','crm','title','تقرير الأداء اليومي','Daily Performance Report','تقرير الأداء اليومي','Daily Performance Report',true,now()),
  ('dailyPerformance.page.subtitle','dailyPerformanceReport','crm','subtitle','متابعة تنفيذ المهام والنشاط اليومي لكل موظف ومندوب.','Track task execution and daily activity for each employee and representative.','متابعة تنفيذ المهام والنشاط اليومي لكل موظف ومندوب.','Track task execution and daily activity for each employee and representative.',true,now()),
  ('dailyPerformance.action.refresh','dailyPerformanceReport','crm','button','تحديث التقرير','Refresh Report','تحديث التقرير','Refresh Report',true,now()),
  ('dailyPerformance.action.exportPdf','dailyPerformanceReport','crm','button','تصدير PDF','Export PDF','تصدير PDF','Export PDF',true,now()),
  ('dailyPerformance.action.sendWhatsappPdf','dailyPerformanceReport','crm','button','إرسال التقرير واتساب PDF','Send Report via WhatsApp PDF','إرسال التقرير واتساب PDF','Send Report via WhatsApp PDF',true,now()),
  ('dailyPerformance.filter.date','dailyPerformanceReport','crm','label','تاريخ التقرير','Report Date','تاريخ التقرير','Report Date',true,now()),
  ('dailyPerformance.filter.employee','dailyPerformanceReport','crm','label','الموظف / المندوب','Employee / Representative','الموظف / المندوب','Employee / Representative',true,now()),
  ('dailyPerformance.filter.allEmployees','dailyPerformanceReport','crm','option','كل الموظفين','All Employees','كل الموظفين','All Employees',true,now()),
  ('dailyPerformance.filter.chooseEmployee','dailyPerformanceReport','crm','option','اختر الموظف','Choose Employee','اختر الموظف','Choose Employee',true,now()),
  ('dailyPerformance.filter.reset','dailyPerformanceReport','crm','button','إعادة التعيين','Reset','إعادة التعيين','Reset',true,now()),
  ('dailyPerformance.manager.label','dailyPerformanceReport','crm','label','ملاحظة المدير','Manager Note','ملاحظة المدير','Manager Note',true,now()),
  ('dailyPerformance.manager.noneTitle','dailyPerformanceReport','crm','empty','لا توجد ملاحظة.','No note.','لا توجد ملاحظة.','No note.',true,now()),
  ('dailyPerformance.manager.noneText','dailyPerformanceReport','crm','empty','لم يتم تسجيل توجيه لهذا اليوم.','No guidance was recorded for this day.','لم يتم تسجيل توجيه لهذا اليوم.','No guidance was recorded for this day.',true,now()),
  ('dailyPerformance.kpi.employees','dailyPerformanceReport','crm','label','إجمالي الموظفين','Total Employees','إجمالي الموظفين','Total Employees',true,now()),
  ('dailyPerformance.kpi.included','dailyPerformanceReport','crm','help','المشمولون في التقرير','Included in report','المشمولون في التقرير','Included in report',true,now()),
  ('dailyPerformance.kpi.checklist','dailyPerformanceReport','crm','label','إنجاز الـChecklist','Checklist Completion','إنجاز الـChecklist','Checklist Completion',true,now()),
  ('dailyPerformance.kpi.completedOf','dailyPerformanceReport','crm','status','{completed} من {total}','{completed} of {total}','{completed} من {total}','{completed} of {total}',true,now()),
  ('dailyPerformance.kpi.customersMet','dailyPerformanceReport','crm','label','حققوا هدف العملاء','Met Customer Target','حققوا هدف العملاء','Met Customer Target',true,now()),
  ('dailyPerformance.kpi.followupsMet','dailyPerformanceReport','crm','label','حققوا هدف المتابعات','Met Follow-up Target','حققوا هدف المتابعات','Met Follow-up Target',true,now()),
  ('dailyPerformance.kpi.quotationsMet','dailyPerformanceReport','crm','label','حققوا هدف العروض','Met Contract Target','حققوا هدف العروض','Met Contract Target',true,now()),
  ('dailyPerformance.kpi.targetEmployeeRate','dailyPerformanceReport','crm','status','{rate}% من الموظفين الخاضعين للأهداف','{rate}% of employees assigned targets','{rate}% من الموظفين الخاضعين للأهداف','{rate}% of employees assigned targets',true,now()),
  ('dailyPerformance.kpi.overdue','dailyPerformanceReport','crm','label','المتابعات المتأخرة','Overdue Follow-ups','المتابعات المتأخرة','Overdue Follow-ups',true,now()),
  ('dailyPerformance.kpi.needsAction','dailyPerformanceReport','crm','help','تحتاج معالجة','Needs action','تحتاج معالجة','Needs action',true,now()),
  ('dailyPerformance.ranking.title','dailyPerformanceReport','crm','title','الترتيب اليومي للموظفين','Daily Employee Ranking','الترتيب اليومي للموظفين','Daily Employee Ranking',true,now()),
  ('dailyPerformance.ranking.note','dailyPerformanceReport','crm','help','درجة الأداء مبنية على تنفيذ المهمة والنشاط المسجل خلال اليوم.','Performance score is based on task completion and activity recorded during the day.','درجة الأداء مبنية على تنفيذ المهمة والنشاط المسجل خلال اليوم.','Performance score is based on task completion and activity recorded during the day.',true,now()),
  ('dailyPerformance.ranking.summary','dailyPerformanceReport','crm','status','{tasks} مهام · {followups} متابعة · {customers} عميل · {quotations} عرض','{tasks} tasks · {followups} follow-ups · {customers} customers · {quotations} contracts','{tasks} مهام · {followups} متابعة · {customers} عميل · {quotations} عرض','{tasks} tasks · {followups} follow-ups · {customers} customers · {quotations} contracts',true,now()),
  ('dailyPerformance.ranking.points','dailyPerformanceReport','crm','label','نقطة','points','نقطة','points',true,now()),
  ('dailyPerformance.ranking.empty','dailyPerformanceReport','crm','empty','لا توجد بيانات موظفين.','No employee data.','لا توجد بيانات موظفين.','No employee data.',true,now()),
  ('dailyPerformance.summary.title','dailyPerformanceReport','crm','title','التقرير الإجمالي','Overall Report','التقرير الإجمالي','Overall Report',true,now()),
  ('dailyPerformance.summary.note','dailyPerformanceReport','crm','help','ملخص حالة كل موظف في جميع مؤشرات اليوم.','Summary of each employee across all daily indicators.','ملخص حالة كل موظف في جميع مؤشرات اليوم.','Summary of each employee across all daily indicators.',true,now()),
  ('dailyPerformance.col.rank','dailyPerformanceReport','crm','table','الترتيب','Rank','الترتيب','Rank',true,now()),
  ('dailyPerformance.col.employee','dailyPerformanceReport','crm','table','الموظف','Employee','الموظف','Employee',true,now()),
  ('dailyPerformance.col.tasks','dailyPerformanceReport','crm','table','المهام اليومية','Daily Tasks','المهام اليومية','Daily Tasks',true,now()),
  ('dailyPerformance.col.newCustomers','dailyPerformanceReport','crm','table','عملاء جدد','New Customers','عملاء جدد','New Customers',true,now()),
  ('dailyPerformance.col.followups','dailyPerformanceReport','crm','table','متابعات','Follow-ups','متابعات','Follow-ups',true,now()),
  ('dailyPerformance.col.quotations','dailyPerformanceReport','crm','table','عروض أسعار','Contracts','عروض أسعار','Contracts',true,now()),
  ('dailyPerformance.col.targets','dailyPerformanceReport','crm','table','تحقيق الأهداف','Target Achievement','تحقيق الأهداف','Target Achievement',true,now()),
  ('dailyPerformance.col.overdue','dailyPerformanceReport','crm','table','متأخرات','Overdue','متأخرات','Overdue',true,now()),
  ('dailyPerformance.col.completion','dailyPerformanceReport','crm','table','الإنجاز','Completion','الإنجاز','Completion',true,now()),
  ('dailyPerformance.col.points','dailyPerformanceReport','crm','table','النقاط','Points','النقاط','Points',true,now()),
  ('dailyPerformance.col.customer','dailyPerformanceReport','crm','table','العميل','Customer','العميل','Customer',true,now()),
  ('dailyPerformance.col.method','dailyPerformanceReport','crm','table','الطريقة','Method','الطريقة','Method',true,now()),
  ('dailyPerformance.col.result','dailyPerformanceReport','crm','table','النتيجة','Result','النتيجة','Result',true,now()),
  ('dailyPerformance.col.nextAppointment','dailyPerformanceReport','crm','table','الموعد القادم','Next Follow-up','الموعد القادم','Next Follow-up',true,now()),
  ('dailyPerformance.col.classification','dailyPerformanceReport','crm','table','التصنيف','Classification','التصنيف','Classification',true,now()),
  ('dailyPerformance.col.contactPerson','dailyPerformanceReport','crm','table','اسم المسؤول','Contact Person','اسم المسؤول','Contact Person',true,now()),
  ('dailyPerformance.col.addedAt','dailyPerformanceReport','crm','table','وقت الإضافة','Added At','وقت الإضافة','Added At',true,now()),
  ('dailyPerformance.col.contractNumber','dailyPerformanceReport','crm','table','رقم العقد','Contract Number','رقم العقد','Contract Number',true,now()),
  ('dailyPerformance.col.status','dailyPerformanceReport','crm','table','الحالة','Status','الحالة','Status',true,now()),
  ('dailyPerformance.col.value','dailyPerformanceReport','crm','table','القيمة','Value','القيمة','Value',true,now()),
  ('dailyPerformance.col.followupDate','dailyPerformanceReport','crm','table','موعد المتابعة','Follow-up Date','موعد المتابعة','Follow-up Date',true,now()),
  ('dailyPerformance.col.previousResult','dailyPerformanceReport','crm','table','النتيجة السابقة','Previous Result','النتيجة السابقة','Previous Result',true,now()),
  ('dailyPerformance.status.overdue','dailyPerformanceReport','crm','status','متأخرة','Overdue','متأخرة','Overdue',true,now()),
  ('dailyPerformance.status.updated','dailyPerformanceReport','crm','status','تم التحديث','Updated','تم التحديث','Updated',true,now()),
  ('dailyPerformance.status.notUpdated','dailyPerformanceReport','crm','status','لم يتم التحديث','Not Updated','لم يتم التحديث','Not Updated',true,now()),
  ('dailyPerformance.status.loading','dailyPerformanceReport','crm','status','جاري تحميل تقرير الأداء اليومي...','Loading daily performance report...','جاري تحميل تقرير الأداء اليومي...','Loading daily performance report...',true,now()),
  ('dailyPerformance.status.updatedAt','dailyPerformanceReport','crm','status','تم تحديث التقرير في {time}.','Report updated at {time}.','تم تحديث التقرير في {time}.','Report updated at {time}.',true,now()),
  ('dailyPerformance.error.load','dailyPerformanceReport','crm','error','تعذر تحميل تقرير الأداء اليومي.','Unable to load daily performance report.','تعذر تحميل تقرير الأداء اليومي.','Unable to load daily performance report.',true,now()),
  ('dailyPerformance.empty.noData','dailyPerformanceReport','crm','empty','لا توجد بيانات.','No data.','لا توجد بيانات.','No data.',true,now()),
  ('dailyPerformance.empty.report','dailyPerformanceReport','crm','empty','لا توجد بيانات في هذا التقرير.','No data in this report.','لا توجد بيانات في هذا التقرير.','No data in this report.',true,now()),
  ('dailyPerformance.empty.filtered','dailyPerformanceReport','crm','empty','لا توجد بيانات مطابقة.','No matching data.','لا توجد بيانات مطابقة.','No matching data.',true,now()),
  ('dailyPerformance.detail.tasksTitle','dailyPerformanceReport','crm','title','المهام اليومية','Daily Tasks','المهام اليومية','Daily Tasks',true,now()),
  ('dailyPerformance.detail.tasksSubtitle','dailyPerformanceReport','crm','help','حالة تنفيذ كل مهمة لكل موظف.','Completion status of each task for each employee.','حالة تنفيذ كل مهمة لكل موظف.','Completion status of each task for each employee.',true,now()),
  ('dailyPerformance.detail.targetsTitle','dailyPerformanceReport','crm','title','تحقيق الأهداف','Target Achievement','تحقيق الأهداف','Target Achievement',true,now()),
  ('dailyPerformance.detail.targetsSubtitle','dailyPerformanceReport','crm','help','مقارنة النشاط الفعلي بالأهداف اليومية.','Compare actual activity with daily targets.','مقارنة النشاط الفعلي بالأهداف اليومية.','Compare actual activity with daily targets.',true,now()),
  ('dailyPerformance.detail.followupsTitle','dailyPerformanceReport','crm','title','المتابعات اليومية','Daily Follow-ups','المتابعات اليومية','Daily Follow-ups',true,now()),
  ('dailyPerformance.detail.followupsSubtitle','dailyPerformanceReport','crm','help','تفاصيل العملاء الذين تمت متابعتهم خلال اليوم.','Details of customers followed up during the day.','تفاصيل العملاء الذين تمت متابعتهم خلال اليوم.','Details of customers followed up during the day.',true,now()),
  ('dailyPerformance.detail.customersTitle','dailyPerformanceReport','crm','title','العملاء الجدد','New Customers','العملاء الجدد','New Customers',true,now()),
  ('dailyPerformance.detail.customersSubtitle','dailyPerformanceReport','crm','help','العملاء الذين تمت إضافتهم خلال اليوم.','Customers added during the day.','العملاء الذين تمت إضافتهم خلال اليوم.','Customers added during the day.',true,now()),
  ('dailyPerformance.detail.quotationsTitle','dailyPerformanceReport','crm','title','عقود العملاء','Customer Contracts','عقود العملاء','Customer Contracts',true,now()),
  ('dailyPerformance.detail.quotationsSubtitle','dailyPerformanceReport','crm','help','عقود العملاء التي تم إنشاؤها خلال اليوم.','Customer contracts created during the day.','عقود العملاء التي تم إنشاؤها خلال اليوم.','Customer contracts created during the day.',true,now()),
  ('dailyPerformance.detail.overdueTitle','dailyPerformanceReport','crm','title','المتابعات المتأخرة','Overdue Follow-ups','المتابعات المتأخرة','Overdue Follow-ups',true,now()),
  ('dailyPerformance.detail.overdueSubtitle','dailyPerformanceReport','crm','help','المتابعات غير المغلقة التي تجاوزت موعدها.','Open follow-ups that passed their due date.','المتابعات غير المغلقة التي تجاوزت موعدها.','Open follow-ups that passed their due date.',true,now()),
  ('dailyPerformance.detail.completedOfTasks','dailyPerformanceReport','crm','status','{completed} من {total} مهام','{completed} of {total} tasks','{completed} من {total} مهام','{completed} of {total} tasks',true,now()),
  ('dailyPerformance.detail.overallCompletion','dailyPerformanceReport','crm','status','{rate}% إنجاز كلي','{rate}% overall completion','{rate}% إنجاز كلي','{rate}% overall completion',true,now()),
  ('dailyPerformance.attendance.title','dailyPerformanceReport','crm','title','الحضور والنشاط اليومي','Daily Attendance & Activity','الحضور والنشاط اليومي','Daily Attendance & Activity',true,now()),
  ('dailyPerformance.attendance.note','dailyPerformanceReport','crm','help','أول نشاط وآخر نشاط وحالة العمل وعدد العمليات لكل موظف.','First activity, last activity, work status, and operation count for each employee.','أول نشاط وآخر نشاط وحالة العمل وعدد العمليات لكل موظف.','First activity, last activity, work status, and operation count for each employee.',true,now()),
  ('dailyPerformance.attendance.first','dailyPerformanceReport','crm','table','أول نشاط','First Activity','أول نشاط','First Activity',true,now()),
  ('dailyPerformance.attendance.last','dailyPerformanceReport','crm','table','آخر نشاط','Last Activity','آخر نشاط','Last Activity',true,now()),
  ('dailyPerformance.attendance.duration','dailyPerformanceReport','crm','table','مدة النشاط','Activity Duration','مدة النشاط','Activity Duration',true,now()),
  ('dailyPerformance.attendance.operations','dailyPerformanceReport','crm','table','العمليات','Operations','العمليات','Operations',true,now()),
  ('dailyPerformance.attendance.lastAction','dailyPerformanceReport','crm','table','آخر إجراء','Last Action','آخر إجراء','Last Action',true,now()),
  ('dailyPerformance.attendance.status','dailyPerformanceReport','crm','table','الحالة','Status','الحالة','Status',true,now()),
  ('dailyPerformance.attendance.notStarted','dailyPerformanceReport','crm','status','لم يبدأ اليوم','Not Started Today','لم يبدأ اليوم','Not Started Today',true,now()),
  ('dailyPerformance.attendance.ended','dailyPerformanceReport','crm','status','أنهى يومه','Ended Day','أنهى يومه','Ended Day',true,now()),
  ('dailyPerformance.attendance.active','dailyPerformanceReport','crm','status','نشط الآن','Active Now','نشط الآن','Active Now',true,now()),
  ('dailyPerformance.attendance.inactive','dailyPerformanceReport','crm','status','غير نشط','Inactive','غير نشط','Inactive',true,now()),
  ('dailyPerformance.attendance.minutes','dailyPerformanceReport','crm','status','{minutes} دقيقة','{minutes} min','{minutes} دقيقة','{minutes} min',true,now()),
  ('dailyPerformance.attendance.hoursMinutes','dailyPerformanceReport','crm','status','{hours} س {minutes} د','{hours} h {minutes} min','{hours} س {minutes} د','{hours} h {minutes} min',true,now()),
  ('dailyPerformance.attendance.empty','dailyPerformanceReport','crm','empty','لا توجد جلسات نشاط مسجلة لهذا اليوم.','No activity sessions were recorded for this day.','لا توجد جلسات نشاط مسجلة لهذا اليوم.','No activity sessions were recorded for this day.',true,now()),
  ('dailyPerformance.activity.title','dailyPerformanceReport','crm','title','خط سير يوم الموظف','Employee Daily Timeline','خط سير يوم الموظف','Employee Daily Timeline',true,now()),
  ('dailyPerformance.activity.note','dailyPerformanceReport','crm','help','تسلسل زمني موحد لأحداث العملاء والمتابعات والعروض والمهام والتنبيهات.','Unified timeline of customer, follow-up, contract, task, and alert events.','تسلسل زمني موحد لأحداث العملاء والمتابعات والعروض والمهام والتنبيهات.','Unified timeline of customer, follow-up, contract, task, and alert events.',true,now()),
  ('dailyPerformance.activity.type','dailyPerformanceReport','crm','label','نوع النشاط','Activity Type','نوع النشاط','Activity Type',true,now()),
  ('dailyPerformance.activity.all','dailyPerformanceReport','crm','option','كل الأنشطة','All Activities','كل الأنشطة','All Activities',true,now()),
  ('dailyPerformance.activity.session','dailyPerformanceReport','crm','option','الدخول والنشاط','Login & Activity','الدخول والنشاط','Login & Activity',true,now()),
  ('dailyPerformance.activity.customers','dailyPerformanceReport','crm','option','العملاء','Customers','العملاء','Customers',true,now()),
  ('dailyPerformance.activity.followups','dailyPerformanceReport','crm','option','المتابعات','Follow-ups','المتابعات','Follow-ups',true,now()),
  ('dailyPerformance.activity.quotations','dailyPerformanceReport','crm','option','عقود العملاء','Customer Contracts','عقود العملاء','Customer Contracts',true,now()),
  ('dailyPerformance.activity.installations','dailyPerformanceReport','crm','option','المواعيد','Appointments','المواعيد','Appointments',true,now()),
  ('dailyPerformance.activity.invoices','dailyPerformanceReport','crm','option','فواتير المبيعات','Sales Invoices','فواتير المبيعات','Sales Invoices',true,now()),
  ('dailyPerformance.activity.tasks','dailyPerformanceReport','crm','option','المهام اليومية','Daily Tasks','المهام اليومية','Daily Tasks',true,now()),
  ('dailyPerformance.activity.alerts','dailyPerformanceReport','crm','option','التنبيهات','Alerts','التنبيهات','Alerts',true,now()),
  ('dailyPerformance.activity.users','dailyPerformanceReport','crm','option','المستخدمون والصلاحيات','Users & Permissions','المستخدمون والصلاحيات','Users & Permissions',true,now()),
  ('dailyPerformance.activity.reference','dailyPerformanceReport','crm','option','البيانات المرجعية','Reference Data','البيانات المرجعية','Reference Data',true,now()),
  ('dailyPerformance.activity.other','dailyPerformanceReport','crm','option','أنشطة أخرى','Other Activities','أنشطة أخرى','Other Activities',true,now()),
  ('dailyPerformance.activity.show','dailyPerformanceReport','crm','button','عرض بيانات التقرير','Show Report Data','عرض بيانات التقرير','Show Report Data',true,now()),
  ('dailyPerformance.activity.exportPdf','dailyPerformanceReport','crm','button','تصدير خط السير PDF','Export Timeline PDF','تصدير خط السير PDF','Export Timeline PDF',true,now()),
  ('dailyPerformance.activity.sendWhatsapp','dailyPerformanceReport','crm','button','إرسال خط السير واتساب PDF','Send Timeline via WhatsApp PDF','إرسال خط السير واتساب PDF','Send Timeline via WhatsApp PDF',true,now()),
  ('dailyPerformance.activity.chooseEmployee','dailyPerformanceReport','crm','empty','اختر الموظف ثم اضغط عرض بيانات التقرير.','Choose an employee, then click Show Report Data.','اختر الموظف ثم اضغط عرض بيانات التقرير.','Choose an employee, then click Show Report Data.',true,now()),
  ('dailyPerformance.activity.empty','dailyPerformanceReport','crm','empty','لا توجد أنشطة مطابقة للفلاتر.','No activities match the filters.','لا توجد أنشطة مطابقة للفلاتر.','No activities match the filters.',true,now()),
  ('dailyPerformance.activity.generic','dailyPerformanceReport','crm','label','نشاط','Activity','نشاط','Activity',true,now()),
  ('dailyPerformance.activity.unknownEmployee','dailyPerformanceReport','crm','label','غير محدد','Unknown','غير محدد','Unknown',true,now()),
  ('dailyPerformance.activity.error','dailyPerformanceReport','crm','error','تعذر تحميل النشاط اليومي.','Unable to load daily activity.','تعذر تحميل النشاط اليومي.','Unable to load daily activity.',true,now()),
  ('dailyPerformance.activity.firstLast','dailyPerformanceReport','crm','status','أول نشاط {first} · آخر نشاط {last}','First activity {first} · last activity {last}','أول نشاط {first} · آخر نشاط {last}','First activity {first} · last activity {last}',true,now()),
  ('dailyPerformance.activity.noSession','dailyPerformanceReport','crm','status','لم يتم تسجيل جلسة اليوم بعد.','Today’s session has not been recorded yet.','لم يتم تسجيل جلسة اليوم بعد.','Today’s session has not been recorded yet.',true,now()),
  ('dailyPerformance.activity.loadSessionError','dailyPerformanceReport','crm','error','تعذر تحميل الجلسة','Unable to load session','تعذر تحميل الجلسة','Unable to load session',true,now()),
  ('dailyPerformance.alerts.title','dailyPerformanceReport','crm','title','تقرير التنبيهات اليومية','Daily Alerts Report','تقرير التنبيهات اليومية','Daily Alerts Report',true,now()),
  ('dailyPerformance.alerts.note','dailyPerformanceReport','crm','help','التنبيهات المفتوحة والمعالجة والمصعّدة لكل موظف.','Open, in-progress, and escalated alerts for each employee.','التنبيهات المفتوحة والمعالجة والمصعّدة لكل موظف.','Open, in-progress, and escalated alerts for each employee.',true,now()),
  ('dailyPerformance.alerts.open','dailyPerformanceReport','crm','status','مفتوح','Open','مفتوح','Open',true,now()),
  ('dailyPerformance.alerts.inProgress','dailyPerformanceReport','crm','status','قيد المعالجة','In Progress','قيد المعالجة','In Progress',true,now()),
  ('dailyPerformance.alerts.escalated','dailyPerformanceReport','crm','status','مصعّد','Escalated','مصعّد','Escalated',true,now()),
  ('dailyPerformance.alerts.closed','dailyPerformanceReport','crm','status','مغلق','Closed','مغلق','Closed',true,now()),
  ('dailyPerformance.alerts.critical','dailyPerformanceReport','crm','status','حرج','Critical','حرج','Critical',true,now()),
  ('dailyPerformance.alerts.normal','dailyPerformanceReport','crm','status','عادي','Normal','عادي','Normal',true,now()),
  ('dailyPerformance.alerts.important','dailyPerformanceReport','crm','status','مهم','Important','مهم','Important',true,now()),
  ('dailyPerformance.alerts.average','dailyPerformanceReport','crm','table','متوسط المعالجة','Avg. Resolution','متوسط المعالجة','Avg. Resolution',true,now()),
  ('dailyPerformance.alerts.noteLabel','dailyPerformanceReport','crm','label','ملاحظة المشرف:','Supervisor Note:','ملاحظة المشرف:','Supervisor Note:',true,now()),
  ('dailyPerformance.alerts.start','dailyPerformanceReport','crm','button','بدء المعالجة','Start','بدء المعالجة','Start',true,now()),
  ('dailyPerformance.alerts.escalate','dailyPerformanceReport','crm','button','تصعيد للمشرف','Escalate','تصعيد للمشرف','Escalate',true,now()),
  ('dailyPerformance.alerts.close','dailyPerformanceReport','crm','button','تمت المعالجة','Resolved','تمت المعالجة','Resolved',true,now()),
  ('dailyPerformance.alerts.reopen','dailyPerformanceReport','crm','button','إعادة فتح','Reopen','إعادة فتح','Reopen',true,now()),
  ('dailyPerformance.alerts.empty','dailyPerformanceReport','crm','empty','لا توجد تنبيهات مطابقة.','No matching alerts.','لا توجد تنبيهات مطابقة.','No matching alerts.',true,now()),
  ('dailyPerformance.alerts.loading','dailyPerformanceReport','crm','status','جاري تحميل التنبيهات...','Loading alerts...','جاري تحميل التنبيهات...','Loading alerts...',true,now()),
  ('dailyPerformance.alerts.loadError','dailyPerformanceReport','crm','error','تعذر تحميل التنبيهات.','Unable to load alerts.','تعذر تحميل التنبيهات.','Unable to load alerts.',true,now()),
  ('dailyPerformance.alerts.actionStart','dailyPerformanceReport','crm','title','بدء معالجة التنبيه','Start Alert Processing','بدء معالجة التنبيه','Start Alert Processing',true,now()),
  ('dailyPerformance.alerts.actionEscalate','dailyPerformanceReport','crm','title','تصعيد التنبيه للمشرف','Escalate Alert to Supervisor','تصعيد التنبيه للمشرف','Escalate Alert to Supervisor',true,now()),
  ('dailyPerformance.alerts.actionClose','dailyPerformanceReport','crm','title','إغلاق التنبيه بعد المعالجة','Close Alert After Resolution','إغلاق التنبيه بعد المعالجة','Close Alert After Resolution',true,now()),
  ('dailyPerformance.alerts.actionReopen','dailyPerformanceReport','crm','title','إعادة فتح التنبيه','Reopen Alert','إعادة فتح التنبيه','Reopen Alert',true,now()),
  ('dailyPerformance.alerts.actionGeneric','dailyPerformanceReport','crm','title','إجراء على التنبيه','Alert Action','إجراء على التنبيه','Alert Action',true,now()),
  ('dailyPerformance.alerts.actionSuccess','dailyPerformanceReport','crm','status','تم تنفيذ الإجراء على التنبيه بنجاح.','Alert action completed successfully.','تم تنفيذ الإجراء على التنبيه بنجاح.','Alert action completed successfully.',true,now()),
  ('dailyPerformance.alerts.actionError','dailyPerformanceReport','crm','error','تعذر تنفيذ الإجراء.','Unable to complete the action.','تعذر تنفيذ الإجراء.','Unable to complete the action.',true,now()),
  ('dailyPerformance.alerts.minutes','dailyPerformanceReport','crm','status','{minutes} دقيقة','{minutes} min','{minutes} دقيقة','{minutes} min',true,now()),
  ('dailyPerformance.alerts.reportEmpty','dailyPerformanceReport','crm','empty','لا توجد بيانات.','No data.','لا توجد بيانات.','No data.',true,now()),
  ('dailyPerformance.matrix.title','dailyPerformanceReport','crm','title','مصفوفة تنفيذ المهام اليومية','Daily Task Completion Matrix','مصفوفة تنفيذ المهام اليومية','Daily Task Completion Matrix',true,now()),
  ('dailyPerformance.matrix.note','dailyPerformanceReport','crm','help','حالة كل مهمة لكل موظف خلال اليوم المحدد.','Status of each task for each employee on the selected day.','حالة كل مهمة لكل موظف خلال اليوم المحدد.','Status of each task for each employee on the selected day.',true,now()),
  ('dailyPerformance.detail.selector','dailyPerformanceReport','crm','label','اختر التقرير التفصيلي','Choose Detailed Report','اختر التقرير التفصيلي','Choose Detailed Report',true,now()),
  ('dailyPerformance.detail.tasksOption','dailyPerformanceReport','crm','option','المهام اليومية','Daily Tasks','المهام اليومية','Daily Tasks',true,now()),
  ('dailyPerformance.detail.targetsOption','dailyPerformanceReport','crm','option','تحقيق الأهداف','Target Achievement','تحقيق الأهداف','Target Achievement',true,now()),
  ('dailyPerformance.detail.followupsOption','dailyPerformanceReport','crm','option','المتابعات اليومية','Daily Follow-ups','المتابعات اليومية','Daily Follow-ups',true,now()),
  ('dailyPerformance.detail.customersOption','dailyPerformanceReport','crm','option','العملاء الجدد','New Customers','العملاء الجدد','New Customers',true,now()),
  ('dailyPerformance.detail.quotationsOption','dailyPerformanceReport','crm','option','عقود العملاء','Customer Contracts','عقود العملاء','Customer Contracts',true,now()),
  ('dailyPerformance.detail.overdueOption','dailyPerformanceReport','crm','option','المتابعات المتأخرة','Overdue Follow-ups','المتابعات المتأخرة','Overdue Follow-ups',true,now()),
  ('dailyPerformance.error.chooseTimelineEmployee','dailyPerformanceReport','crm','error','اختر الموظف أولًا لعرض خط سير يومه.','Choose an employee first to view their daily timeline.','اختر الموظف أولًا لعرض خط سير يومه.','Choose an employee first to view their daily timeline.',true,now()),
  ('dailyPerformance.error.chooseTasksEmployee','dailyPerformanceReport','crm','error','اختر الموظف أولًا لعرض تقرير المهام اليومية.','Choose an employee first to view the daily tasks report.','اختر الموظف أولًا لعرض تقرير المهام اليومية.','Choose an employee first to view the daily tasks report.',true,now()),
  ('dailyPerformance.employeeTargets.title','dailyPerformanceReport','crm','title','إدارة أهداف وتقارير الموظفين','Manage Employee Targets & Reports','إدارة أهداف وتقارير الموظفين','Manage Employee Targets & Reports',true,now()),
  ('dailyPerformance.employeeTargets.note','dailyPerformanceReport','crm','help','حدد الموظفين المشمولين في التقارير والمهام والأهداف اليومية.','Select employees included in reports, daily tasks, and daily targets.','حدد الموظفين المشمولين في التقارير والمهام والأهداف اليومية.','Select employees included in reports, daily tasks, and daily targets.',true,now()),
  ('dailyPerformance.employeeTargets.effectiveFrom','dailyPerformanceReport','crm','label','تاريخ سريان الإعداد','Effective From','تاريخ سريان الإعداد','Effective From',true,now()),
  ('dailyPerformance.employeeTargets.reload','dailyPerformanceReport','crm','button','إعادة تحميل','Reload','إعادة تحميل','Reload',true,now()),
  ('dailyPerformance.employeeTargets.dashboard','dailyPerformanceReport','crm','table','لوحة التحكم','Dashboard','لوحة التحكم','Dashboard',true,now()),
  ('dailyPerformance.employeeTargets.performanceReports','dailyPerformanceReport','crm','table','تقارير الأداء','Performance Reports','تقارير الأداء','Performance Reports',true,now()),
  ('dailyPerformance.employeeTargets.timeline','dailyPerformanceReport','crm','table','خط السير','Timeline','خط السير','Timeline',true,now()),
  ('dailyPerformance.employeeTargets.tasks','dailyPerformanceReport','crm','table','المهام','Tasks','المهام','Tasks',true,now()),
  ('dailyPerformance.employeeTargets.targetsRequired','dailyPerformanceReport','crm','table','مطلوب أهداف','Targets Required','مطلوب أهداف','Targets Required',true,now()),
  ('dailyPerformance.employeeTargets.customers','dailyPerformanceReport','crm','table','العملاء','Customers','العملاء','Customers',true,now()),
  ('dailyPerformance.employeeTargets.followups','dailyPerformanceReport','crm','table','المتابعات','Follow-ups','المتابعات','Follow-ups',true,now()),
  ('dailyPerformance.employeeTargets.quotations','dailyPerformanceReport','crm','table','العروض','Contracts','العروض','Contracts',true,now()),
  ('dailyPerformance.employeeTargets.loading','dailyPerformanceReport','crm','status','جاري التحميل...','Loading...','جاري التحميل...','Loading...',true,now()),
  ('dailyPerformance.employeeTargets.cancel','dailyPerformanceReport','crm','button','إلغاء','Cancel','إلغاء','Cancel',true,now()),
  ('dailyPerformance.employeeTargets.save','dailyPerformanceReport','crm','button','حفظ الإعدادات','Save Settings','حفظ الإعدادات','Save Settings',true,now()),
  ('dailyPerformance.employeeTargets.noEmployees','dailyPerformanceReport','crm','empty','لا توجد بيانات موظفين متاحة.','No employee data available.','لا توجد بيانات موظفين متاحة.','No employee data available.',true,now()),
  ('dailyPerformance.employeeTargets.noAccounts','dailyPerformanceReport','crm','empty','لا توجد حسابات نشطة.','No active accounts.','لا توجد حسابات نشطة.','No active accounts.',true,now()),
  ('dailyPerformance.employeeTargets.loadingSettings','dailyPerformanceReport','crm','status','جاري تحميل الإعدادات...','Loading settings...','جاري تحميل الإعدادات...','Loading settings...',true,now()),
  ('dailyPerformance.employeeTargets.loadError','dailyPerformanceReport','crm','error','تعذر تحميل الإعدادات.','Unable to load settings.','تعذر تحميل الإعدادات.','Unable to load settings.',true,now()),
  ('dailyPerformance.employeeTargets.saving','dailyPerformanceReport','crm','status','جاري حفظ الإعدادات...','Saving settings...','جاري حفظ الإعدادات...','Saving settings...',true,now()),
  ('dailyPerformance.employeeTargets.saved','dailyPerformanceReport','crm','status','تم حفظ أهداف ومشاركة الموظفين في التقارير.','Employee targets and report participation were saved.','تم حفظ أهداف ومشاركة الموظفين في التقارير.','Employee targets and report participation were saved.',true,now()),
  ('dailyPerformance.employeeTargets.saveError','dailyPerformanceReport','crm','error','تعذر حفظ الإعدادات.','Unable to save settings.','تعذر حفظ الإعدادات.','Unable to save settings.',true,now()),
  ('dailyAlerts.dialog.title','dailyPerformanceReport','crm','title','إجراء على التنبيه','Alert Action','إجراء على التنبيه','Alert Action',true,now()),
  ('dailyAlerts.dialog.subtitle','dailyPerformanceReport','crm','help','أضف ملاحظة قبل تنفيذ الإجراء.','Add a note before performing the action.','أضف ملاحظة قبل تنفيذ الإجراء.','Add a note before performing the action.',true,now()),
  ('dailyAlerts.dialog.note','dailyPerformanceReport','crm','label','ملاحظة','Note','ملاحظة','Note',true,now()),
  ('dailyAlerts.dialog.cancel','dailyPerformanceReport','crm','button','إلغاء','Cancel','إلغاء','Cancel',true,now()),
  ('dailyAlerts.dialog.execute','dailyPerformanceReport','crm','button','تنفيذ','Execute','تنفيذ','Execute',true,now()),
  ('dailyTargets.dialog.title','dailyOperations','crm','title','أهداف العمل اليومية','Daily Work Targets','أهداف العمل اليومية','Daily Work Targets',true,now()),
  ('dailyTargets.dialog.note','dailyOperations','crm','help','تُطبق الأهداف على جميع المندوبين النشطين.','Targets apply to all active representatives.','تُطبق الأهداف على جميع المندوبين النشطين.','Targets apply to all active representatives.',true,now()),
  ('dailyTargets.dialog.customers','dailyOperations','crm','label','هدف العملاء الجدد','New Customer Target','هدف العملاء الجدد','New Customer Target',true,now()),
  ('dailyTargets.dialog.followups','dailyOperations','crm','label','هدف المتابعات','Follow-up Target','هدف المتابعات','Follow-up Target',true,now()),
  ('dailyTargets.dialog.quotations','dailyOperations','crm','label','هدف عقود العملاء','Customer Contract Target','هدف عقود العملاء','Customer Contract Target',true,now()),
  ('dailyTargets.dialog.cancel','dailyOperations','crm','button','إلغاء','Cancel','إلغاء','Cancel',true,now()),
  ('dailyTargets.dialog.save','dailyOperations','crm','button','حفظ الأهداف','Save Targets','حفظ الأهداف','Save Targets',true,now()),
  ('dailyOperations.service.dbNotReady','dailyOperations','crm','error','اتصال Supabase غير جاهز.','Supabase connection is not ready.','اتصال Supabase غير جاهز.','Supabase connection is not ready.',true,now()),
  ('dailyOperations.service.loadData','dailyOperations','crm','error','تعذر تحميل بيانات التشغيل اليومية:','Unable to load daily operations data:','تعذر تحميل بيانات التشغيل اليومية:','Unable to load daily operations data:',true,now()),
  ('dailyOperations.service.loadDefinitions','dailyOperations','crm','error','تعذر تحميل تعريفات المهام:','Unable to load task definitions:','تعذر تحميل تعريفات المهام:','Unable to load task definitions:',true,now()),
  ('dailyOperations.service.loadTasks','dailyOperations','crm','error','تعذر تحميل المهام اليومية:','Unable to load daily tasks:','تعذر تحميل المهام اليومية:','Unable to load daily tasks:',true,now()),
  ('dailyOperations.service.currentUser','dailyOperations','crm','error','تعذر تحديد المستخدم الحالي.','Unable to identify the current user.','تعذر تحديد المستخدم الحالي.','Unable to identify the current user.',true,now()),
  ('dailyOperations.service.updateTask','dailyOperations','crm','error','تعذر تحديث المهمة اليومية:','Unable to update the daily task:','تعذر تحديث المهمة اليومية:','Unable to update the daily task:',true,now()),
  ('dailyOperations.service.loadTargets','dailyOperations','crm','error','تعذر تحميل الأهداف اليومية:','Unable to load daily targets:','تعذر تحميل الأهداف اليومية:','Unable to load daily targets:',true,now()),
  ('dailyOperations.service.saveTargets','dailyOperations','crm','error','تعذر حفظ الأهداف اليومية:','Unable to save daily targets:','تعذر حفظ الأهداف اليومية:','Unable to save daily targets:',true,now()),
  ('dailyOperations.service.loadManagerNote','dailyOperations','crm','error','تعذر تحميل ملاحظة المدير:','Unable to load manager note:','تعذر تحميل ملاحظة المدير:','Unable to load manager note:',true,now()),
  ('dailyOperations.service.saveManagerNote','dailyOperations','crm','error','تعذر حفظ ملاحظة المدير:','Unable to save manager note:','تعذر حفظ ملاحظة المدير:','Unable to save manager note:',true,now()),
  ('dailyOperations.service.conflictChanged','dailyOperations','crm','error','تم تغيير حالة المهمة اليومية بعد العملية المحلية السابقة.','Daily task status changed after the previous local operation.','تم تغيير حالة المهمة اليومية بعد العملية المحلية السابقة.','Daily task status changed after the previous local operation.',true,now()),
  ('dailyOperations.service.conflictCreated','dailyOperations','crm','error','تم إنشاء أو تعديل المهمة اليومية على الخادم بعد آخر مزامنة.','The daily task was created or modified on the server after the last sync.','تم إنشاء أو تعديل المهمة اليومية على الخادم بعد آخر مزامنة.','The daily task was created or modified on the server after the last sync.',true,now()),
  ('dailyOperations.service.conflictModified','dailyOperations','crm','error','تم تعديل المهمة اليومية على الخادم بعد آخر مزامنة.','The daily task was modified on the server after the last sync.','تم تعديل المهمة اليومية على الخادم بعد آخر مزامنة.','The daily task was modified on the server after the last sync.',true,now()),
  ('dailyOperations.service.targetsConflict','dailyOperations','crm','error','تم تعديل الأهداف اليومية على الخادم بعد آخر مزامنة.','Daily targets were modified on the server after the last sync.','تم تعديل الأهداف اليومية على الخادم بعد آخر مزامنة.','Daily targets were modified on the server after the last sync.',true,now()),
  ('dailyOperations.service.managerConflict','dailyOperations','crm','error','تم تعديل ملاحظة المدير على الخادم بعد آخر مزامنة.','The manager note was modified on the server after the last sync.','تم تعديل ملاحظة المدير على الخادم بعد آخر مزامنة.','The manager note was modified on the server after the last sync.',true,now()),
  ('dailyPerformance.service.dbNotReady','dailyPerformanceReport','crm','error','اتصال Supabase غير جاهز.','Supabase connection is not ready.','اتصال Supabase غير جاهز.','Supabase connection is not ready.',true,now()),
  ('dailyPerformance.service.loadDefinitions','dailyPerformanceReport','crm','error','تعذر تحميل تعريفات المهام:','Unable to load task definitions:','تعذر تحميل تعريفات المهام:','Unable to load task definitions:',true,now()),
  ('dailyPerformance.service.loadCompletions','dailyPerformanceReport','crm','error','تعذر تحميل تنفيذ المهام:','Unable to load task completions:','تعذر تحميل تنفيذ المهام:','Unable to load task completions:',true,now()),
  ('dailyPerformance.service.loadTargets','dailyPerformanceReport','crm','error','تعذر تحميل أهداف اليوم:','Unable to load today’s targets:','تعذر تحميل أهداف اليوم:','Unable to load today’s targets:',true,now()),
  ('dailyPerformance.service.loadManagerNote','dailyPerformanceReport','crm','error','تعذر تحميل ملاحظة المدير:','Unable to load manager note:','تعذر تحميل ملاحظة المدير:','Unable to load manager note:',true,now()),
  ('dailyPerformance.service.loadRepresentatives','dailyPerformanceReport','crm','error','تعذر تحميل المندوبين:','Unable to load representatives:','تعذر تحميل المندوبين:','Unable to load representatives:',true,now()),
  ('dailyPerformance.service.loadUsers','dailyPerformanceReport','crm','error','تعذر تحميل المستخدمين:','Unable to load users:','تعذر تحميل المستخدمين:','Unable to load users:',true,now()),
  ('dailyPerformance.service.unnamedUser','dailyPerformanceReport','crm','label','مستخدم بدون اسم','Unnamed User','مستخدم بدون اسم','Unnamed User',true,now()),
  ('dailyActivity.service.invalidDate','dailyPerformanceReport','crm','error','تاريخ التقرير غير صالح.','Report date is invalid.','تاريخ التقرير غير صالح.','Report date is invalid.',true,now()),
  ('dailyActivity.service.endDay','dailyPerformanceReport','crm','error','تعذر إنهاء يوم العمل:','Unable to end work day:','تعذر إنهاء يوم العمل:','Unable to end work day:',true,now()),
  ('dailyActivity.service.loadSession','dailyPerformanceReport','crm','error','تعذر تحميل جلسة العمل:','Unable to load work session:','تعذر تحميل جلسة العمل:','Unable to load work session:',true,now()),
  ('dailyActivity.service.loadAttendance','dailyPerformanceReport','crm','error','تعذر تحميل الحضور اليومي:','Unable to load daily attendance:','تعذر تحميل الحضور اليومي:','Unable to load daily attendance:',true,now()),
  ('dailyActivity.service.loadLog','dailyPerformanceReport','crm','error','تعذر تحميل سجل النشاط:','Unable to load activity log:','تعذر تحميل سجل النشاط:','Unable to load activity log:',true,now()),
  ('dailyActivity.service.loadTasks','dailyPerformanceReport','crm','error','تعذر تحميل أحداث المهام:','Unable to load task events:','تعذر تحميل أحداث المهام:','Unable to load task events:',true,now()),
  ('dailyAlerts.service.load','dailyPerformanceReport','crm','error','تعذر تحميل التنبيهات:','Unable to load alerts:','تعذر تحميل التنبيهات:','Unable to load alerts:',true,now()),
  ('dailyAlerts.service.sync','dailyPerformanceReport','crm','error','تعذر مزامنة التنبيهات:','Unable to sync alerts:','تعذر مزامنة التنبيهات:','Unable to sync alerts:',true,now()),
  ('dailyAlerts.service.unsupported','dailyPerformanceReport','crm','error','نوع الإجراء غير مدعوم.','Action type is not supported.','نوع الإجراء غير مدعوم.','Action type is not supported.',true,now()),
  ('dailyAlerts.service.update','dailyPerformanceReport','crm','error','تعذر تحديث التنبيه:','Unable to update alert:','تعذر تحديث التنبيه:','Unable to update alert:',true,now()),
  ('dailyActivity.entity.customers','dailyPerformanceReport','crm','label','العملاء','Customers','العملاء','Customers',true,now()),
  ('dailyActivity.entity.followups','dailyPerformanceReport','crm','label','المتابعات','Follow-ups','المتابعات','Follow-ups',true,now()),
  ('dailyActivity.entity.quotations','dailyPerformanceReport','crm','label','عقود العملاء','Customer Contracts','عقود العملاء','Customer Contracts',true,now()),
  ('dailyActivity.entity.installations','dailyPerformanceReport','crm','label','المواعيد','Appointments','المواعيد','Appointments',true,now()),
  ('dailyActivity.entity.invoices','dailyPerformanceReport','crm','label','فواتير المبيعات','Sales Invoices','فواتير المبيعات','Sales Invoices',true,now()),
  ('dailyActivity.entity.tasks','dailyPerformanceReport','crm','label','المهام اليومية','Daily Tasks','المهام اليومية','Daily Tasks',true,now()),
  ('dailyActivity.entity.users','dailyPerformanceReport','crm','label','المستخدمون','Users','المستخدمون','Users',true,now()),
  ('dailyActivity.entity.permissions','dailyPerformanceReport','crm','label','الصلاحيات','Permissions','الصلاحيات','Permissions',true,now()),
  ('dailyActivity.entity.representatives','dailyPerformanceReport','crm','label','مندوبي المبيعات','Sales Representatives','مندوبي المبيعات','Sales Representatives',true,now()),
  ('dailyActivity.entity.other','dailyPerformanceReport','crm','label','نشاط داخل البرنامج','In-app Activity','نشاط داخل البرنامج','In-app Activity',true,now()),
  ('dailyActivity.detail.request','dailyPerformanceReport','crm','label','رقم الطلب: {value}','Request No.: {value}','رقم الطلب: {value}','Request No.: {value}',true,now()),
  ('dailyActivity.detail.quotation','dailyPerformanceReport','crm','label','رقم عرض السعر: {value}','Contract No.: {value}','رقم عرض السعر: {value}','Contract No.: {value}',true,now()),
  ('dailyActivity.detail.invoice','dailyPerformanceReport','crm','label','رقم الفاتورة: {value}','Invoice No.: {value}','رقم الفاتورة: {value}','Invoice No.: {value}',true,now()),
  ('dailyActivity.detail.phone','dailyPerformanceReport','crm','label','رقم الجوال: {value}','Mobile: {value}','رقم الجوال: {value}','Mobile: {value}',true,now()),
  ('dailyActivity.detail.source','dailyPerformanceReport','crm','label','المصدر: {value}','Source: {value}','المصدر: {value}','Source: {value}',true,now()),
  ('dailyActivity.detail.success','dailyPerformanceReport','crm','status','تم تنفيذ الحركة بنجاح.','Action completed successfully.','تم تنفيذ الحركة بنجاح.','Action completed successfully.',true,now()),
  ('dailyActivity.action.create','dailyPerformanceReport','crm','label','إضافة','Create','إضافة','Create',true,now()),
  ('dailyActivity.action.update','dailyPerformanceReport','crm','label','تعديل','Update','تعديل','Update',true,now()),
  ('dailyActivity.action.delete','dailyPerformanceReport','crm','label','حذف','Delete','حذف','Delete',true,now()),
  ('dailyActivity.action.complete','dailyPerformanceReport','crm','label','إكمال','Complete','إكمال','Complete',true,now()),
  ('dailyActivity.action.reopen','dailyPerformanceReport','crm','label','إعادة فتح','Reopen','إعادة فتح','Reopen',true,now()),
  ('dailyActivity.action.start','dailyPerformanceReport','crm','label','بدء المعالجة','Start Processing','بدء المعالجة','Start Processing',true,now()),
  ('dailyActivity.action.escalate','dailyPerformanceReport','crm','label','تصعيد','Escalate','تصعيد','Escalate',true,now()),
  ('dailyActivity.action.close','dailyPerformanceReport','crm','label','إغلاق','Close','إغلاق','Close',true,now()),
  ('dailyActivity.action.login','dailyPerformanceReport','crm','label','تسجيل الدخول','Login','تسجيل الدخول','Login',true,now()),
  ('dailyActivity.action.heartbeat','dailyPerformanceReport','crm','label','نشاط داخل النظام','System Activity','نشاط داخل النظام','System Activity',true,now()),
  ('dailyActivity.action.endDay','dailyPerformanceReport','crm','label','إنهاء يوم العمل','End Work Day','إنهاء يوم العمل','End Work Day',true,now()),
  ('dailyActivity.action.whatsapp','dailyPerformanceReport','crm','label','فتح واتساب','Open WhatsApp','فتح واتساب','Open WhatsApp',true,now()),
  ('dailyActivity.action.generic','dailyPerformanceReport','crm','label','نشاط','Activity','نشاط','Activity',true,now()),
  ('dailyActivity.unknown','dailyPerformanceReport','crm','label','غير محدد','Unknown','غير محدد','Unknown',true,now()),
  ('dailyActivity.timeline.startTitle','dailyPerformanceReport','crm','title','بدء يوم العمل','Work Day Started','بدء يوم العمل','Work Day Started',true,now()),
  ('dailyActivity.timeline.startDetail','dailyPerformanceReport','crm','help','تم تسجيل أول نشاط للمستخدم.','The user’s first activity was recorded.','تم تسجيل أول نشاط للمستخدم.','The user’s first activity was recorded.',true,now()),
  ('dailyActivity.timeline.endTitle','dailyPerformanceReport','crm','title','إنهاء يوم العمل','Work Day Ended','إنهاء يوم العمل','Work Day Ended',true,now()),
  ('dailyActivity.timeline.endDetail','dailyPerformanceReport','crm','help','إجمالي العمليات المسجلة: {count}','Total recorded operations: {count}','إجمالي العمليات المسجلة: {count}','Total recorded operations: {count}',true,now()),
  ('dailyActivity.timeline.taskComplete','dailyPerformanceReport','crm','title','إكمال مهمة يومية','Daily Task Completed','إكمال مهمة يومية','Daily Task Completed',true,now()),
  ('dailyActivity.timeline.taskReopen','dailyPerformanceReport','crm','title','إعادة فتح مهمة يومية','Daily Task Reopened','إعادة فتح مهمة يومية','Daily Task Reopened',true,now()),
  ('dailyActivity.timeline.alert','dailyPerformanceReport','crm','title','{action} تنبيه','{action} Alert','{action} تنبيه','{action} Alert',true,now()),
  ('dailyPerformance.kpi.checklistInitial','dailyPerformanceReport','crm','status','0 من 0','0 of 0','0 من 0','0 of 0',true,now()),
  ('dailyOperations.team.serviceUnavailable','dailyOperations','crm','error','تعذر تحميل خدمة متابعة الفريق.','Unable to load the team tracking service.','تعذر تحميل خدمة متابعة الفريق.','Unable to load the team tracking service.',true,now()),
  ('dailyOperations.team.loadError','dailyOperations','crm','error','تعذر تحميل متابعة إنجاز الفريق.','Unable to load team completion tracking.','تعذر تحميل متابعة إنجاز الفريق.','Unable to load team completion tracking.',true,now()),
  ('dailyOperations.team.loading','dailyOperations','crm','status','جارٍ تحميل أداء الفريق...','Loading team performance...','جارٍ تحميل أداء الفريق...','Loading team performance...',true,now()),
  ('dailyOperations.team.summaryError','dailyOperations','crm','status','تعذر تحميل أداء الفريق','Unable to load team performance','تعذر تحميل أداء الفريق','Unable to load team performance',true,now()),
  ('dailyOperations.team.errorTitle','dailyOperations','crm','error','تعذر تحميل متابعة الفريق','Unable to load team tracking','تعذر تحميل متابعة الفريق','Unable to load team tracking',true,now()),
  ('dailyOperations.team.summary','dailyOperations','crm','format','{users} مستخدمين — {completed} من {target} تواصل مكتمل','{users} users — {completed} of {target} completed contacts','{users} مستخدمين — {completed} من {target} تواصل مكتمل','{users} users — {completed} of {target} completed contacts',true,now()),
  ('dailyOperations.team.empty','dailyOperations','crm','empty','لا توجد حسابات مبيعات نشطة لعرضها.','No active sales accounts to display.','لا توجد حسابات مبيعات نشطة لعرضها.','No active sales accounts to display.',true,now()),
  ('dailyActivity.detail.whatsappOpened','dailyPerformanceReport','crm','help','تم فتح رابط واتساب بنجاح.','WhatsApp link opened successfully.','تم فتح رابط واتساب بنجاح.','WhatsApp link opened successfully.',true,now()),
  ('pwa.update.release.r44r32.title','aboutApp','system','title','استكمال ترجمة التشغيل والأداء اليومي','Daily Operations & Performance Localization','استكمال ترجمة التشغيل والأداء اليومي','Daily Operations & Performance Localization',true,now()),
  ('pwa.update.release.r44r32.note1','aboutApp','system','help','استكمال ترجمة إدارة المهام اليومية وحالات التحميل والفراغ والرسائل التشغيلية.','Completes localization for Daily Operations, including loading, empty, and runtime states.','استكمال ترجمة إدارة المهام اليومية وحالات التحميل والفراغ والرسائل التشغيلية.','Completes localization for Daily Operations, including loading, empty, and runtime states.',true,now()),
  ('pwa.update.release.r44r32.note2','aboutApp','system','help','استكمال ترجمة تقرير الأداء اليومي وخط السير والتنبيهات ومصفوفة المهام.','Completes localization for Daily Performance, timeline, alerts, and task matrix.','استكمال ترجمة تقرير الأداء اليومي وخط السير والتنبيهات ومصفوفة المهام.','Completes localization for Daily Performance, timeline, alerts, and task matrix.',true,now()),
  ('pwa.update.release.r44r32.note3','aboutApp','system','help','الحفاظ على عقود Offline/Sync ومنطق الأعمال دون تغيير؛ تمت الترجمة في طبقة العرض المعتمدة.','Preserves Offline/Sync contracts and business logic; localization remains in the canonical display layer.','الحفاظ على عقود Offline/Sync ومنطق الأعمال دون تغيير؛ تمت الترجمة في طبقة العرض المعتمدة.','Preserves Offline/Sync contracts and business logic; localization remains in the canonical display layer.',true,now())
)
insert into public.app_translations (translation_key,screen_key,module_name,text_type,ar_text,en_text,default_ar,default_en,is_active,updated_at)
select * from translation_seed
on conflict (translation_key) do update set
  screen_key=excluded.screen_key,
  module_name=excluded.module_name,
  text_type=excluded.text_type,
  ar_text=case when nullif(trim(public.app_translations.ar_text),'') is null then excluded.ar_text else public.app_translations.ar_text end,
  en_text=case when nullif(trim(public.app_translations.en_text),'') is null then excluded.en_text else public.app_translations.en_text end,
  default_ar=excluded.default_ar,
  default_en=excluded.default_en,
  is_active=true,
  updated_at=now();

commit;
