-- R44R33 — CRM L2-C Reports / Customer 360 / Customer Excel / CRM runtime localization
-- Non-destructive seed for canonical public.app_translations.
-- Existing customized translations are preserved; only blank values are filled.

begin;

with translation_seed(translation_key,screen_key,module_name,text_type,ar_text,en_text,default_ar,default_en,is_active,updated_at) as (
values
  ('reportsOverview.page.title','reportsOverview','crm','label','مركز التقارير','Reports Center','مركز التقارير','Reports Center',true,now()),
  ('reportsOverview.page.subtitle','reportsOverview','crm','label','تحليلات العملاء والمتابعات والعروض وأداء المندوبين','Customer, follow-up, contract, and representative performance analytics','تحليلات العملاء والمتابعات والعروض وأداء المندوبين','Customer, follow-up, contract, and representative performance analytics',true,now()),
  ('reportsOverview.title','reportsOverview','crm','label','مركز التقارير والتحليلات','Reports & Analytics Center','مركز التقارير والتحليلات','Reports & Analytics Center',true,now()),
  ('reportsOverview.note','reportsOverview','crm','label','ملخص تنفيذي حي لبيانات العملاء والمتابعات وعقود العملاء وأداء المندوبين.','Live executive summary of customers, follow-ups, customer contracts, and representative performance.','ملخص تنفيذي حي لبيانات العملاء والمتابعات وعقود العملاء وأداء المندوبين.','Live executive summary of customers, follow-ups, customer contracts, and representative performance.',true,now()),
  ('reportsOverview.action.refresh','reportsOverview','crm','label','تحديث التقرير','Refresh Report','تحديث التقرير','Refresh Report',true,now()),
  ('reportsOverview.action.exportCenter','reportsOverview','crm','label','مركز التصدير','Export Center','مركز التصدير','Export Center',true,now()),
  ('reportsOverview.filter.from','reportsOverview','crm','label','من تاريخ','From Date','من تاريخ','From Date',true,now()),
  ('reportsOverview.filter.to','reportsOverview','crm','label','إلى تاريخ','To Date','إلى تاريخ','To Date',true,now()),
  ('reportsOverview.filter.representative','reportsOverview','crm','label','المندوب','Representative','المندوب','Representative',true,now()),
  ('reportsOverview.filter.allRepresentatives','reportsOverview','crm','label','كل المندوبين','All Representatives','كل المندوبين','All Representatives',true,now()),
  ('reportsOverview.filter.target','reportsOverview','crm','label','هدف قيمة العروض','Contract Value Target','هدف قيمة العروض','Contract Value Target',true,now()),
  ('reportsOverview.filter.reset','reportsOverview','crm','label','إعادة التعيين','Reset','إعادة التعيين','Reset',true,now()),
  ('reportsOverview.period.current','reportsOverview','crm','label','الفترة الحالية','Current Period','الفترة الحالية','Current Period',true,now()),
  ('reportsOverview.period.previous','reportsOverview','crm','label','فترة المقارنة','Comparison Period','فترة المقارنة','Comparison Period',true,now()),
  ('reportsOverview.period.all','reportsOverview','crm','label','كل الفترات','All Periods','كل الفترات','All Periods',true,now()),
  ('reportsOverview.kpi.targetAchievement','reportsOverview','crm','label','تحقيق الهدف','Target Achievement','تحقيق الهدف','Target Achievement',true,now()),
  ('reportsOverview.kpi.customers','reportsOverview','crm','label','إجمالي العملاء','Total Customers','إجمالي العملاء','Total Customers',true,now()),
  ('reportsOverview.kpi.newInitial','reportsOverview','crm','label','الجدد: 0','New: 0','الجدد: 0','New: 0',true,now()),
  ('reportsOverview.kpi.todayFollowups','reportsOverview','crm','label','متابعات اليوم','Today’s Follow-ups','متابعات اليوم','Today’s Follow-ups',true,now()),
  ('reportsOverview.kpi.overdueInitial','reportsOverview','crm','label','المتأخرة: 0','Overdue: 0','المتأخرة: 0','Overdue: 0',true,now()),
  ('reportsOverview.kpi.followups','reportsOverview','crm','label','إجمالي المتابعات','Total Follow-ups','إجمالي المتابعات','Total Follow-ups',true,now()),
  ('reportsOverview.kpi.completedInitial','reportsOverview','crm','label','المكتملة: 0','Completed: 0','المكتملة: 0','Completed: 0',true,now()),
  ('reportsOverview.kpi.contracts','reportsOverview','crm','label','إجمالي العروض','Total Contracts','إجمالي العروض','Total Contracts',true,now()),
  ('reportsOverview.kpi.acceptedInitial','reportsOverview','crm','label','المقبولة: 0','Accepted: 0','المقبولة: 0','Accepted: 0',true,now()),
  ('reportsOverview.kpi.contractValue','reportsOverview','crm','label','قيمة العروض','Contract Value','قيمة العروض','Contract Value',true,now()),
  ('reportsOverview.kpi.acceptedValueInitial','reportsOverview','crm','label','المقبولة: 0 SAR','Accepted: 0 SAR','المقبولة: 0 SAR','Accepted: 0 SAR',true,now()),
  ('reportsOverview.kpi.conversion','reportsOverview','crm','label','نسبة التحويل','Conversion Rate','نسبة التحويل','Conversion Rate',true,now()),
  ('reportsOverview.kpi.conversionHelp','reportsOverview','crm','label','العقود المقبولة ÷ إجمالي العروض','Accepted contracts ÷ total contracts','العقود المقبولة ÷ إجمالي العروض','Accepted contracts ÷ total contracts',true,now()),
  ('reportsOverview.kpi.remainingInitial','reportsOverview','crm','label','المتبقي: 0 SAR','Remaining: 0 SAR','المتبقي: 0 SAR','Remaining: 0 SAR',true,now()),
  ('reportsOverview.kpi.withoutFollowup','reportsOverview','crm','label','عملاء بلا متابعة','Customers Without Follow-up','عملاء بلا متابعة','Customers Without Follow-up',true,now()),
  ('reportsOverview.kpi.requiresAction','reportsOverview','crm','label','يحتاجون إجراءً','Require Action','يحتاجون إجراءً','Require Action',true,now()),
  ('reportsOverview.funnel.title','reportsOverview','crm','label','مسار المبيعات التنفيذي','Executive Sales Funnel','مسار المبيعات التنفيذي','Executive Sales Funnel',true,now()),
  ('reportsOverview.funnel.note','reportsOverview','crm','label','توزيع العروض حسب الحالة الحالية.','Contract distribution by current status.','توزيع العروض حسب الحالة الحالية.','Contract distribution by current status.',true,now()),
  ('reportsOverview.contractStatus.note','reportsOverview','crm','label','توزيع العروض حسب الحالة الحالية.','Contract distribution by current status.','توزيع العروض حسب الحالة الحالية.','Contract distribution by current status.',true,now()),
  ('reportsOverview.customerAnalytics.title','reportsOverview','crm','label','تحليل العملاء','Customer Analysis','تحليل العملاء','Customer Analysis',true,now()),
  ('reportsOverview.customerAnalytics.note','reportsOverview','crm','label','التصنيف والاهتمامات والمندوبون وحالة النشاط.','Type, interests, representatives, and activity status.','التصنيف والاهتمامات والمندوبون وحالة النشاط.','Type, interests, representatives, and activity status.',true,now()),
  ('reportsOverview.customerAnalytics.types','reportsOverview','crm','label','التصنيف','Type','التصنيف','Type',true,now()),
  ('reportsOverview.customerAnalytics.interests','reportsOverview','crm','label','الاهتمامات','Interests','الاهتمامات','Interests',true,now()),
  ('reportsOverview.customerAnalytics.representatives','reportsOverview','crm','label','المندوبون','Representatives','المندوبون','Representatives',true,now()),
  ('reportsOverview.customerAnalytics.activity','reportsOverview','crm','label','النشاط','Activity','النشاط','Activity',true,now()),
  ('reportsOverview.contractValue.title','reportsOverview','crm','label','تحليل قيم عقود العملاء','Customer Contract Value Analysis','تحليل قيم عقود العملاء','Customer Contract Value Analysis',true,now()),
  ('reportsOverview.contractValue.note','reportsOverview','crm','label','المتوسط والأعلى والأقل وقيمة العقود المفتوحة والمرفوضة.','Average, highest, lowest, open, and rejected contract values.','المتوسط والأعلى والأقل وقيمة العقود المفتوحة والمرفوضة.','Average, highest, lowest, open, and rejected contract values.',true,now()),
  ('reportsOverview.contractValue.average','reportsOverview','crm','label','متوسط العرض','Average Contract','متوسط العرض','Average Contract',true,now()),
  ('reportsOverview.contractValue.highest','reportsOverview','crm','label','أعلى عرض','Highest Contract','أعلى عرض','Highest Contract',true,now()),
  ('reportsOverview.contractValue.lowest','reportsOverview','crm','label','أقل عرض','Lowest Contract','أقل عرض','Lowest Contract',true,now()),
  ('reportsOverview.contractValue.open','reportsOverview','crm','label','قيمة المفتوح','Open Value','قيمة المفتوح','Open Value',true,now()),
  ('reportsOverview.contractValue.rejected','reportsOverview','crm','label','قيمة المرفوض','Rejected Value','قيمة المرفوض','Rejected Value',true,now()),
  ('reportsOverview.contractValue.rejectionRate','reportsOverview','crm','label','معدل الرفض','Rejection Rate','معدل الرفض','Rejection Rate',true,now()),
  ('reportsOverview.lossReasons.title','reportsOverview','crm','label','أكثر أسباب الخسارة','Top Loss Reasons','أكثر أسباب الخسارة','Top Loss Reasons',true,now()),
  ('reportsOverview.lossReasons.note','reportsOverview','crm','label','أسباب رفض عقود العملاء وعدم إتمام البيع.','Reasons for rejected customer contracts and lost sales.','أسباب رفض عقود العملاء وعدم إتمام البيع.','Reasons for rejected customer contracts and lost sales.',true,now()),
  ('reportsOverview.topCustomers.title','reportsOverview','crm','label','أعلى العملاء من حيث قيمة العروض','Top Customers by Contract Value','أعلى العملاء من حيث قيمة العروض','Top Customers by Contract Value',true,now()),
  ('reportsOverview.topCustomers.note','reportsOverview','crm','label','أعلى 10 عملاء داخل النطاق المحدد.','Top 10 customers within the selected range.','أعلى 10 عملاء داخل النطاق المحدد.','Top 10 customers within the selected range.',true,now()),
  ('reportsOverview.inactive.title','reportsOverview','crm','label','العملاء غير النشطين','Inactive Customers','العملاء غير النشطين','Inactive Customers',true,now()),
  ('reportsOverview.inactive.note','reportsOverview','crm','label','لم يحدث معهم تواصل خلال 30 يومًا أو أكثر.','No contact for 30 days or more.','لم يحدث معهم تواصل خلال 30 يومًا أو أكثر.','No contact for 30 days or more.',true,now()),
  ('reportsOverview.needsFollowup.title','reportsOverview','crm','label','عملاء يحتاجون متابعة','Customers Needing Follow-up','عملاء يحتاجون متابعة','Customers Needing Follow-up',true,now()),
  ('reportsOverview.needsFollowup.note','reportsOverview','crm','label','بدون متابعة أو لديهم متابعة متأخرة.','No follow-up or an overdue follow-up.','بدون متابعة أو لديهم متابعة متأخرة.','No follow-up or an overdue follow-up.',true,now()),
  ('reportsOverview.monthly.title','reportsOverview','crm','label','اتجاه النشاط الشهري','Monthly Activity Trend','اتجاه النشاط الشهري','Monthly Activity Trend',true,now()),
  ('reportsOverview.monthly.note','reportsOverview','crm','label','العملاء والمتابعات والعروض خلال آخر 6 أشهر.','Customers, follow-ups, and contracts over the last 6 months.','العملاء والمتابعات والعروض خلال آخر 6 أشهر.','Customers, follow-ups, and contracts over the last 6 months.',true,now()),
  ('reportsOverview.followupIndicators.title','reportsOverview','crm','label','أهم مؤشرات المتابعة','Key Follow-up Indicators','أهم مؤشرات المتابعة','Key Follow-up Indicators',true,now()),
  ('reportsOverview.followupIndicators.note','reportsOverview','crm','label','المتأخر والقادم والمكتمل داخل النطاق المحدد.','Overdue, upcoming, and completed within the selected range.','المتأخر والقادم والمكتمل داخل النطاق المحدد.','Overdue, upcoming, and completed within the selected range.',true,now()),
  ('reportsOverview.repRanking.title','reportsOverview','crm','label','ترتيب مندوبي المبيعات','Sales Representative Ranking','ترتيب مندوبي المبيعات','Sales Representative Ranking',true,now()),
  ('reportsOverview.repRanking.note','reportsOverview','crm','label','ترتيب حسب قيمة العقود المقبولة ونسبة التحويل والنشاط.','Ranked by accepted contract value, conversion rate, and activity.','ترتيب حسب قيمة العقود المقبولة ونسبة التحويل والنشاط.','Ranked by accepted contract value, conversion rate, and activity.',true,now()),
  ('reportsOverview.repComparison.title','reportsOverview','crm','label','مقارنة أداء المندوبين','Representative Performance Comparison','مقارنة أداء المندوبين','Representative Performance Comparison',true,now()),
  ('reportsOverview.repComparison.note','reportsOverview','crm','label','الفترة الحالية مقابل الفترة السابقة.','Current period versus previous period.','الفترة الحالية مقابل الفترة السابقة.','Current period versus previous period.',true,now()),
  ('reportsOverview.yearly.title','reportsOverview','crm','label','اتجاه الأداء خلال 12 شهرًا','12-Month Performance Trend','اتجاه الأداء خلال 12 شهرًا','12-Month Performance Trend',true,now()),
  ('reportsOverview.yearly.note','reportsOverview','crm','label','العملاء والمتابعات والعروض وقيمة العروض.','Customers, follow-ups, contracts, and contract value.','العملاء والمتابعات والعروض وقيمة العروض.','Customers, follow-ups, contracts, and contract value.',true,now()),
  ('reportsOverview.common.customers','reportsOverview','crm','label','العملاء','Customers','العملاء','Customers',true,now()),
  ('reportsOverview.common.followups','reportsOverview','crm','label','المتابعات','Follow-ups','المتابعات','Follow-ups',true,now()),
  ('reportsOverview.common.contracts','reportsOverview','crm','label','العروض','Contracts','العروض','Contracts',true,now()),
  ('reportsOverview.common.value','reportsOverview','crm','label','القيمة','Value','القيمة','Value',true,now()),
  ('reportsOverview.common.accepted','reportsOverview','crm','label','المقبولة','Accepted','المقبولة','Accepted',true,now()),
  ('reportsOverview.common.conversion','reportsOverview','crm','label','تحويل','Conversion','تحويل','Conversion',true,now()),
  ('reportsOverview.common.unspecified','reportsOverview','crm','label','غير محدد','Unspecified','غير محدد','Unspecified',true,now()),
  ('reportsOverview.topReps.title','reportsOverview','crm','label','أفضل 10 مندوبين','Top 10 Representatives','أفضل 10 مندوبين','Top 10 Representatives',true,now()),
  ('reportsOverview.topReps.note','reportsOverview','crm','label','حسب قيمة العقود المقبولة.','By accepted contract value.','حسب قيمة العقود المقبولة.','By accepted contract value.',true,now()),
  ('reportsOverview.topInterests.title','reportsOverview','crm','label','أعلى 10 اهتمامات','Top 10 Interests','أعلى 10 اهتمامات','Top 10 Interests',true,now()),
  ('reportsOverview.topInterests.note','reportsOverview','crm','label','الاهتمامات الأكثر تكرارًا لدى العملاء.','Most frequent customer interests.','الاهتمامات الأكثر تكرارًا لدى العملاء.','Most frequent customer interests.',true,now()),
  ('reportsOverview.topCustomersExecutive.title','reportsOverview','crm','label','أفضل 10 عملاء','Top 10 Customers','أفضل 10 عملاء','Top 10 Customers',true,now()),
  ('reportsOverview.topCustomersExecutive.note','reportsOverview','crm','label','حسب إجمالي قيمة عقود العملاء.','By total customer contract value.','حسب إجمالي قيمة عقود العملاء.','By total customer contract value.',true,now()),
  ('reportsOverview.topLossReasons.title','reportsOverview','crm','label','أكثر 10 أسباب خسارة','Top 10 Loss Reasons','أكثر 10 أسباب خسارة','Top 10 Loss Reasons',true,now()),
  ('reportsOverview.topLossReasons.note','reportsOverview','crm','label','الأسباب الأعلى تكرارًا.','Most frequent reasons.','الأسباب الأعلى تكرارًا.','Most frequent reasons.',true,now()),
  ('reportsOverview.repPerformance.title','reportsOverview','crm','label','أداء مندوبي المبيعات','Sales Representative Performance','أداء مندوبي المبيعات','Sales Representative Performance',true,now()),
  ('reportsOverview.repPerformance.note','reportsOverview','crm','label','العملاء والمتابعات والعروض والقيمة ونسبة التحويل لكل مندوب.','Customers, follow-ups, contracts, value, and conversion rate for each representative.','العملاء والمتابعات والعروض والقيمة ونسبة التحويل لكل مندوب.','Customers, follow-ups, contracts, value, and conversion rate for each representative.',true,now()),
  ('reportsOverview.loading','reportsOverview','crm','label','جاري تحديث بيانات التقارير...','Refreshing report data...','جاري تحديث بيانات التقارير...','Refreshing report data...',true,now()),
  ('reportsOverview.error.load','reportsOverview','crm','label','تعذر تحميل بيانات التقارير.','Unable to load report data.','تعذر تحميل بيانات التقارير.','Unable to load report data.',true,now()),
  ('reportsOverview.activity.active7','reportsOverview','crm','label','نشط خلال 7 أيام','Active within 7 days','نشط خلال 7 أيام','Active within 7 days',true,now()),
  ('reportsOverview.activity.active30','reportsOverview','crm','label','نشط خلال 30 يومًا','Active within 30 days','نشط خلال 30 يومًا','Active within 30 days',true,now()),
  ('reportsOverview.activity.inactive30','reportsOverview','crm','label','غير نشط أكثر من 30 يومًا','Inactive for more than 30 days','غير نشط أكثر من 30 يومًا','Inactive for more than 30 days',true,now()),
  ('reportsOverview.activity.neverContacted','reportsOverview','crm','label','لم يتم التواصل','Never contacted','لم يتم التواصل','Never contacted',true,now()),
  ('reportsOverview.empty.range','reportsOverview','crm','label','لا توجد بيانات داخل النطاق المحدد.','No data within the selected range.','لا توجد بيانات داخل النطاق المحدد.','No data within the selected range.',true,now()),
  ('reportsOverview.empty.contractsRange','reportsOverview','crm','label','لا توجد عروض داخل النطاق المحدد.','No contracts within the selected range.','لا توجد عروض داخل النطاق المحدد.','No contracts within the selected range.',true,now()),
  ('reportsOverview.empty.inactive','reportsOverview','crm','label','لا يوجد عملاء غير نشطين داخل النطاق المحدد.','No inactive customers within the selected range.','لا يوجد عملاء غير نشطين داخل النطاق المحدد.','No inactive customers within the selected range.',true,now()),
  ('reportsOverview.empty.followupsHealthy','reportsOverview','crm','label','كل العملاء لديهم متابعة سليمة.','All customers have valid follow-up coverage.','كل العملاء لديهم متابعة سليمة.','All customers have valid follow-up coverage.',true,now()),
  ('reportsOverview.empty.representatives','reportsOverview','crm','label','لا توجد بيانات مندوبي مبيعات.','No sales representative data.','لا توجد بيانات مندوبي مبيعات.','No sales representative data.',true,now()),
  ('reportsOverview.empty.comparison','reportsOverview','crm','label','لا توجد بيانات مقارنة.','No comparison data.','لا توجد بيانات مقارنة.','No comparison data.',true,now()),
  ('reportsOverview.empty.data','reportsOverview','crm','label','لا توجد بيانات.','No data.','لا توجد بيانات.','No data.',true,now()),
  ('reportsOverview.empty.performance','reportsOverview','crm','label','لا توجد بيانات أداء داخل النطاق المحدد.','No performance data within the selected range.','لا توجد بيانات أداء داخل النطاق المحدد.','No performance data within the selected range.',true,now()),
  ('reportsOverview.format.new','reportsOverview','crm','format','الجدد: {count}','New: {count}','الجدد: {count}','New: {count}',true,now()),
  ('reportsOverview.format.overdue','reportsOverview','crm','format','المتأخرة: {count}','Overdue: {count}','المتأخرة: {count}','Overdue: {count}',true,now()),
  ('reportsOverview.format.completed','reportsOverview','crm','format','المكتملة: {count}','Completed: {count}','المكتملة: {count}','Completed: {count}',true,now()),
  ('reportsOverview.format.accepted','reportsOverview','crm','format','المقبولة: {count}','Accepted: {count}','المقبولة: {count}','Accepted: {count}',true,now()),
  ('reportsOverview.format.acceptedValue','reportsOverview','crm','format','المقبولة: {value}','Accepted: {value}','المقبولة: {value}','Accepted: {value}',true,now()),
  ('reportsOverview.format.remaining','reportsOverview','crm','format','المتبقي: {value}','Remaining: {value}','المتبقي: {value}','Remaining: {value}',true,now()),
  ('reportsOverview.format.contractsAccepted','reportsOverview','crm','format','{contracts} عروض — {accepted} مقبولة','{contracts} contracts — {accepted} accepted','{contracts} عروض — {accepted} مقبولة','{contracts} contracts — {accepted} accepted',true,now()),
  ('reportsOverview.format.days','reportsOverview','crm','format','{count} يوم','{count} days','{count} يوم','{count} days',true,now()),
  ('reportsOverview.format.acceptedContractsValue','reportsOverview','crm','format','{count} عروض مقبولة — {value}','{count} accepted contracts — {value}','{count} عروض مقبولة — {value}','{count} accepted contracts — {value}',true,now()),
  ('reportsOverview.format.acceptedConversion','reportsOverview','crm','format','{accepted} مقبولة — {conversion}% تحويل','{accepted} accepted — {conversion}% conversion','{accepted} مقبولة — {conversion}% تحويل','{accepted} accepted — {conversion}% conversion',true,now()),
  ('reportsOverview.funnel.stage.lead','reportsOverview','crm','label','العملاء المحتملون','Leads','العملاء المحتملون','Leads',true,now()),
  ('reportsOverview.funnel.stage.qualified','reportsOverview','crm','label','عملاء مؤهلون','Qualified Customers','عملاء مؤهلون','Qualified Customers',true,now()),
  ('reportsOverview.funnel.stage.followup','reportsOverview','crm','label','تمت متابعتهم','Followed Up','تمت متابعتهم','Followed Up',true,now()),
  ('reportsOverview.funnel.stage.quotation','reportsOverview','crm','label','استلموا عرض سعر','Received Contract','استلموا عرض سعر','Received Contract',true,now()),
  ('reportsOverview.funnel.stage.negotiation','reportsOverview','crm','label','تحت التفاوض','Negotiation','تحت التفاوض','Negotiation',true,now()),
  ('reportsOverview.funnel.stage.won','reportsOverview','crm','label','صفقات ناجحة','Won Deals','صفقات ناجحة','Won Deals',true,now()),
  ('reportsOverview.funnel.fromPrevious','reportsOverview','crm','format','من المرحلة السابقة: {value}%','From previous stage: {value}%','من المرحلة السابقة: {value}%','From previous stage: {value}%',true,now()),
  ('reportsOverview.funnel.fromTotal','reportsOverview','crm','format','من إجمالي العملاء: {value}%','From total customers: {value}%','من إجمالي العملاء: {value}%','From total customers: {value}%',true,now()),
  ('reportsOverview.funnel.negotiating','reportsOverview','crm','label','تحت التفاوض','Negotiating','تحت التفاوض','Negotiating',true,now()),
  ('reportsOverview.funnel.wonDeals','reportsOverview','crm','label','صفقات ناجحة','Won Deals','صفقات ناجحة','Won Deals',true,now()),
  ('reportsOverview.chart.customers','reportsOverview','crm','format','العملاء: {count}','Customers: {count}','العملاء: {count}','Customers: {count}',true,now()),
  ('reportsOverview.chart.followups','reportsOverview','crm','format','المتابعات: {count}','Follow-ups: {count}','المتابعات: {count}','Follow-ups: {count}',true,now()),
  ('reportsOverview.chart.contracts','reportsOverview','crm','format','العروض: {count}','Contracts: {count}','العروض: {count}','Contracts: {count}',true,now()),
  ('reportsOverview.chart.value','reportsOverview','crm','format','القيمة: {value}','Value: {value}','القيمة: {value}','Value: {value}',true,now()),
  ('reportsOverview.followup.noDate','reportsOverview','crm','label','بدون موعد','No Date','بدون موعد','No Date',true,now()),
  ('reportsOverview.followupReason.overdue','reportsOverview','crm','label','متابعة متأخرة','Overdue Follow-up','متابعة متأخرة','Overdue Follow-up',true,now()),
  ('reportsOverview.followupReason.none','reportsOverview','crm','label','بدون متابعة','No Follow-up','بدون متابعة','No Follow-up',true,now()),
  ('reportsOverview.comparison.currentVsPrevious','reportsOverview','crm','label','الفترة الحالية مقابل السابقة','Current period versus previous','الفترة الحالية مقابل السابقة','Current period versus previous',true,now()),
  ('reportsOverview.updatedAt','reportsOverview','crm','format','تم تحديث التقرير في {time}.','Report updated at {time}.','تم تحديث التقرير في {time}.','Report updated at {time}.',true,now()),
  ('customer360.action.addFollowup','customers','crm','label','إضافة متابعة','Add Follow-up','إضافة متابعة','Add Follow-up',true,now()),
  ('customer360.action.editCustomer','customers','crm','label','تعديل العميل','Edit Customer','تعديل العميل','Edit Customer',true,now()),
  ('customer360.action.exportFile','customers','crm','label','تصدير الملف','Export File','تصدير الملف','Export File',true,now()),
  ('customer360.common.noCode','customers','crm','label','بدون كود','No Code','بدون كود','No Code',true,now()),
  ('customer360.common.noPhone','customers','crm','label','بدون جوال','No Mobile','بدون جوال','No Mobile',true,now()),
  ('customer360.common.unspecified','customers','crm','label','غير محدد','Unspecified','غير محدد','Unspecified',true,now()),
  ('customer360.common.followup','customers','crm','label','متابعة','Follow-up','متابعة','Follow-up',true,now()),
  ('customer360.overview.status','customers','crm','label','حالة العميل','Customer Status','حالة العميل','Customer Status',true,now()),
  ('customer360.overview.lastContact','customers','crm','label','آخر تواصل','Last Contact','آخر تواصل','Last Contact',true,now()),
  ('customer360.overview.noDuration','customers','crm','label','لا توجد مدة محسوبة','No calculated duration','لا توجد مدة محسوبة','No calculated duration',true,now()),
  ('customer360.overview.daysAgo','customers','crm','format','منذ {days} يوم','{days} days ago','منذ {days} يوم','{days} days ago',true,now()),
  ('customer360.kpi.followups','customers','crm','label','إجمالي المتابعات','Total Follow-ups','إجمالي المتابعات','Total Follow-ups',true,now()),
  ('customer360.kpi.overdue','customers','crm','format','المتأخرة: {count}','Overdue: {count}','المتأخرة: {count}','Overdue: {count}',true,now()),
  ('customer360.kpi.upcoming','customers','crm','label','المتابعات القادمة','Upcoming Follow-ups','المتابعات القادمة','Upcoming Follow-ups',true,now()),
  ('customer360.kpi.next','customers','crm','format','القادم: {date}','Next: {date}','القادم: {date}','Next: {date}',true,now()),
  ('customer360.kpi.noNext','customers','crm','label','لا يوجد موعد قادم','No upcoming date','لا يوجد موعد قادم','No upcoming date',true,now()),
  ('customer360.kpi.contracts','customers','crm','label','عقود العملاء','Customer Contracts','عقود العملاء','Customer Contracts',true,now()),
  ('customer360.kpi.open','customers','crm','format','المفتوحة: {count}','Open: {count}','المفتوحة: {count}','Open: {count}',true,now()),
  ('customer360.kpi.contractValue','customers','crm','label','قيمة العروض','Contract Value','قيمة العروض','Contract Value',true,now()),
  ('customer360.kpi.acceptedValue','customers','crm','format','المقبول: {value}','Accepted: {value}','المقبول: {value}','Accepted: {value}',true,now()),
  ('customer360.kpi.conversion','customers','crm','label','نسبة التحويل','Conversion Rate','نسبة التحويل','Conversion Rate',true,now()),
  ('customer360.kpi.acceptedContracts','customers','crm','format','{count} عروض مقبولة','{count} accepted contracts','{count} عروض مقبولة','{count} accepted contracts',true,now()),
  ('customer360.risk.health','customers','crm','label','صحة العميل','Customer Health','صحة العميل','Customer Health',true,now()),
  ('customer360.risk.score','customers','crm','label','درجة الخطر','Risk Score','درجة الخطر','Risk Score',true,now()),
  ('customer360.risk.priority','customers','crm','label','أولوية المتابعة','Follow-up Priority','أولوية المتابعة','Follow-up Priority',true,now()),
  ('customer360.risk.percent','customers','crm','format','{score}% خطر','{score}% risk','{score}% خطر','{score}% risk',true,now()),
  ('customer360.next.title','customers','crm','label','الإجراء التالي المقترح','Suggested Next Action','الإجراء التالي المقترح','Suggested Next Action',true,now()),
  ('customer360.next.engagement','customers','crm','format','التفاعل: {value}%','Engagement: {value}%','التفاعل: {value}%','Engagement: {value}%',true,now()),
  ('customer360.next.response','customers','crm','format','استجابة المتابعة: {value}%','Follow-up response: {value}%','استجابة المتابعة: {value}%','Follow-up response: {value}%',true,now()),
  ('customer360.value.accepted','customers','crm','label','قيمة العميل المقبولة','Accepted Customer Value','قيمة العميل المقبولة','Accepted Customer Value',true,now()),
  ('customer360.value.potential','customers','crm','label','القيمة المحتملة','Potential Value','القيمة المحتملة','Potential Value',true,now()),
  ('customer360.value.open','customers','crm','format','المفتوح: {value}','Open: {value}','المفتوح: {value}','Open: {value}',true,now()),
  ('customer360.value.rejected','customers','crm','label','قيمة العقود المرفوضة','Rejected Contract Value','قيمة العقود المرفوضة','Rejected Contract Value',true,now()),
  ('customer360.value.reviewOpportunities','customers','crm','label','فرص تحتاج مراجعة','Opportunities Needing Review','فرص تحتاج مراجعة','Opportunities Needing Review',true,now()),
  ('customer360.value.engagement','customers','crm','label','مؤشر التفاعل','Engagement Score','مؤشر التفاعل','Engagement Score',true,now()),
  ('customer360.value.response','customers','crm','format','استجابة: {value}%','Response: {value}%','استجابة: {value}%','Response: {value}%',true,now()),
  ('customer360.section.profile','customers','crm','label','البيانات الأساسية','Basic Information','البيانات الأساسية','Basic Information',true,now()),
  ('customer360.section.profileNote','customers','crm','label','ملخص بيانات العميل المسجلة في النظام.','Summary of customer data recorded in the system.','ملخص بيانات العميل المسجلة في النظام.','Summary of customer data recorded in the system.',true,now()),
  ('customer360.section.contracts','customers','crm','label','عقود العملاء','Customer Contracts','عقود العملاء','Customer Contracts',true,now()),
  ('customer360.section.contractsNote','customers','crm','label','جميع عروض السعر المرتبطة بالعميل.','All contracts linked to the customer.','جميع عروض السعر المرتبطة بالعميل.','All contracts linked to the customer.',true,now()),
  ('customer360.section.followupSummary','customers','crm','label','ملخص المتابعة','Follow-up Summary','ملخص المتابعة','Follow-up Summary',true,now()),
  ('customer360.section.followupSummaryNote','customers','crm','label','حالة مواعيد المتابعة الحالية.','Current follow-up schedule status.','حالة مواعيد المتابعة الحالية.','Current follow-up schedule status.',true,now()),
  ('customer360.section.latestFollowup','customers','crm','label','آخر متابعة','Latest Follow-up','آخر متابعة','Latest Follow-up',true,now()),
  ('customer360.section.latestFollowupNote','customers','crm','label','أحدث تواصل مسجل مع العميل.','Most recent recorded customer interaction.','أحدث تواصل مسجل مع العميل.','Most recent recorded customer interaction.',true,now()),
  ('customer360.section.activity','customers','crm','label','سجل النشاط الموحد','Unified Activity Log','سجل النشاط الموحد','Unified Activity Log',true,now()),
  ('customer360.section.activityNote','customers','crm','label','جميع أحداث العميل مرتبة من الأحدث إلى الأقدم.','All customer events ordered from newest to oldest.','جميع أحداث العميل مرتبة من الأحدث إلى الأقدم.','All customer events ordered from newest to oldest.',true,now()),
  ('customer360.section.followupHistory','customers','crm','label','سجل المتابعات','Follow-up History','سجل المتابعات','Follow-up History',true,now()),
  ('customer360.section.followupHistoryNote','customers','crm','label','جميع عمليات التواصل مرتبة من الأحدث إلى الأقدم.','All interactions ordered from newest to oldest.','جميع عمليات التواصل مرتبة من الأحدث إلى الأقدم.','All interactions ordered from newest to oldest.',true,now()),
  ('customer360.count.contracts','customers','crm','format','{count} عرض','{count} contracts','{count} عرض','{count} contracts',true,now()),
  ('customer360.count.events','customers','crm','format','{count} حدث','{count} events','{count} حدث','{count} events',true,now()),
  ('customer360.count.followups','customers','crm','format','{count} متابعة','{count} follow-ups','{count} متابعة','{count} follow-ups',true,now()),
  ('customer360.contract.noNumber','customers','crm','label','عرض بدون رقم','Contract Without Number','عرض بدون رقم','Contract Without Number',true,now()),
  ('customer360.empty.contracts','customers','crm','label','لا توجد عروض أسعار لهذا العميل.','No contracts for this customer.','لا توجد عروض أسعار لهذا العميل.','No contracts for this customer.',true,now()),
  ('customer360.empty.followups','customers','crm','label','لم تتم إضافة متابعات.','No follow-ups have been added.','لم تتم إضافة متابعات.','No follow-ups have been added.',true,now()),
  ('customer360.empty.customerFollowups','customers','crm','label','لم تتم إضافة متابعات لهذا العميل.','No follow-ups have been added for this customer.','لم تتم إضافة متابعات لهذا العميل.','No follow-ups have been added for this customer.',true,now()),
  ('customer360.empty.timelineType','customers','crm','label','لا توجد أحداث من هذا النوع.','No events of this type.','لا توجد أحداث من هذا النوع.','No events of this type.',true,now()),
  ('customer360.activity.latest','customers','crm','label','آخر نشاط','Latest Activity','آخر نشاط','Latest Activity',true,now()),
  ('customer360.activity.none','customers','crm','label','لا يوجد نشاط','No Activity','لا يوجد نشاط','No Activity',true,now()),
  ('customer360.activity.followups','customers','crm','label','المتابعات','Follow-ups','المتابعات','Follow-ups',true,now()),
  ('customer360.activity.followupsTotal','customers','crm','label','إجمالي المتابعات','Total Follow-ups','إجمالي المتابعات','Total Follow-ups',true,now()),
  ('customer360.activity.contracts','customers','crm','label','عقود العملاء','Customer Contracts','عقود العملاء','Customer Contracts',true,now()),
  ('customer360.activity.contractsTotal','customers','crm','label','إجمالي العروض','Total Contracts','إجمالي العروض','Total Contracts',true,now()),
  ('customer360.filter.all','customers','crm','label','الكل','All','الكل','All',true,now()),
  ('customer360.filter.followups','customers','crm','label','المتابعات','Follow-ups','المتابعات','Follow-ups',true,now()),
  ('customer360.filter.contracts','customers','crm','label','عقود العملاء','Customer Contracts','عقود العملاء','Customer Contracts',true,now()),
  ('customer360.filter.customer','customers','crm','label','بيانات العميل','Customer Data','بيانات العميل','Customer Data',true,now()),
  ('customer360.followup.contract','customers','crm','format','العقد: {number}','Contract: {number}','العقد: {number}','Contract: {number}',true,now()),
  ('customer360.followup.next','customers','crm','format','المتابعة القادمة: {date}','Next follow-up: {date}','المتابعة القادمة: {date}','Next follow-up: {date}',true,now()),
  ('customer360.timeline.noDate','customers','crm','label','بدون موعد','No Date','بدون موعد','No Date',true,now()),
  ('customer360.timeline.open','customers','crm','label','مفتوح','Open','مفتوح','Open',true,now()),
  ('customer360.timeline.info','customers','crm','label','معلومة','Info','معلومة','Info',true,now()),
  ('customer360.timeline.customerData','customers','crm','label','بيانات العميل','Customer Data','بيانات العميل','Customer Data',true,now()),
  ('customer360.timeline.customerCreated','customers','crm','label','إنشاء ملف العميل','Customer Profile Created','إنشاء ملف العميل','Customer Profile Created',true,now()),
  ('customer360.timeline.customerCreatedDetail','customers','crm','label','تم إنشاء ملف العميل في النظام.','Customer profile was created in the system.','تم إنشاء ملف العميل في النظام.','Customer profile was created in the system.',true,now()),
  ('customer360.timeline.followup','customers','crm','label','متابعة','Follow-up','متابعة','Follow-up',true,now()),
  ('customer360.timeline.followupCustomer','customers','crm','label','متابعة العميل','Customer Follow-up','متابعة العميل','Customer Follow-up',true,now()),
  ('customer360.timeline.followupRecorded','customers','crm','label','تم تسجيل متابعة للعميل.','A customer follow-up was recorded.','تم تسجيل متابعة للعميل.','A customer follow-up was recorded.',true,now()),
  ('customer360.timeline.contract','customers','crm','label','عرض سعر','Contract','عرض سعر','Contract',true,now()),
  ('customer360.status.active','customers','crm','label','نشط','Active','نشط','Active',true,now()),
  ('customer360.status.activeDetail','customers','crm','label','التواصل مع العميل ضمن النطاق الطبيعي.','Customer contact is within the normal range.','التواصل مع العميل ضمن النطاق الطبيعي.','Customer contact is within the normal range.',true,now()),
  ('customer360.status.overdue','customers','crm','label','متابعة متأخرة','Overdue Follow-up','متابعة متأخرة','Overdue Follow-up',true,now()),
  ('customer360.status.overdueDetail','customers','crm','label','يوجد موعد متابعة تجاوز تاريخه.','A follow-up date has passed.','يوجد موعد متابعة تجاوز تاريخه.','A follow-up date has passed.',true,now()),
  ('customer360.status.needsFollowup','customers','crm','label','يحتاج متابعة','Needs Follow-up','يحتاج متابعة','Needs Follow-up',true,now()),
  ('customer360.status.needsFollowupDetail','customers','crm','label','لم تتم إضافة أي متابعة للعميل.','No follow-up has been added for this customer.','لم تتم إضافة أي متابعة للعميل.','No follow-up has been added for this customer.',true,now()),
  ('customer360.status.inactive','customers','crm','label','غير نشط','Inactive','غير نشط','Inactive',true,now()),
  ('customer360.status.noContactDate','customers','crm','label','لا يوجد تاريخ تواصل واضح.','No clear contact date is available.','لا يوجد تاريخ تواصل واضح.','No clear contact date is available.',true,now()),
  ('customer360.status.daysSinceContact','customers','crm','format','مر {days} يومًا منذ آخر تواصل.','{days} days since the last contact.','مر {days} يومًا منذ آخر تواصل.','{days} days since the last contact.',true,now()),
  ('customer360.status.today','customers','crm','label','متابعة اليوم','Follow-up Today','متابعة اليوم','Follow-up Today',true,now()),
  ('customer360.status.todayDetail','customers','crm','label','يوجد موعد متابعة مستحق اليوم.','A follow-up is due today.','يوجد موعد متابعة مستحق اليوم.','A follow-up is due today.',true,now()),
  ('customer360.risk.noFollowup','customers','crm','label','لا توجد متابعة مسجلة للعميل.','No follow-up is recorded for this customer.','لا توجد متابعة مسجلة للعميل.','No follow-up is recorded for this customer.',true,now()),
  ('customer360.risk.overdueCount','customers','crm','format','يوجد {count} متابعة متأخرة.','There are {count} overdue follow-ups.','يوجد {count} متابعة متأخرة.','There are {count} overdue follow-ups.',true,now()),
  ('customer360.risk.noLastContact','customers','crm','label','لا يوجد تاريخ واضح لآخر تواصل.','No clear last-contact date.','لا يوجد تاريخ واضح لآخر تواصل.','No clear last-contact date.',true,now()),
  ('customer360.risk.daysSinceContact','customers','crm','format','مر {days} يومًا منذ آخر تواصل.','{days} days since the last contact.','مر {days} يومًا منذ آخر تواصل.','{days} days since the last contact.',true,now()),
  ('customer360.risk.inactiveDays','customers','crm','format','العميل غير نشط منذ {days} يومًا.','Customer has been inactive for {days} days.','العميل غير نشط منذ {days} يومًا.','Customer has been inactive for {days} days.',true,now()),
  ('customer360.risk.moreRejected','customers','crm','label','العروض المرفوضة أكثر من العروض المقبولة.','Rejected contracts exceed accepted contracts.','العروض المرفوضة أكثر من العروض المقبولة.','Rejected contracts exceed accepted contracts.',true,now()),
  ('customer360.risk.noAccepted','customers','crm','label','لا توجد عروض أسعار مقبولة حتى الآن.','No accepted contracts yet.','لا توجد عروض أسعار مقبولة حتى الآن.','No accepted contracts yet.',true,now()),
  ('customer360.risk.none','customers','crm','label','لا توجد مؤشرات خطر واضحة حاليًا.','No clear risk indicators currently.','لا توجد مؤشرات خطر واضحة حاليًا.','No clear risk indicators currently.',true,now()),
  ('customer360.priority.low','customers','crm','label','أولوية منخفضة','Low Priority','أولوية منخفضة','Low Priority',true,now()),
  ('customer360.priority.medium','customers','crm','label','أولوية متوسطة','Medium Priority','أولوية متوسطة','Medium Priority',true,now()),
  ('customer360.priority.high','customers','crm','label','أولوية مرتفعة','High Priority','أولوية مرتفعة','High Priority',true,now()),
  ('customer360.priority.critical','customers','crm','label','أولوية حرجة','Critical Priority','أولوية حرجة','Critical Priority',true,now()),
  ('customer360.next.periodic','customers','crm','label','استمرار المتابعة الدورية','Continue Periodic Follow-up','استمرار المتابعة الدورية','Continue Periodic Follow-up',true,now()),
  ('customer360.next.periodicDetail','customers','crm','label','لا توجد مشكلة عاجلة، حافظ على التواصل المنتظم مع العميل.','No urgent issue; maintain regular customer contact.','لا توجد مشكلة عاجلة، حافظ على التواصل المنتظم مع العميل.','No urgent issue; maintain regular customer contact.',true,now()),
  ('customer360.next.overdue','customers','crm','label','تنفيذ المتابعة المتأخرة فورًا','Handle Overdue Follow-up Now','تنفيذ المتابعة المتأخرة فورًا','Handle Overdue Follow-up Now',true,now()),
  ('customer360.next.overdueDetail','customers','crm','label','تواصل مع العميل وحدّث نتيجة المتابعة والموعد القادم.','Contact the customer and update the follow-up result and next date.','تواصل مع العميل وحدّث نتيجة المتابعة والموعد القادم.','Contact the customer and update the follow-up result and next date.',true,now()),
  ('customer360.next.firstFollowup','customers','crm','label','إنشاء أول متابعة','Create First Follow-up','إنشاء أول متابعة','Create First Follow-up',true,now()),
  ('customer360.next.firstFollowupDetail','customers','crm','label','حدد وسيلة التواصل وموعد المتابعة القادم.','Select the contact method and next follow-up date.','حدد وسيلة التواصل وموعد المتابعة القادم.','Select the contact method and next follow-up date.',true,now()),
  ('customer360.next.reactivate','customers','crm','label','إعادة تنشيط العميل','Reactivate Customer','إعادة تنشيط العميل','Reactivate Customer',true,now()),
  ('customer360.next.reactivateDetail','customers','crm','label','ابدأ تواصلًا جديدًا وحدد احتياجه الحالي قبل إرسال عرض جديد.','Start a new interaction and identify current needs before sending a new contract.','ابدأ تواصلًا جديدًا وحدد احتياجه الحالي قبل إرسال عرض جديد.','Start a new interaction and identify current needs before sending a new contract.',true,now()),
  ('customer360.next.openContracts','customers','crm','label','متابعة عروض الأسعار المفتوحة','Follow Up Open Contracts','متابعة عروض الأسعار المفتوحة','Follow Up Open Contracts',true,now()),
  ('customer360.next.openContractsDetail','customers','crm','format','يوجد {count} عرض مفتوح بقيمة {value} SAR.','There are {count} open contracts worth {value} SAR.','يوجد {count} عرض مفتوح بقيمة {value} SAR.','There are {count} open contracts worth {value} SAR.',true,now()),
  ('customer360.next.reviewConversion','customers','crm','label','مراجعة سبب عدم التحويل','Review Conversion Failure','مراجعة سبب عدم التحويل','Review Conversion Failure',true,now()),
  ('customer360.next.reviewConversionDetail','customers','crm','label','راجع أسباب الرفض وعدّل العرض أو أسلوب المتابعة.','Review rejection reasons and adjust the contract or follow-up approach.','راجع أسباب الرفض وعدّل العرض أو أسلوب المتابعة.','Review rejection reasons and adjust the contract or follow-up approach.',true,now()),
  ('customer360.valueTier.strategic','customers','crm','label','استراتيجي','Strategic','استراتيجي','Strategic',true,now()),
  ('customer360.valueTier.high','customers','crm','label','قيمة مرتفعة','High Value','قيمة مرتفعة','High Value',true,now()),
  ('customer360.valueTier.standard','customers','crm','label','قيمة متوسطة','Standard Value','قيمة متوسطة','Standard Value',true,now()),
  ('customer360.valueTier.new','customers','crm','label','فرصة جديدة','New Opportunity','فرصة جديدة','New Opportunity',true,now()),
  ('customer360.contractStatus.cancelled','customers','crm','label','ملغي','Cancelled','ملغي','Cancelled',true,now()),
  ('customerImport.title','customers','crm','label','استيراد العملاء من Excel','Import Customers from Excel','استيراد العملاء من Excel','Import Customers from Excel',true,now()),
  ('customerImport.note','customers','crm','label','تتم المعاينة والتحقق قبل حفظ أي بيانات.','Data is previewed and validated before anything is saved.','تتم المعاينة والتحقق قبل حفظ أي بيانات.','Data is previewed and validated before anything is saved.',true,now()),
  ('customerImport.chooseFile','customers','crm','label','اختيار ملف Excel','Choose Excel File','اختيار ملف Excel','Choose Excel File',true,now()),
  ('customerImport.noFile','customers','crm','label','لم يتم اختيار ملف','No file selected','لم يتم اختيار ملف','No file selected',true,now()),
  ('customerImport.progress.title','customers','crm','label','تقدم الاستيراد — رفع 200 عميل في كل دفعة','Import Progress — 200 customers per batch','تقدم الاستيراد — رفع 200 عميل في كل دفعة','Import Progress — 200 customers per batch',true,now()),
  ('customerImport.progress.success','customers','crm','label','نجح:','Succeeded:','نجح:','Succeeded:',true,now()),
  ('customerImport.progress.failed','customers','crm','label','فشل:','Failed:','فشل:','Failed:',true,now()),
  ('customerImport.progress.remaining','customers','crm','label','متبقي:','Remaining:','متبقي:','Remaining:',true,now()),
  ('customerImport.summary.total','customers','crm','label','إجمالي الصفوف','Total Rows','إجمالي الصفوف','Total Rows',true,now()),
  ('customerImport.summary.valid','customers','crm','label','صفوف صحيحة','Valid Rows','صفوف صحيحة','Valid Rows',true,now()),
  ('customerImport.summary.errors','customers','crm','label','صفوف بها أخطاء','Rows with Errors','صفوف بها أخطاء','Rows with Errors',true,now()),
  ('customerImport.summary.new','customers','crm','label','عملاء جدد','New Customers','عملاء جدد','New Customers',true,now()),
  ('customerImport.summary.existing','customers','crm','label','عملاء موجودون','Existing Customers','عملاء موجودون','Existing Customers',true,now()),
  ('customerImport.summary.duplicates','customers','crm','label','مكرر داخل الملف','Duplicates in File','مكرر داخل الملف','Duplicates in File',true,now()),
  ('customerImport.mode.label','customers','crm','label','طريقة التعامل مع العملاء الموجودين','How to Handle Existing Customers','طريقة التعامل مع العملاء الموجودين','How to Handle Existing Customers',true,now()),
  ('customerImport.mode.newOnly','customers','crm','label','إضافة الجدد فقط','Add New Only','إضافة الجدد فقط','Add New Only',true,now()),
  ('customerImport.mode.upsert','customers','crm','label','تحديث الموجود وإضافة الجدد','Update Existing and Add New','تحديث الموجود وإضافة الجدد','Update Existing and Add New',true,now()),
  ('customerImport.mode.skipExisting','customers','crm','label','تجاهل الموجود','Skip Existing','تجاهل الموجود','Skip Existing',true,now()),
  ('customerImport.col.status','customers','crm','label','الحالة','Status','الحالة','Status',true,now()),
  ('customerImport.col.notes','customers','crm','label','الملاحظات','Notes','الملاحظات','Notes',true,now()),
  ('customerImport.preview.empty','customers','crm','label','اختر ملف Excel لعرض المعاينة.','Choose an Excel file to preview.','اختر ملف Excel لعرض المعاينة.','Choose an Excel file to preview.',true,now()),
  ('customerImport.downloadFailed','customers','crm','label','تنزيل ملف الصفوف التي بها أخطاء','Download Rows with Errors','تنزيل ملف الصفوف التي بها أخطاء','Download Rows with Errors',true,now()),
  ('customerImport.downloadFailedCount','customers','crm','format','تنزيل ملف الصفوف التي بها أخطاء ({count})','Download Rows with Errors ({count})','تنزيل ملف الصفوف التي بها أخطاء ({count})','Download Rows with Errors ({count})',true,now()),
  ('customerImport.override.action','customers','crm','label','اعتماد استثنائي بالباسورد','Password Override','اعتماد استثنائي بالباسورد','Password Override',true,now()),
  ('customerImport.execute','customers','crm','label','اعتماد الاستيراد','Confirm Import','اعتماد الاستيراد','Confirm Import',true,now()),
  ('customerImport.override.title','customers','crm','label','اعتماد استيراد استثنائي','Exceptional Import Approval','اعتماد استيراد استثنائي','Exceptional Import Approval',true,now()),
  ('customerImport.override.note','customers','crm','label','متاح لمدير النظام فقط، ولن يتم رفع أي صف مكرر أو مرفوع مسبقًا.','Available to Super Admin only; duplicate or previously uploaded rows will not be uploaded.','متاح لمدير النظام فقط، ولن يتم رفع أي صف مكرر أو مرفوع مسبقًا.','Available to Super Admin only; duplicate or previously uploaded rows will not be uploaded.',true,now()),
  ('customerImport.override.password','customers','crm','label','كلمة مرور مدير النظام الحالية','Current Super Admin Password','كلمة مرور مدير النظام الحالية','Current Super Admin Password',true,now()),
  ('customerImport.override.confirm','customers','crm','label','تحقق واعتمد الاستيراد','Verify and Approve Import','تحقق واعتمد الاستيراد','Verify and Approve Import',true,now()),
  ('customerImport.status.error','customers','crm','error','خطأ','Error','خطأ','Error',true,now()),
  ('customerImport.status.existing','customers','crm','label','موجود','Existing','موجود','Existing',true,now()),
  ('customerImport.status.new','customers','crm','label','جديد','New','جديد','New',true,now()),
  ('customerImport.status.existingCustomer','customers','crm','label','عميل موجود','Existing Customer','عميل موجود','Existing Customer',true,now()),
  ('customerImport.status.ready','customers','crm','label','جاهز','Ready','جاهز','Ready',true,now()),
  ('customerImport.preview.limited','customers','crm','format','يتم عرض أول {limit} صف فقط من أصل {total} صف للحفاظ على سرعة الواجهة. سيتم استيراد جميع الصفوف الصحيحة.','Only the first {limit} of {total} rows are shown to keep the interface responsive. All valid rows will be imported.','يتم عرض أول {limit} صف فقط من أصل {total} صف للحفاظ على سرعة الواجهة. سيتم استيراد جميع الصفوف الصحيحة.','Only the first {limit} of {total} rows are shown to keep the interface responsive. All valid rows will be imported.',true,now()),
  ('customerImport.executeCount','customers','crm','format','اعتماد الاستيراد ({count})','Confirm Import ({count})','اعتماد الاستيراد ({count})','Confirm Import ({count})',true,now()),
  ('customerImport.noNewRows','customers','crm','label','لا توجد صفوف جديدة للاستيراد','No New Rows to Import','لا توجد صفوف جديدة للاستيراد','No New Rows to Import',true,now()),
  ('customerImport.noNewRowsTitle','customers','crm','label','جميع الصفوف مرفوعة مسبقًا أو تحتوي على أخطاء أو مكررة.','All rows were previously uploaded, contain errors, or are duplicates.','جميع الصفوف مرفوعة مسبقًا أو تحتوي على أخطاء أو مكررة.','All rows were previously uploaded, contain errors, or are duplicates.',true,now()),
  ('customerImport.override.count','customers','crm','format','اعتماد استثنائي بالباسورد ({count})','Password Override ({count})','اعتماد استثنائي بالباسورد ({count})','Password Override ({count})',true,now()),
  ('customerImport.override.none','customers','crm','label','لا توجد أخطاء قابلة للاستثناء','No Override-Eligible Errors','لا توجد أخطاء قابلة للاستثناء','No Override-Eligible Errors',true,now()),
  ('customerImport.override.passwordRequired','customers','crm','label','يتطلب كلمة مرور مدير النظام','Super Admin password required','يتطلب كلمة مرور مدير النظام','Super Admin password required',true,now()),
  ('customerImport.override.noneTitle','customers','crm','label','الأخطاء الحالية مكررة أو مرفوعة مسبقًا أو غير قابلة للتجاوز.','Current errors are duplicates, previously uploaded, or cannot be overridden.','الأخطاء الحالية مكررة أو مرفوعة مسبقًا أو غير قابلة للتجاوز.','Current errors are duplicates, previously uploaded, or cannot be overridden.',true,now()),
  ('customerImport.decision.normal','customers','crm','format','سيتم اعتماد {normal} صف جديد فقط. سيتم استبعاد {duplicate} صف مكرر أو مرفوع مسبقًا و{hard} صف بأخطاء غير قابلة للتجاوز.','Only {normal} new rows will be imported. {duplicate} duplicate/previously uploaded rows and {hard} non-overridable error rows will be excluded.','سيتم اعتماد {normal} صف جديد فقط. سيتم استبعاد {duplicate} صف مكرر أو مرفوع مسبقًا و{hard} صف بأخطاء غير قابلة للتجاوز.','Only {normal} new rows will be imported. {duplicate} duplicate/previously uploaded rows and {hard} non-overridable error rows will be excluded.',true,now()),
  ('customerImport.decision.override','customers','crm','format','لا توجد صفوف صحيحة جديدة. يمكن لمدير النظام اعتماد {count} صف بأخطاء قابلة للتجاوز بعد التحقق بكلمة المرور.','No new valid rows. Super Admin can approve {count} override-eligible rows after password verification.','لا توجد صفوف صحيحة جديدة. يمكن لمدير النظام اعتماد {count} صف بأخطاء قابلة للتجاوز بعد التحقق بكلمة المرور.','No new valid rows. Super Admin can approve {count} override-eligible rows after password verification.',true,now()),
  ('customerImport.decision.none','customers','crm','label','لا توجد صفوف جديدة قابلة للاستيراد. جميع الصفوف إما مرفوعة مسبقًا أو مكررة أو تحتوي على أخطاء غير قابلة للتجاوز.','No new rows can be imported. All rows are previously uploaded, duplicates, or contain non-overridable errors.','لا توجد صفوف جديدة قابلة للاستيراد. جميع الصفوف إما مرفوعة مسبقًا أو مكررة أو تحتوي على أخطاء غير قابلة للتجاوز.','No new rows can be imported. All rows are previously uploaded, duplicates, or contain non-overridable errors.',true,now()),
  ('customerImport.reading','customers','crm','label','جاري قراءة الملف والتحقق من البيانات...','Reading file and validating data...','جاري قراءة الملف والتحقق من البيانات...','Reading file and validating data...',true,now()),
  ('customerImport.checkedWithErrors','customers','crm','format','تم التحقق: سيتم استيراد {valid} صف صحيح وتجاهل {errors} صف به أخطاء.','Validated: {valid} valid rows will be imported and {errors} rows with errors will be skipped.','تم التحقق: سيتم استيراد {valid} صف صحيح وتجاهل {errors} صف به أخطاء.','Validated: {valid} valid rows will be imported and {errors} rows with errors will be skipped.',true,now()),
  ('customerImport.checkedReady','customers','crm','label','تم التحقق من الملف وهو جاهز للاستيراد.','File validated and ready to import.','تم التحقق من الملف وهو جاهز للاستيراد.','File validated and ready to import.',true,now()),
  ('customerImport.error.read','customers','crm','error','تعذر قراءة ملف Excel.','Unable to read the Excel file.','تعذر قراءة ملف Excel.','Unable to read the Excel file.',true,now()),
  ('customerImport.permission.import','customers','crm','label','لا توجد صلاحية استيراد العملاء.','You do not have permission to import customers.','لا توجد صلاحية استيراد العملاء.','You do not have permission to import customers.',true,now()),
  ('customerImport.permission.update','customers','crm','label','لا توجد صلاحية تحديث العملاء الموجودين.','You do not have permission to update existing customers.','لا توجد صلاحية تحديث العملاء الموجودين.','You do not have permission to update existing customers.',true,now()),
  ('customerImport.permission.export','customers','crm','label','لا توجد صلاحية تصدير بيانات العملاء.','You do not have permission to export customer data.','لا توجد صلاحية تصدير بيانات العملاء.','You do not have permission to export customer data.',true,now()),
  ('customerImport.permission.template','customers','crm','label','لا توجد صلاحية تنزيل نموذج العملاء.','You do not have permission to download the customer template.','لا توجد صلاحية تنزيل نموذج العملاء.','You do not have permission to download the customer template.',true,now()),
  ('customerImport.override.summaryTitle','customers','crm','label','ملخص الاستيراد الاستثنائي','Exceptional Import Summary','ملخص الاستيراد الاستثنائي','Exceptional Import Summary',true,now()),
  ('customerImport.override.validRows','customers','crm','format','صفوف صحيحة: {count}','Valid rows: {count}','صفوف صحيحة: {count}','Valid rows: {count}',true,now()),
  ('customerImport.override.warningRows','customers','crm','format','صفوف سيتم تجاوز تحذيراتها: {count}','Rows whose warnings will be overridden: {count}','صفوف سيتم تجاوز تحذيراتها: {count}','Rows whose warnings will be overridden: {count}',true,now()),
  ('customerImport.override.duplicateRows','customers','crm','format','صفوف مكررة أو مرفوعة مسبقًا لن تُرفع: {count}','Duplicate or previously uploaded rows not uploaded: {count}','صفوف مكررة أو مرفوعة مسبقًا لن تُرفع: {count}','Duplicate or previously uploaded rows not uploaded: {count}',true,now()),
  ('customerImport.override.hardRows','customers','crm','format','صفوف بأخطاء غير قابلة للتجاوز لن تُرفع: {count}','Rows with non-overridable errors not uploaded: {count}','صفوف بأخطاء غير قابلة للتجاوز لن تُرفع: {count}','Rows with non-overridable errors not uploaded: {count}',true,now()),
  ('customerImport.override.error.finalize','customers','crm','error','تعذر إغلاق سجل الاعتماد الاستثنائي.','Unable to finalize the exceptional approval audit.','تعذر إغلاق سجل الاعتماد الاستثنائي.','Unable to finalize the exceptional approval audit.',true,now()),
  ('customerImport.result.withNotes','customers','crm','label','اكتمل الاستيراد مع ملاحظات','Import Completed with Notes','اكتمل الاستيراد مع ملاحظات','Import Completed with Notes',true,now()),
  ('customerImport.result.saved','customers','crm','label','تم حفظ البيانات في Supabase بنجاح','Data saved successfully to Supabase','تم حفظ البيانات في Supabase بنجاح','Data saved successfully to Supabase',true,now()),
  ('customerImport.result.savedCount','customers','crm','format','العملاء المحفوظون أو المحدثون: {count}','Saved or updated customers: {count}','العملاء المحفوظون أو المحدثون: {count}','Saved or updated customers: {count}',true,now()),
  ('customerImport.result.overrideCount','customers','crm','format','الصفوف المعتمدة استثنائيًا: {count}','Exceptionally approved rows: {count}','الصفوف المعتمدة استثنائيًا: {count}','Exceptionally approved rows: {count}',true,now()),
  ('customerImport.result.skipped','customers','crm','format','المكرر أو المتجاهل: {count}','Duplicate or skipped: {count}','المكرر أو المتجاهل: {count}','Duplicate or skipped: {count}',true,now()),
  ('customerImport.result.failed','customers','crm','format','فشل الحفظ: {count}','Save failures: {count}','فشل الحفظ: {count}','Save failures: {count}',true,now()),
  ('customerImport.result.auditClosed','customers','crm','label','سجل الاعتماد: تم إغلاقه وتأكيده','Approval audit: closed and confirmed','سجل الاعتماد: تم إغلاقه وتأكيده','Approval audit: closed and confirmed',true,now()),
  ('customerImport.result.auditNotClosed','customers','crm','label','سجل الاعتماد: تعذر تأكيد إغلاقه','Approval audit: unable to confirm closure','سجل الاعتماد: تعذر تأكيد إغلاقه','Approval audit: unable to confirm closure',true,now()),
  ('customerImport.execute.noOverrideRows','customers','crm','label','لا توجد صفوف بأخطاء قابلة للاستثناء. الصفوف الحالية مكررة أو مرفوعة مسبقًا أو غير قابلة للتجاوز.','No override-eligible error rows. Current rows are duplicates, previously uploaded, or non-overridable.','لا توجد صفوف بأخطاء قابلة للاستثناء. الصفوف الحالية مكررة أو مرفوعة مسبقًا أو غير قابلة للتجاوز.','No override-eligible error rows. Current rows are duplicates, previously uploaded, or non-overridable.',true,now()),
  ('customerImport.execute.noRows','customers','crm','label','لا توجد صفوف جديدة قابلة للاستيراد. جميع الصفوف الحالية مرفوعة مسبقًا أو مكررة أو تحتوي على أخطاء.','No new rows can be imported. Current rows are previously uploaded, duplicates, or contain errors.','لا توجد صفوف جديدة قابلة للاستيراد. جميع الصفوف الحالية مرفوعة مسبقًا أو مكررة أو تحتوي على أخطاء.','No new rows can be imported. Current rows are previously uploaded, duplicates, or contain errors.',true,now()),
  ('customerImport.execute.nothingSent','customers','crm','label','لم يتم إرسال أي بيانات إلى Supabase لعدم وجود صفوف جديدة قابلة للحفظ.','No data was sent to Supabase because there are no new savable rows.','لم يتم إرسال أي بيانات إلى Supabase لعدم وجود صفوف جديدة قابلة للحفظ.','No data was sent to Supabase because there are no new savable rows.',true,now()),
  ('customerImport.progress.start','customers','crm','format','بدء الرفع على دفعات بحد أقصى 200 عميل لكل دفعة — 0 من {total} (0%)','Starting batched upload, up to 200 customers per batch — 0 of {total} (0%)','بدء الرفع على دفعات بحد أقصى 200 عميل لكل دفعة — 0 من {total} (0%)','Starting batched upload, up to 200 customers per batch — 0 of {total} (0%)',true,now()),
  ('customerImport.progress.batch','customers','crm','format',' — الدفعة {index} من {total} ({size} عميل)',' — batch {index} of {total} ({size} customers)',' — الدفعة {index} من {total} ({size} عميل)',' — batch {index} of {total} ({size} customers)',true,now()),
  ('customerImport.progress.uploading','customers','crm','format','جاري الرفع: {current} من {total} — {percent}%{batch}','Uploading: {current} of {total} — {percent}%{batch}','جاري الرفع: {current} من {total} — {percent}%{batch}','Uploading: {current} of {total} — {percent}%{batch}',true,now()),
  ('customerImport.complete','customers','crm','format','اكتمل الاستيراد وتم تنفيذ الحفظ في Supabase: {inserted} جديد، {updated} تحديث، {skipped} مكرر أو متجاهل، {failed} فشل{override}.','Import completed and saved to Supabase: {inserted} new, {updated} updated, {skipped} duplicate/skipped, {failed} failed{override}.','اكتمل الاستيراد وتم تنفيذ الحفظ في Supabase: {inserted} جديد، {updated} تحديث، {skipped} مكرر أو متجاهل، {failed} فشل{override}.','Import completed and saved to Supabase: {inserted} new, {updated} updated, {skipped} duplicate/skipped, {failed} failed{override}.',true,now()),
  ('customerImport.completeOverride','customers','crm','format','، {count} صف باعتماد استثنائي',', {count} exceptionally approved rows','، {count} صف باعتماد استثنائي',', {count} exceptionally approved rows',true,now()),
  ('customerImport.error.execute','customers','crm','error','تعذر تنفيذ الاستيراد.','Unable to execute the import.','تعذر تنفيذ الاستيراد.','Unable to execute the import.',true,now()),
  ('customerImport.override.superAdminOnly','customers','crm','label','هذا الإجراء متاح لمدير النظام فقط.','This action is available to Super Admin only.','هذا الإجراء متاح لمدير النظام فقط.','This action is available to Super Admin only.',true,now()),
  ('customerImport.override.passwordMissing','customers','crm','label','أدخل كلمة مرور مدير النظام.','Enter the Super Admin password.','أدخل كلمة مرور مدير النظام.','Enter the Super Admin password.',true,now()),
  ('customerImport.override.verifying','customers','crm','label','جاري التحقق من الهوية والصلاحية...','Verifying identity and permission...','جاري التحقق من الهوية والصلاحية...','Verifying identity and permission...',true,now()),
  ('customerImport.override.error.email','customers','crm','error','تعذر تحديد بريد مدير النظام الحالي.','Unable to determine the current Super Admin email.','تعذر تحديد بريد مدير النظام الحالي.','Unable to determine the current Super Admin email.',true,now()),
  ('customerImport.override.error.password','customers','crm','error','كلمة المرور غير صحيحة.','Incorrect password.','كلمة المرور غير صحيحة.','Incorrect password.',true,now()),
  ('customerImport.override.error.sessionChanged','customers','crm','error','تم رفض الاعتماد لأن جلسة المستخدم تغيرت أثناء التحقق.','Approval was rejected because the user session changed during verification.','تم رفض الاعتماد لأن جلسة المستخدم تغيرت أثناء التحقق.','Approval was rejected because the user session changed during verification.',true,now()),
  ('customerImport.override.error.audit','customers','crm','error','تعذر إنشاء سجل الاعتماد الاستثنائي.','Unable to create the exceptional approval audit.','تعذر إنشاء سجل الاعتماد الاستثنائي.','Unable to create the exceptional approval audit.',true,now()),
  ('customerImport.override.error.verify','customers','crm','error','تعذر التحقق.','Unable to verify.','تعذر التحقق.','Unable to verify.',true,now()),
  ('customerImport.error.exportFailed','customers','crm','error','تعذر تصدير الصفوف الفاشلة.','Unable to export failed rows.','تعذر تصدير الصفوف الفاشلة.','Unable to export failed rows.',true,now()),
  ('customerImport.export.success','customers','crm','format','تم تصدير {count} عميل إلى Excel.','Exported {count} customers to Excel.','تم تصدير {count} عميل إلى Excel.','Exported {count} customers to Excel.',true,now()),
  ('customerImport.export.error','customers','crm','error','تعذر تصدير بيانات العملاء.','Unable to export customer data.','تعذر تصدير بيانات العملاء.','Unable to export customer data.',true,now()),
  ('customerImport.template.success','customers','crm','label','تم تنزيل نموذج استيراد العملاء.','Customer import template downloaded.','تم تنزيل نموذج استيراد العملاء.','Customer import template downloaded.',true,now()),
  ('customerImport.template.error','customers','crm','error','تعذر تنزيل النموذج.','Unable to download the template.','تعذر تنزيل النموذج.','Unable to download the template.',true,now()),
  ('customerImport.error.codeRequired','customers','crm','error','code مطلوب','code is required','code مطلوب','code is required',true,now()),
  ('customerImport.error.nameRequired','customers','crm','error','name مطلوب','name is required','name مطلوب','name is required',true,now()),
  ('customerImport.error.mobileInvalid','customers','crm','error','mobile غير صالح','mobile is invalid','mobile غير صالح','mobile is invalid',true,now()),
  ('customerImport.error.mobileDuplicateFile','customers','crm','error','mobile مكرر داخل الملف','mobile is duplicated in the file','mobile مكرر داخل الملف','mobile is duplicated in the file',true,now()),
  ('customerImport.error.codeDuplicateFile','customers','crm','error','code مكرر داخل الملف','code is duplicated in the file','code مكرر داخل الملف','code is duplicated in the file',true,now()),
  ('customerImport.service.xlsxMissing','customers','crm','error','مكتبة Excel غير محملة.','Excel library is not loaded.','مكتبة Excel غير محملة.','Excel library is not loaded.',true,now()),
  ('customerImport.service.fileFirst','customers','crm','error','اختر ملف Excel أولًا.','Choose an Excel file first.','اختر ملف Excel أولًا.','Choose an Excel file first.',true,now()),
  ('customerImport.service.noRows','customers','crm','error','ملف Excel لا يحتوي على صفوف عملاء.','The Excel file contains no customer rows.','ملف Excel لا يحتوي على صفوف عملاء.','The Excel file contains no customer rows.',true,now()),
  ('customerImport.service.requiredColumns','customers','crm','error','الملف يجب أن يحتوي على الأعمدة: code, name, address, mobile.','The file must contain the columns: code, name, address, mobile.','الملف يجب أن يحتوي على الأعمدة: code, name, address, mobile.','The file must contain the columns: code, name, address, mobile.',true,now()),
  ('customerImport.service.noFailedRows','customers','crm','error','لا توجد صفوف فاشلة للتصدير.','There are no failed rows to export.','لا توجد صفوف فاشلة للتصدير.','There are no failed rows to export.',true,now()),
  ('crmService.supabaseNotReady','shared','crm','error','اتصال Supabase غير جاهز.','Supabase connection is not ready.','اتصال Supabase غير جاهز.','Supabase connection is not ready.',true,now()),
  ('crmService.customer.phoneExists','shared','crm','error','رقم الجوال مسجل بالفعل لعميل آخر.','The mobile number is already registered to another customer.','رقم الجوال مسجل بالفعل لعميل آخر.','The mobile number is already registered to another customer.',true,now()),
  ('crmService.customer.invalidReference','shared','crm','error','تعذر الحفظ بسبب ارتباط مرجعي غير صالح.','Unable to save because of an invalid reference.','تعذر الحفظ بسبب ارتباط مرجعي غير صالح.','Unable to save because of an invalid reference.',true,now()),
  ('crmService.customer.nameRequired','shared','crm','error','اسم العميل مطلوب.','Customer name is required.','اسم العميل مطلوب.','Customer name is required.',true,now()),
  ('crmService.customer.phoneRequired','shared','crm','error','رقم الجوال مطلوب.','Mobile number is required.','رقم الجوال مطلوب.','Mobile number is required.',true,now()),
  ('crmService.customer.codeRequired','shared','crm','error','كود العميل مطلوب.','Customer code is required.','كود العميل مطلوب.','Customer code is required.',true,now()),
  ('crmService.customer.neighborhoodRequired','shared','crm','error','اختر الحي من قائمة الأحياء.','Select a district from the district list.','اختر الحي من قائمة الأحياء.','Select a district from the district list.',true,now()),
  ('crmService.customer.neighborhoodInactive','shared','crm','error','الحي المختار غير موجود أو غير نشط.','The selected district does not exist or is inactive.','الحي المختار غير موجود أو غير نشط.','The selected district does not exist or is inactive.',true,now()),
  ('crmService.customer.conflict','shared','crm','error','تم تعديل العميل على الخادم بعد آخر مزامنة.','The customer was modified on the server after the last sync.','تم تعديل العميل على الخادم بعد آخر مزامنة.','The customer was modified on the server after the last sync.',true,now()),
  ('crmService.customer.deleteUnsynced','shared','crm','error','لا يمكن حذف عميل لم تتم مزامنته بعد. انتظر اكتمال المزامنة أولًا.','A customer that has not yet synced cannot be deleted. Wait for sync to complete.','لا يمكن حذف عميل لم تتم مزامنته بعد. انتظر اكتمال المزامنة أولًا.','A customer that has not yet synced cannot be deleted. Wait for sync to complete.',true,now()),
  ('crmService.customer.deleteOfflineTimestamp','shared','crm','error','تعذر حذف العميل Offline لأن نسخة السجل المحلية لا تحتوي وقت آخر تحديث. افتح البيانات Online ثم أعد المحاولة.','Unable to delete the customer offline because the local record has no last-update timestamp. Open the data online and try again.','تعذر حذف العميل Offline لأن نسخة السجل المحلية لا تحتوي وقت آخر تحديث. افتح البيانات Online ثم أعد المحاولة.','Unable to delete the customer offline because the local record has no last-update timestamp. Open the data online and try again.',true,now()),
  ('crmService.customer.deleteIncomplete','shared','crm','error','بيانات العميل غير مكتملة للحذف.','Customer data is incomplete for deletion.','بيانات العميل غير مكتملة للحذف.','Customer data is incomplete for deletion.',true,now()),
  ('crmService.followup.invalidReference','shared','crm','error','تعذر الحفظ بسبب ارتباط العميل أو المندوب أو سبب عدم البيع.','Unable to save because of the customer, representative, or no-sale reason reference.','تعذر الحفظ بسبب ارتباط العميل أو المندوب أو سبب عدم البيع.','Unable to save because of the customer, representative, or no-sale reason reference.',true,now()),
  ('crmService.followup.conflict','shared','crm','error','تم تعديل المتابعة على الخادم بعد آخر مزامنة.','The follow-up was modified on the server after the last sync.','تم تعديل المتابعة على الخادم بعد آخر مزامنة.','The follow-up was modified on the server after the last sync.',true,now()),
  ('crmService.followup.parentPending','shared','crm','error','تعذر ربط المتابعة بالعميل المحلي المعلق.','Unable to link the follow-up to the pending local customer.','تعذر ربط المتابعة بالعميل المحلي المعلق.','Unable to link the follow-up to the pending local customer.',true,now()),
  ('crmService.followup.deleteUnsynced','shared','crm','error','لا يمكن حذف متابعة لم تتم مزامنتها بعد. انتظر اكتمال المزامنة أولًا.','A follow-up that has not yet synced cannot be deleted. Wait for sync to complete.','لا يمكن حذف متابعة لم تتم مزامنتها بعد. انتظر اكتمال المزامنة أولًا.','A follow-up that has not yet synced cannot be deleted. Wait for sync to complete.',true,now()),
  ('crmService.followup.deleteOfflineTimestamp','shared','crm','error','تعذر حذف المتابعة Offline لأن نسخة السجل المحلية لا تحتوي وقت آخر تحديث.','Unable to delete the follow-up offline because the local record has no last-update timestamp.','تعذر حذف المتابعة Offline لأن نسخة السجل المحلية لا تحتوي وقت آخر تحديث.','Unable to delete the follow-up offline because the local record has no last-update timestamp.',true,now()),
  ('crmService.followup.deleteIncomplete','shared','crm','error','بيانات المتابعة غير مكتملة للحذف.','Follow-up data is incomplete for deletion.','بيانات المتابعة غير مكتملة للحذف.','Follow-up data is incomplete for deletion.',true,now()),
  ('crmService.followup.customerNotSynced','shared','crm','error','لم تتم مزامنة العميل المرتبط بالمتابعة بعد.','The customer linked to the follow-up has not synced yet.','لم تتم مزامنة العميل المرتبط بالمتابعة بعد.','The customer linked to the follow-up has not synced yet.',true,now()),
  ('crmService.contract.numberExists','shared','crm','error','رقم العقد مسجل بالفعل ولا يمكن تكراره.','The contract number is already registered and cannot be duplicated.','رقم العقد مسجل بالفعل ولا يمكن تكراره.','The contract number is already registered and cannot be duplicated.',true,now()),
  ('crmService.contract.invalidReference','shared','crm','error','تعذر الحفظ بسبب ارتباط العميل أو المندوب أو سبب الرفض.','Unable to save because of the customer, representative, or rejection-reason reference.','تعذر الحفظ بسبب ارتباط العميل أو المندوب أو سبب الرفض.','Unable to save because of the customer, representative, or rejection-reason reference.',true,now()),
  ('crmService.contract.conflict','shared','crm','error','تم تعديل العقد على الخادم بعد آخر مزامنة.','The contract was modified on the server after the last sync.','تم تعديل العقد على الخادم بعد آخر مزامنة.','The contract was modified on the server after the last sync.',true,now()),
  ('crmService.contract.parentPending','shared','crm','error','تعذر ربط العقد بالعميل المحلي المعلق.','Unable to link the contract to the pending local customer.','تعذر ربط العقد بالعميل المحلي المعلق.','Unable to link the contract to the pending local customer.',true,now()),
  ('crmService.contract.deleteUnsynced','shared','crm','error','لا يمكن حذف عقد لم تتم مزامنته بعد. انتظر اكتمال المزامنة أولًا.','A contract that has not yet synced cannot be deleted. Wait for sync to complete.','لا يمكن حذف عقد لم تتم مزامنته بعد. انتظر اكتمال المزامنة أولًا.','A contract that has not yet synced cannot be deleted. Wait for sync to complete.',true,now()),
  ('crmService.contract.deleteOfflineTimestamp','shared','crm','error','تعذر حذف العقد Offline لأن نسخة السجل المحلية لا تحتوي وقت آخر تحديث.','Unable to delete the contract offline because the local record has no last-update timestamp.','تعذر حذف العقد Offline لأن نسخة السجل المحلية لا تحتوي وقت آخر تحديث.','Unable to delete the contract offline because the local record has no last-update timestamp.',true,now()),
  ('crmService.contract.deleteIncomplete','shared','crm','error','بيانات العقد غير مكتملة للحذف.','Contract data is incomplete for deletion.','بيانات العقد غير مكتملة للحذف.','Contract data is incomplete for deletion.',true,now()),
  ('crmService.contract.customerNotSynced','shared','crm','error','لم تتم مزامنة العميل المرتبط بالعقد بعد.','The customer linked to the contract has not synced yet.','لم تتم مزامنة العميل المرتبط بالعقد بعد.','The customer linked to the contract has not synced yet.',true,now()),
  ('crmService.customer.count','shared','crm','error','تعذر التحقق من عدد العملاء:','Unable to verify customer count:','تعذر التحقق من عدد العملاء:','Unable to verify customer count:',true,now()),
  ('crmService.customer.currentUser','shared','crm','error','تعذر تحديد المستخدم الحالي:','Unable to determine the current user:','تعذر تحديد المستخدم الحالي:','Unable to determine the current user:',true,now()),
  ('crmService.customer.requestSave','shared','crm','error','تعذر حفظ طلب العميل:','Unable to save the customer request:','تعذر حفظ طلب العميل:','Unable to save the customer request:',true,now()),
  ('crmService.followup.todayLoad','shared','crm','error','تعذر تحميل متابعات اليوم:','Unable to load today’s follow-ups:','تعذر تحميل متابعات اليوم:','Unable to load today’s follow-ups:',true,now()),
  ('crmService.followup.overdueLoad','shared','crm','error','تعذر تحميل المتابعات المتأخرة:','Unable to load overdue follow-ups:','تعذر تحميل المتابعات المتأخرة:','Unable to load overdue follow-ups:',true,now()),
  ('crmService.followup.currentUser','shared','crm','error','تعذر تحديد المستخدم الحالي:','Unable to determine the current user:','تعذر تحديد المستخدم الحالي:','Unable to determine the current user:',true,now()),
  ('crmService.contract.currentUser','shared','crm','error','تعذر تحديد المستخدم الحالي:','Unable to determine the current user:','تعذر تحديد المستخدم الحالي:','Unable to determine the current user:',true,now()),
  ('crmService.customer.loadDeleteLog','shared','crm','error','تعذر تحميل سجل حذف العملاء','Unable to load customer deletion log','تعذر تحميل سجل حذف العملاء','Unable to load customer deletion log',true,now()),
  ('crmService.customer.load','shared','crm','error','تعذر تحميل العملاء','Unable to load customers','تعذر تحميل العملاء','Unable to load customers',true,now()),
  ('crmService.customer.loadOne','shared','crm','error','تعذر تحميل بيانات العميل','Unable to load customer data','تعذر تحميل بيانات العميل','Unable to load customer data',true,now()),
  ('crmService.customer.performance','shared','crm','error','تعذر تحميل عملاء تقرير الأداء','Unable to load customers for the performance report','تعذر تحميل عملاء تقرير الأداء','Unable to load customers for the performance report',true,now()),
  ('crmService.customer.phoneCheck','shared','crm','error','تعذر التحقق من رقم الجوال','Unable to verify the mobile number','تعذر التحقق من رقم الجوال','Unable to verify the mobile number',true,now()),
  ('crmService.customer.neighborhoodCheck','shared','crm','error','تعذر التحقق من الحي المختار','Unable to verify the selected district','تعذر التحقق من الحي المختار','Unable to verify the selected district',true,now()),
  ('crmService.customer.edit','shared','crm','error','تعذر تعديل العميل','Unable to update the customer','تعذر تعديل العميل','Unable to update the customer',true,now()),
  ('crmService.customer.add','shared','crm','error','تعذر إضافة العميل','Unable to add the customer','تعذر إضافة العميل','Unable to add the customer',true,now()),
  ('crmService.customer.delete','shared','crm','error','تعذر حذف العميل','Unable to delete the customer','تعذر حذف العميل','Unable to delete the customer',true,now()),
  ('crmService.followup.loadDeleteLog','shared','crm','error','تعذر تحميل سجل حذف المتابعات','Unable to load follow-up deletion log','تعذر تحميل سجل حذف المتابعات','Unable to load follow-up deletion log',true,now()),
  ('crmService.followup.load','shared','crm','error','تعذر تحميل المتابعات','Unable to load follow-ups','تعذر تحميل المتابعات','Unable to load follow-ups',true,now()),
  ('crmService.followup.edit','shared','crm','error','تعذر تعديل المتابعة','Unable to update the follow-up','تعذر تعديل المتابعة','Unable to update the follow-up',true,now()),
  ('crmService.followup.add','shared','crm','error','تعذر إضافة المتابعة','Unable to add the follow-up','تعذر إضافة المتابعة','Unable to add the follow-up',true,now()),
  ('crmService.followup.delete','shared','crm','error','تعذر حذف المتابعة','Unable to delete the follow-up','تعذر حذف المتابعة','Unable to delete the follow-up',true,now()),
  ('crmService.contract.loadDeleteLog','shared','crm','error','تعذر تحميل سجل حذف العقود','Unable to load contract deletion log','تعذر تحميل سجل حذف العقود','Unable to load contract deletion log',true,now()),
  ('crmService.contract.load','shared','crm','error','تعذر تحميل عقود العملاء','Unable to load customer contracts','تعذر تحميل عقود العملاء','Unable to load customer contracts',true,now()),
  ('crmService.contract.performance','shared','crm','error','تعذر تحميل عروض تقرير الأداء','Unable to load contracts for the performance report','تعذر تحميل عروض تقرير الأداء','Unable to load contracts for the performance report',true,now()),
  ('crmService.contract.numberCheck','shared','crm','error','تعذر التحقق من رقم العقد','Unable to verify the contract number','تعذر التحقق من رقم العقد','Unable to verify the contract number',true,now()),
  ('crmService.contract.edit','shared','crm','error','تعذر تعديل العقد','Unable to update the contract','تعذر تعديل العقد','Unable to update the contract',true,now()),
  ('crmService.contract.add','shared','crm','error','تعذر إضافة العقد','Unable to add the contract','تعذر إضافة العقد','Unable to add the contract',true,now()),
  ('crmService.contract.delete','shared','crm','error','تعذر حذف العقد','Unable to delete the contract','تعذر حذف العقد','Unable to delete the contract',true,now()),
  ('pwa.update.release.r44r33.title','shared','core','title','استكمال ترجمة تقارير CRM وCustomer 360 والاستيراد','CRM Reports, Customer 360 & Import Localization','استكمال ترجمة تقارير CRM وCustomer 360 والاستيراد','CRM Reports, Customer 360 & Import Localization',true,now()),
  ('pwa.update.release.r44r33.note1','shared','core','help','استكمال ترجمة مركز التقارير والتحليلات وCustomer 360 ورسائل التشغيل الديناميكية.','Completes localization for Reports & Analytics, Customer 360, and dynamic runtime messages.','استكمال ترجمة مركز التقارير والتحليلات وCustomer 360 ورسائل التشغيل الديناميكية.','Completes localization for Reports & Analytics, Customer 360, and dynamic runtime messages.',true,now()),
  ('pwa.update.release.r44r33.note2','shared','core','help','استكمال ترجمة واجهة استيراد وتصدير العملاء ورسائل Excel مع الحفاظ على منطق التحقق الداخلي كما هو.','Completes customer Excel import/export UI and messages while preserving internal validation logic.','استكمال ترجمة واجهة استيراد وتصدير العملاء ورسائل Excel مع الحفاظ على منطق التحقق الداخلي كما هو.','Completes customer Excel import/export UI and messages while preserving internal validation logic.',true,now()),
  ('pwa.update.release.r44r33.note3','shared','core','help','إضافة ترجمة Display Layer لرسائل خدمات CRM دون تغيير عقود Offline/Sync أو منطق الأعمال.','Adds display-layer localization for CRM service messages without changing Offline/Sync contracts or business logic.','إضافة ترجمة Display Layer لرسائل خدمات CRM دون تغيير عقود Offline/Sync أو منطق الأعمال.','Adds display-layer localization for CRM service messages without changing Offline/Sync contracts or business logic.',true,now()),
  ('customerImport.runtime.xlsxStart','customers','crm','error','مكتبة Excel لم تبدأ بشكل صحيح.','Excel library did not start correctly.','مكتبة Excel لم تبدأ بشكل صحيح.','Excel library did not start correctly.',true,now()),
  ('customerImport.runtime.xlsxLoad','customers','crm','error','تعذر تحميل مكتبة Excel. تحقق من الاتصال بالإنترنت.','Unable to load the Excel library. Check your internet connection.','تعذر تحميل مكتبة Excel. تحقق من الاتصال بالإنترنت.','Unable to load the Excel library. Check your internet connection.',true,now()),
  ('customerImport.runtime.functionMissing','customers','crm','format','تعذر تحميل وظيفة {name}. نفذ Hard Refresh ثم أعد المحاولة.','Unable to load function {name}. Perform a Hard Refresh and try again.','تعذر تحميل وظيفة {name}. نفذ Hard Refresh ثم أعد المحاولة.','Unable to load function {name}. Perform a Hard Refresh and try again.',true,now()),
  ('customerImport.runtime.dialogMissing','customers','crm','error','نافذة استيراد العملاء غير موجودة.','Customer import dialog was not found.','نافذة استيراد العملاء غير موجودة.','Customer import dialog was not found.',true,now()),
  ('customerImport.runtime.centerMissing','customers','crm','error','مركز Excel للعملاء غير محمل.','Customer Excel Center is not loaded.','مركز Excel للعملاء غير محمل.','Customer Excel Center is not loaded.',true,now()),
  ('customerImport.runtime.openError','customers','crm','error','تعذر فتح الاستيراد.','Unable to open customer import.','تعذر فتح الاستيراد.','Unable to open customer import.',true,now()),
  ('customerImport.runtime.overrideOpenError','customers','crm','error','تعذر فتح الاعتماد الاستثنائي.','Unable to open exceptional approval.','تعذر فتح الاعتماد الاستثنائي.','Unable to open exceptional approval.',true,now()),
  ('customerImport.runtime.engineMissing','customers','crm','error','تعذر تحميل محرك الاستيراد. نفذ Hard Refresh ثم أعد المحاولة.','Unable to load the import engine. Perform a Hard Refresh and try again.','تعذر تحميل محرك الاستيراد. نفذ Hard Refresh ثم أعد المحاولة.','Unable to load the import engine. Perform a Hard Refresh and try again.',true,now()),
  ('customers.permission.add','customers','crm','error','لا توجد صلاحية إضافة العملاء.','You do not have permission to add customers.','لا توجد صلاحية إضافة العملاء.','You do not have permission to add customers.',true,now()),
  ('customers.permission.edit','customers','crm','error','لا توجد صلاحية تعديل العملاء.','You do not have permission to edit customers.','لا توجد صلاحية تعديل العملاء.','You do not have permission to edit customers.',true,now()),
  ('customers.permission.save','customers','crm','error','لا توجد صلاحية حفظ العملاء.','You do not have permission to save customers.','لا توجد صلاحية حفظ العملاء.','You do not have permission to save customers.',true,now()),
  ('customers.permission.manage','customers','crm','error','لا توجد صلاحية لتعديل بيانات العملاء.','You do not have permission to manage customer data.','لا توجد صلاحية لتعديل بيانات العملاء.','You do not have permission to manage customer data.',true,now()),
  ('customers.permission.delete','customers','crm','error','لا توجد صلاحية حذف العملاء.','You do not have permission to delete customers.','لا توجد صلاحية حذف العملاء.','You do not have permission to delete customers.',true,now()),
  ('customers.permission.deleteAdmin','customers','crm','error','حذف العملاء متاح للإدارة فقط.','Customer deletion is available to management only.','حذف العملاء متاح للإدارة فقط.','Customer deletion is available to management only.',true,now()),
  ('customers.validation.neighborhood','customers','crm','error','اختر الحي من القائمة.','Select a district from the list.','اختر الحي من القائمة.','Select a district from the list.',true,now()),
  ('customers.validation.code','customers','crm','error','أدخل كود العميل.','Enter the customer code.','أدخل كود العميل.','Enter the customer code.',true,now()),
  ('customers.validation.name','customers','crm','error','أدخل اسم العميل.','Enter the customer name.','أدخل اسم العميل.','Enter the customer name.',true,now()),
  ('customers.validation.mobile','customers','crm','error','أدخل رقم جوال سعودي صحيحًا بصيغة 05XXXXXXXX.','Enter a valid Saudi mobile number in the format 05XXXXXXXX.','أدخل رقم جوال سعودي صحيحًا بصيغة 05XXXXXXXX.','Enter a valid Saudi mobile number in the format 05XXXXXXXX.',true,now()),
  ('customers.error.loadOne','customers','crm','error','تعذر تحميل بيانات العميل.','Unable to load customer data.','تعذر تحميل بيانات العميل.','Unable to load customer data.',true,now()),
  ('customers.error.save','customers','crm','error','تعذر حفظ العميل.','Unable to save the customer.','تعذر حفظ العميل.','Unable to save the customer.',true,now()),
  ('customers.error.delete','customers','crm','error','تعذر حذف العميل.','Unable to delete the customer.','تعذر حذف العميل.','Unable to delete the customer.',true,now()),
  ('customers.confirm.delete','customers','crm','confirm','هل تريد حذف العميل: {name}؟ سيتم حذف السجلات المرتبطة به وفق قواعد قاعدة البيانات.','Delete customer {name}? Linked records will be deleted according to database rules.','هل تريد حذف العميل: {name}؟ سيتم حذف السجلات المرتبطة به وفق قواعد قاعدة البيانات.','Delete customer {name}? Linked records will be deleted according to database rules.',true,now()),
  ('followups.permission.add','followups','crm','error','لا توجد صلاحية إضافة المتابعات.','You do not have permission to add follow-ups.','لا توجد صلاحية إضافة المتابعات.','You do not have permission to add follow-ups.',true,now()),
  ('followups.permission.edit','followups','crm','error','لا توجد صلاحية تعديل المتابعات.','You do not have permission to edit follow-ups.','لا توجد صلاحية تعديل المتابعات.','You do not have permission to edit follow-ups.',true,now()),
  ('followups.permission.save','followups','crm','error','لا توجد صلاحية حفظ المتابعات.','You do not have permission to save follow-ups.','لا توجد صلاحية حفظ المتابعات.','You do not have permission to save follow-ups.',true,now()),
  ('followups.permission.manage','followups','crm','error','لا توجد صلاحية لإدارة المتابعات.','You do not have permission to manage follow-ups.','لا توجد صلاحية لإدارة المتابعات.','You do not have permission to manage follow-ups.',true,now()),
  ('followups.warning.suggestionUpdate','followups','crm','format','تم حفظ المتابعة، ولكن تعذر تحديث قائمة العملاء المقترحين: {error}','The follow-up was saved, but the suggested customers list could not be updated: {error}','تم حفظ المتابعة، ولكن تعذر تحديث قائمة العملاء المقترحين: {error}','The follow-up was saved, but the suggested customers list could not be updated: {error}',true,now()),
  ('followups.error.delete','followups','crm','error','تعذر حذف المتابعة.','Unable to delete the follow-up.','تعذر حذف المتابعة.','Unable to delete the follow-up.',true,now()),
  ('shared.error.unknown','shared','core','error','خطأ غير معروف','Unknown error','خطأ غير معروف','Unknown error',true,now()),
  ('contracts.permission.add','quotations','crm','error','لا توجد صلاحية إضافة عقود العملاء.','You do not have permission to add customer contracts.','لا توجد صلاحية إضافة عقود العملاء.','You do not have permission to add customer contracts.',true,now()),
  ('contracts.permission.edit','quotations','crm','error','لا توجد صلاحية تعديل عقود العملاء.','You do not have permission to edit customer contracts.','لا توجد صلاحية تعديل عقود العملاء.','You do not have permission to edit customer contracts.',true,now()),
  ('contracts.permission.save','quotations','crm','error','لا توجد صلاحية حفظ عقود العملاء.','You do not have permission to save customer contracts.','لا توجد صلاحية حفظ عقود العملاء.','You do not have permission to save customer contracts.',true,now()),
  ('contracts.permission.manage','quotations','crm','error','لا توجد صلاحية لإدارة عقود العملاء.','You do not have permission to manage customer contracts.','لا توجد صلاحية لإدارة عقود العملاء.','You do not have permission to manage customer contracts.',true,now()),
  ('contracts.permission.delete','quotations','crm','error','لا توجد صلاحية حذف عقود العملاء.','You do not have permission to delete customer contracts.','لا توجد صلاحية حذف عقود العملاء.','You do not have permission to delete customer contracts.',true,now()),
  ('contracts.validation.number','quotations','crm','error','أدخل رقم العقد.','Enter the contract number.','أدخل رقم العقد.','Enter the contract number.',true,now()),
  ('contracts.validation.amount','quotations','crm','error','قيمة العقد لا يمكن أن تكون سالبة.','Contract value cannot be negative.','قيمة العقد لا يمكن أن تكون سالبة.','Contract value cannot be negative.',true,now()),
  ('contracts.validation.rejectionReason','quotations','crm','error','اختر سبب رفض العقد.','Select the contract rejection reason.','اختر سبب رفض العقد.','Select the contract rejection reason.',true,now()),
  ('contracts.validation.duplicate','quotations','crm','format','رقم العقد {code} مسجل بالفعل ولا يمكن تكراره.','Contract number {code} is already registered and cannot be duplicated.','رقم العقد {code} مسجل بالفعل ولا يمكن تكراره.','Contract number {code} is already registered and cannot be duplicated.',true,now()),
  ('contracts.dialog.saving','quotations','crm','status','جاري الحفظ...','Saving...','جاري الحفظ...','Saving...',true,now()),
  ('contracts.error.save','quotations','crm','error','تعذر حفظ العقد.','Unable to save the contract.','تعذر حفظ العقد.','Unable to save the contract.',true,now()),
  ('contracts.error.delete','quotations','crm','error','تعذر حذف العقد.','Unable to delete the contract.','تعذر حذف العقد.','Unable to delete the contract.',true,now()),
  ('contracts.confirm.delete','quotations','crm','confirm','هل تريد حذف العقد {code}؟','Delete contract {code}?','هل تريد حذف العقد {code}؟','Delete contract {code}?',true,now())
)
insert into public.app_translations (translation_key,screen_key,module_name,text_type,ar_text,en_text,default_ar,default_en,is_active,updated_at)
select translation_key,screen_key,module_name,text_type,ar_text,en_text,default_ar,default_en,is_active,updated_at
from translation_seed
on conflict (translation_key) do update set
  screen_key = excluded.screen_key,
  module_name = excluded.module_name,
  text_type = excluded.text_type,
  ar_text = case when nullif(btrim(public.app_translations.ar_text),'') is null then excluded.ar_text else public.app_translations.ar_text end,
  en_text = case when nullif(btrim(public.app_translations.en_text),'') is null then excluded.en_text else public.app_translations.en_text end,
  default_ar = excluded.default_ar,
  default_en = excluded.default_en,
  is_active = true,
  updated_at = now();

commit;
