-- PETATOE P5.13.6 — Dashboard Localization Rollout
insert into public.app_translations
(translation_key,screen_key,module_name,text_type,ar_text,en_text,default_ar,default_en,is_active)
values
('dashboard.page.title','dashboard','dashboard','title','لوحة التحكم','Dashboard','لوحة التحكم','Dashboard',true),
('dashboard.page.subtitle','dashboard','dashboard','subtitle','ملخص بيانات العملاء والمتابعة','Customer and follow-up data summary','ملخص بيانات العملاء والمتابعة','Customer and follow-up data summary',true),
('dashboard.header.title','dashboard','dashboard','title','لوحة التحليل والمتابعة','Analytics & Monitoring Dashboard','لوحة التحليل والمتابعة','Analytics & Monitoring Dashboard',true),
('dashboard.header.note','dashboard','dashboard','help','استخدم الفلاتر لتحديث جميع المؤشرات والتحليلات في نفس الوقت.','Use the filters to update all indicators and analytics at the same time.','استخدم الفلاتر لتحديث جميع المؤشرات والتحليلات في نفس الوقت.','Use the filters to update all indicators and analytics at the same time.',true),
('dashboard.filter.allReps','dashboard','dashboard','option','كل المندوبين','All representatives','كل المندوبين','All representatives',true),
('dashboard.filter.fromAria','dashboard','dashboard','aria','من تاريخ','From date','من تاريخ','From date',true),
('dashboard.filter.toAria','dashboard','dashboard','aria','إلى تاريخ','To date','إلى تاريخ','To date',true),
('dashboard.filter.reset','dashboard','dashboard','button','إعادة تعيين','Reset','إعادة تعيين','Reset',true),
('dashboard.reps.title','dashboard','dashboard','title','أداء المندوبين','Representative Performance','أداء المندوبين','Representative Performance',true),
('dashboard.reps.note','dashboard','dashboard','help','العملاء، المتابعات، العروض، ونسبة التحويل','Customers, follow-ups, contracts, and conversion rate','العملاء، المتابعات، العروض، ونسبة التحويل','Customers, follow-ups, contracts, and conversion rate',true),
('dashboard.reps.settings','dashboard','dashboard','button','إعدادات ظهور المندوبين','Representative Visibility Settings','إعدادات ظهور المندوبين','Representative Visibility Settings',true),
('dashboard.contractStatus.title','dashboard','dashboard','title','حالات عقود العملاء','Customer Contract Statuses','حالات عقود العملاء','Customer Contract Statuses',true),
('dashboard.contractStatus.note','dashboard','dashboard','help','توزيع العروض حسب الحالة الحالية','Distribution of contracts by current status','توزيع العروض حسب الحالة الحالية','Distribution of contracts by current status',true),
('dashboard.noSale.title','dashboard','dashboard','title','أسباب عدم البيع','Reasons for No Sale','أسباب عدم البيع','Reasons for No Sale',true),
('dashboard.noSale.note','dashboard','dashboard','help','الأسباب الأكثر تكرارًا داخل الفترة','Most frequent reasons within the selected period','الأسباب الأكثر تكرارًا داخل الفترة','Most frequent reasons within the selected period',true),
('dashboard.activity.title','dashboard','dashboard','title','اتجاه النشاط خلال الفترة','Activity Trend During the Period','اتجاه النشاط خلال الفترة','Activity Trend During the Period',true),
('dashboard.activity.note','dashboard','dashboard','help','العملاء الجدد، المتابعات، وعقود العملاء حسب التاريخ','New customers, follow-ups, and customer contracts by date','العملاء الجدد، المتابعات، وعقود العملاء حسب التاريخ','New customers, follow-ups, and customer contracts by date',true),
('dashboard.recent.title','dashboard','dashboard','title','أحدث العملاء','Recent Customers','أحدث العملاء','Recent Customers',true),
('dashboard.recent.viewAll','dashboard','dashboard','button','عرض الكل','View All','عرض الكل','View All',true),
('dashboard.attention.title','dashboard','dashboard','title','المتابعات التي تحتاج انتباه','Follow-ups Requiring Attention','المتابعات التي تحتاج انتباه','Follow-ups Requiring Attention',true),
('dashboard.attention.view','dashboard','dashboard','button','عرض المتابعات','View Follow-ups','عرض المتابعات','View Follow-ups',true),
('dashboard.stats.customers','dashboard','dashboard','label','إجمالي العملاء','Total Customers','إجمالي العملاء','Total Customers',true),
('dashboard.stats.followups','dashboard','dashboard','label','إجمالي المتابعات','Total Follow-ups','إجمالي المتابعات','Total Follow-ups',true),
('dashboard.stats.today','dashboard','dashboard','label','متابعات اليوم','Today''s Follow-ups','متابعات اليوم','Today''s Follow-ups',true),
('dashboard.stats.overdue','dashboard','dashboard','label','متابعات متأخرة','Overdue Follow-ups','متابعات متأخرة','Overdue Follow-ups',true),
('dashboard.stats.contracts','dashboard','dashboard','label','عدد عقود العملاء','Customer Contracts','عدد عقود العملاء','Customer Contracts',true),
('dashboard.stats.contractValue','dashboard','dashboard','label','قيمة العقود','Contract Value','قيمة العقود','Contract Value',true),
('dashboard.stats.accepted','dashboard','dashboard','label','العقود المقبولة','Accepted Contracts','العقود المقبولة','Accepted Contracts',true),
('dashboard.stats.acceptedValue','dashboard','dashboard','label','قيمة المقبول','Accepted Value','قيمة المقبول','Accepted Value',true),
('dashboard.stats.rejected','dashboard','dashboard','label','العقود المرفوضة','Rejected Contracts','العقود المرفوضة','Rejected Contracts',true),
('dashboard.stats.conversion','dashboard','dashboard','label','نسبة التحويل','Conversion Rate','نسبة التحويل','Conversion Rate',true),
('dashboard.period.all','dashboard','dashboard','label','الفترة: جميع البيانات','Period: All data','الفترة: جميع البيانات','Period: All data',true),
('dashboard.period.range','dashboard','dashboard','format','الفترة: {from} — {to}','Period: {from} — {to}','الفترة: {from} — {to}','Period: {from} — {to}',true),
('dashboard.period.start','dashboard','dashboard','label','البداية','Start','البداية','Start',true),
('dashboard.period.today','dashboard','dashboard','label','اليوم','Today','اليوم','Today',true),
('dashboard.reps.conversion','dashboard','dashboard','format','نسبة التحويل {value}%','Conversion rate {value}%','نسبة التحويل {value}%','Conversion rate {value}%',true),
('dashboard.reps.followups','dashboard','dashboard','label','المتابعات','Follow-ups','المتابعات','Follow-ups',true),
('dashboard.reps.contracts','dashboard','dashboard','label','العقود','Contracts','العقود','Contracts',true),
('dashboard.reps.contractValue','dashboard','dashboard','label','قيمة العقود','Contract Value','قيمة العقود','Contract Value',true),
('dashboard.reps.conversionLabel','dashboard','dashboard','label','التحويل','Conversion','التحويل','Conversion',true),
('dashboard.reps.empty','dashboard','dashboard','empty','لا توجد بيانات أداء ضمن الفلاتر.','No performance data matches the filters.','لا توجد بيانات أداء ضمن الفلاتر.','No performance data matches the filters.',true),
('dashboard.chart.empty','dashboard','dashboard','empty','لا توجد بيانات كافية.','Not enough data.','لا توجد بيانات كافية.','Not enough data.',true),
('dashboard.activity.empty','dashboard','dashboard','empty','لا توجد بيانات زمنية كافية.','Not enough time-series data.','لا توجد بيانات زمنية كافية.','Not enough time-series data.',true),
('dashboard.activity.customers','dashboard','dashboard','label','العملاء','Customers','العملاء','Customers',true),
('dashboard.activity.followups','dashboard','dashboard','label','المتابعات','Follow-ups','المتابعات','Follow-ups',true),
('dashboard.activity.contracts','dashboard','dashboard','label','العروض','Contracts','العروض','Contracts',true),
('dashboard.activity.customersTitle','dashboard','dashboard','format','العملاء: {count}','Customers: {count}','العملاء: {count}','Customers: {count}',true),
('dashboard.activity.followupsTitle','dashboard','dashboard','format','المتابعات: {count}','Follow-ups: {count}','المتابعات: {count}','Follow-ups: {count}',true),
('dashboard.activity.contractsTitle','dashboard','dashboard','format','العروض: {count}','Contracts: {count}','العروض: {count}','Contracts: {count}',true),
('dashboard.recent.empty','dashboard','dashboard','empty','لا توجد بيانات عملاء.','No customer data.','لا توجد بيانات عملاء.','No customer data.',true),
('dashboard.attention.empty','dashboard','dashboard','empty','لا توجد متابعات تحتاج انتباهًا حاليًا.','No follow-ups currently require attention.','لا توجد متابعات تحتاج انتباهًا حاليًا.','No follow-ups currently require attention.',true),
('dashboard.mobile.quick','dashboard','dashboard','label','نظرة سريعة','Quick Overview','نظرة سريعة','Quick Overview',true),
('dashboard.mobile.title','dashboard','dashboard','title','لوحة التحكم','Dashboard','لوحة التحكم','Dashboard',true),
('dashboard.mobile.filterAria','dashboard','dashboard','aria','فتح فلاتر لوحة التحكم','Open dashboard filters','فتح فلاتر لوحة التحكم','Open dashboard filters',true),
('dashboard.mobile.refresh','dashboard','dashboard','button','تحديث','Refresh','تحديث','Refresh',true),
('dashboard.mobile.refreshAria','dashboard','dashboard','aria','تحديث لوحة التحكم','Refresh dashboard','تحديث لوحة التحكم','Refresh dashboard',true),
('dashboard.mobile.closeFilters','dashboard','dashboard','aria','إغلاق الفلاتر','Close filters','إغلاق الفلاتر','Close filters',true),
('dashboard.mobile.apply','dashboard','dashboard','button','تنفيذ الفلترة','Apply Filters','تنفيذ الفلترة','Apply Filters',true),
('dashboard.mobile.closeBackdrop','dashboard','dashboard','aria','إغلاق فلاتر لوحة التحكم','Close dashboard filters','إغلاق فلاتر لوحة التحكم','Close dashboard filters',true)
on conflict (translation_key) do update set
screen_key=excluded.screen_key,module_name=excluded.module_name,text_type=excluded.text_type,
default_ar=excluded.default_ar,default_en=excluded.default_en,
ar_text=case when coalesce(public.app_translations.ar_text,'')='' then excluded.ar_text else public.app_translations.ar_text end,
en_text=case when coalesce(public.app_translations.en_text,'')='' then excluded.en_text else public.app_translations.en_text end,
is_active=true;

select translation_key,ar_text,en_text from public.app_translations
where screen_key='dashboard' and (coalesce(trim(ar_text),'')='' or coalesce(trim(en_text),'')='');
